#!/bin/bash

if [ -f fort.73 -a -f fort.67 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
set pm3d map
set style data pm3d
set palette
set cbrange[:]
set zrange[:]
splot 'fort.73' using 1:2:(0.0):3 t 'Data coverage','fort.67' using 1:2:(0.0):(0.0) with lines lt 10  notitle
#end gnuplot commands
exit
EOF

$gplot bidon

else
echo No plot produced

fi