#!/bin/bash

if [ -f fort.67 -a -f fort.79 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
set pm3d  interpolate ii,ii map
set style data pm3d
set style line 9 linetype 1 lw 1 linecolor rgb "black"

#end gnuplot commands
exit
EOF

echo "splot 'fort.79' using" '1:2:(sqrt($3)):(sqrt($3))' "t 'Standard deviation', 'fort.67' using 1:2:(0.0) with lines ls 9  notitle" >> bidon

$gplot bidon

else
echo No plot produced

fi