#!/bin/bash

if [ -f ../output/trends.all.2.dat ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
plot '../output/trends.all.2.dat' using 1:2 with steps t 'Group 2 trends'
#end gnuplot commands
exit
EOF

$gplot bidon

else
echo No plot produced

fi