#!/bin/bash

if [ -f fort.67 -a -f fort.73 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands

set pm3d map
set style data pm3d
set palette
set cbrange[:]
set zrange[:]

#end gnuplot commands

EOF
echo \
"splot 'fort.73' using 1:2:(0.0):"'(log10($3))'" t 'Data coverage, Log10','fort.67' using 1:2:(0.0):(0.0) with lines lt 10  notitle" >> bidon


$gplot bidon

else
echo No plot produced

fi