#!/bin/bash
export LC_ALL=C 



if [ "$#" != "1" ]
then
Echo =======================================
Echo Usage:  divaguessform datafile
Echo =======================================
exit
fi

# First try to determine which delimiter by testing which one gives the
# maximum number of equal number of fields on the lines

NTABS=$(awk -F "\t" 'BEGIN {n=0;NFO=0} {if(substr($0,1,2) != "//") { if (NF==NFO) {n=n+1} else {NFO=NF}}} END {print n+NF}' $1)
NSEMI=$(awk -F ";" 'BEGIN {n=0;NFO=0} {if(substr($0,1,2) != "//") { if (NF==NFO) {n=n+1} else {NFO=NF}}} END {print n+NF}' $1)
delimiter="\t"
echo $NTABS and $NSEMI

if [ "$NSEMI" -gt "$NTABS" ]
then
delimiter=";"
fi

echo "$delimiter" > ODVdelimiter

awk -F "$delimiter" '{\
if(substr($0,1,2) != "//" && /ongitude/) { print $0 } 
}' $1 > ODVheader

awk -F "$delimiter" '{\
for(i=1;i<=NF;i++){{print $i "\t \t" i} }
}' ODVheader > ODVcolumns
