#!/bin/bash


FILENAME=driver
{
read isextractcomm
read isextractf
read iscontourcomm
read iscontour
read isdatacleancomm
read isdataclean
read minimumdatanumbercomm
read mindata
read isoptimisecomm
read isoptimise
read CLMINcomm
read CLMIN
read CLMAXcomm
read CLMAX
read SNMINcomm
read SNMIN
read SNMAXcomm
read SNMAX
read isanalysiscomm
read isanalysis
read lowerlevelcomm
read minlevel
read upperlevelcomm
read upperlevel
read isxmlgeneratcom
read isxmlgenerat
read isplotcomm
read isplot
} < $FILENAME




isxmlgenerat=$1

WDIR=$(pwd)
DIVADIR="../../DIVA3D"

mkdir -p ${DIVADIR}/divastripped/output
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis
mkdir -p ./output/3Danalysis/MetaDataXMLs
#
./dvtxtmetainfo > ./output/3Danalysis/DriverMetainfo
#
##################################################
# loop on years defined in yearlist
# loop on variables defined in varlist

#########################################################
for var in `cat varlist`
#########################################################
do
echo variable $var
#########################################################
for year in `cat yearlist`
#########################################################
do
echo year $year
#########################################################

yearb=${year:0:4}
yeare=${year:4:4}
monthb=${month:0:2}
monthe=${month:2:2}

echo ' '
echo ' =================== Running divadoNCDF ======================== '
echo ' =================== working on variable: ' $var ' and year: '$year 
echo ' '

rm -f ${DIVADIR}/divastripped/3DWORK/*
rm -rf ${DIVADIR}/divastripped/output/3Danalysis/* 

if [ -f './output/3Danalysis/'$var'.Metainfo.txt' ]; then
cp -v './output/3Danalysis/'$var'.Metainfo.txt'  ${DIVADIR}/divastripped/output/3Danalysis/.
fi

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCliste' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCliste' ${DIVADIR}/divastripped/output/3Danalysis/.

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCinfo' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCinfo' ${DIVADIR}/divastripped/output/3Danalysis/.

cp -v ./output/3Danalysis/Fields/GridInfo.dat ${DIVADIR}/divastripped/output/3Danalysis/.

cd ./output/3Danalysis/
for ncfile in `ls $var.*.anl.nc` ;do
echo $ncfile
cp -v $ncfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.nbrdata'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.3Dparam'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done
cd ../../

cd ${DIVADIR}/divastripped

echo ' '
echo '==================== Running diva4Dncwrite ========================'

varl=$var'.'$year
vld=0
if [ "$isxmlgenerat" -lt "0" ];then
vld=1
fi

#2013JMB

if [ -f "./output/metajmb" ]
then
rm -f ./output/metajmb
fi
let lev=0+$minlevel
let upperlevel=0+$upperlevel
echo SO SOS
while [ "$lev" -le "$upperlevel" ]
do
echo working on level $lev for $varl
let levn=10000+$lev

# exloit the 3DNC info file to know which data have been used

cat './output/3Danalysis/'$var'.'$year'.3DNCliste'



for ii in `cat './output/3Danalysis/'$var'.'$year'.3DNCliste' | awk '{print $1}' `


do
echo $ii
jmm=$(echo $ii | awk -F . '{print $3}')
jmt=$(echo $ii | awk -F . '{print $1}')
jmy=$(echo $ii | awk -F . '{print $2}')

echo So $jmm $jmt $jmy $levn

ls -l ${WDIR}/input/divadata/$jmt'.'$jmy'.'$jmm'.'$levn
depthval=$(head -$lev ${WDIR}/input/contour.depth | tail -1)
echo Depth $depthval

cat ${WDIR}/input/divadata/$jmt'.'$jmy'.'$jmm'.'$levn | awk -v depth=$depthval '{print $1,$2,depth,$9,$10}' >> ./output/metajmb


done


let lev=1+$lev
done
#2013JMB


echo ======
cat ./output/metajmb
echo ======

diva4Dncwrite $varl $vld
../bin/netcdfobsid.a ./output/metajmb ./output/3Danalysis/$var.$year.4Danl.nc


echo ' '
echo '========  Copying netcdf and metadata files to climatology output directory ======'
echo ' '

#echo now saving needs to be done
if [ -f "./output/3Danalysis/$var.$year.4Danl.nc" ];then
cp -v ./output/3Danalysis/$var.$year.4Danl.nc ${WDIR}/output/3Danalysis/.
fi
if [ -f "./output/3Danalysis/$var.4Danl.nc" ];then
cp -v ./output/3Danalysis/$var.4Danl.nc ${WDIR}/output/3Danalysis/.
fi
cp -v ./output/3Danalysis/$var'.4DNCMetainfo' ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/$var'.Metainfo.txt' ${WDIR}/output/3Danalysis/.

cd $WDIR

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCinfo'

fi

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCliste'

fi

cd $WDIR

echo '============================= divadoNCDF: end year loop    '$year

done

cat  ./output/3Danalysis/DriverMetainfo ./output/3Danalysis/$var'.Metainfo.txt' > ./output/3Danalysis/MetaDataXMLs/$var'.Textinfo.txt'

echo '============================= divadoNCDF: end var loop    '$var

done

echo =================================
echo Finished writing 4D NetCDF  files 
echo =================================
