#!/bin/bash
# 
echo ======================================================
echo Before additional elimination
wc -l "$1"
# Example below, use only data where latidute value is below 57+0.6*longitude
# and latitude larger than 10
#awk -F " " '{if ($2 < 57.0+0.6*$1) {print $0}}' $1 > bidon
#mv bidon $1
#awk -F " " '{if ($1 > 10) {print $0}}' $1 > bidon
#mv bidon $1
echo After additional elimination
wc -l "$1"
echo ======================================================
