#!/bin/bash

makeRef=0

echo =============================================
echo =============================================
echo ==                                         ==
echo ==   Procedure to test programs in : MESH  ==
echo ==                                         ==
echo =============================================
echo =============================================
echo ' '

echo Testing procedure in progress...
echo ================================
rm -f ./testing.log
rm -f ./*.a

# Chech program : gmshDriver.a
# -----------------------
fileToCheck=gmshDriver
echo Test : $fileToCheck
echo ------
echo Test : $fileToCheck >> testing.log
echo ------ >> testing.log

cp $divaDir/Bin/$fileToCheck.a ./$fileToCheck.a
cp $divaDir/Bin/gmsh ./gmsh

cp ./INPUTS/fort.10.$fileToCheck.$compiler ./fort.10
cp ./INPUTS/fort.11.$fileToCheck.$compiler ./fort.11
icoordchange=0
echo $icoordchange | ./$fileToCheck.a >> testing.log

if [ $makeRef == 1 ]
then
cp ./fort.22 ./OUTPUTS/fort.22.$fileToCheck.$compiler
cp ./fort.23 ./OUTPUTS/fort.23.$fileToCheck.$compiler
fi
 
diff -s ./fort.22 ./OUTPUTS/fort.22.$fileToCheck.$compiler >> testing.log
diff -s ./fort.23 ./OUTPUTS/fort.23.$fileToCheck.$compiler >> testing.log

rm ./fort.22
rm ./fort.23

icoordchange=1
echo $icoordchange | ./$fileToCheck.a >> testing.log

if [ $makeRef == 1 ]
then
cp ./fort.22 ./OUTPUTS/fort.22b.$fileToCheck.$compiler
cp ./fort.23 ./OUTPUTS/fort.23b.$fileToCheck.$compiler
fi
 
diff -s ./fort.22 ./OUTPUTS/fort.22b.$fileToCheck.$compiler >> testing.log
diff -s ./fort.23 ./OUTPUTS/fort.23b.$fileToCheck.$compiler >> testing.log

rm ./fort.10
rm ./fort.11
rm ./fort.22
rm ./fort.23
rm ./gmsh

rm ./$fileToCheck.*
echo ' ' >> testing.log

echo Testing procedure finished
echo ==========================
echo Check 'testing.log'

