#!/bin/bash

# Definition of the compiler and options
# ======================================
compiler=ifort

flag='-fast -warn all -implicitnone'

export compiler
export flag


# Definition of preprocessor options if needed
# ============================================
preprocessor='-cpp'
preprocessorFlag='-D=_BATCH_MODE_ -D=_INTELF90_ '$preproFlag

export preprocessor
export preprocessorFlag


# Definition of the library directory
# ====================================
libraryDir='-I'$divaModuleLib
libraryObj=$divaModuleLib/*.o

export libraryDir
export libraryObj

# Definition of the library directory
# ====================================
libraryPath='-L'$divaModuleLib
libraryLink='-ldiva -lMath -lVector -lMatrix -lArray -lSparseMatrix -lIO'

export libraryPath
export libraryLink
