#!/bin/bash

# Definition of the compiler and options
# ======================================
compiler=g95

flag='-O0'
#flag='-O3 -pedantic -fbounds-check -ftrace=full -finteger=0 -freal=zero -fpointer=null'

#flag='-O3 -Wall -Wimplicit-none -pedantic -fbounds-check -ftrace=full -finteger=0 -freal=zero -fpointer=null'
#flag='-O3 -Wall -Wimplicit-none -pedantic -fbounds-check -ftrace=full -Wno-unused-vars -Wno-unset-vars -march=pentium4 -finteger=0 -freal=zero -fpointer=null'

export compiler
export flag


# Definition of preprocessor options if needed
# ============================================
preprocessor='-cpp'
preprocessorFlag='-D=_BATCH_MODE_ -D=_G95_ '$preproFlag

export preprocessor
export preprocessorFlag


# Definition of the library
# =========================
source ./defineLibrary