#!/bin/bash

# Definition of the compiler and options
# ======================================
source $divaDir/compileBaseG95

# Definition of the library directory
# ===================================
library=$libraryDir' '$associateDir

echo 'Compiling ' $2

$compiler $flag $preprocessor $preprocessorFlag $library $1 -o $2.o

