#!/bin/bash


# Definition of preprocessor options if needed
# ============================================
preprocessorFlag=$preprocessorFlag' '$preproFlag

# Definition of the library directory
# ===================================
library=$libraryDir' '$associateDir

echo 'Compiling ' $2

if [ "$compiler" = ifort ] 
then
cp $1 fileToCompile.f90
$compiler $flag -c $preprocessor $preprocessorFlag $library fileToCompile.f90 -o $2.o
rm fileToCompile.f90
else
$compiler $flag -c $preprocessor $preprocessorFlag $library $1 -o $2.o
fi


