#!/bin/bash

# Definition of the compiler and options
# ======================================
compiler=gfortran

flag='-O3 -Wall -fimplicit-none -pedantic -fbounds-check '

export compiler
export flag


# Definition of preprocessor options if needed
# ============================================
preprocessor='-x f95-cpp-input '
preprocessorFlag='-D=_BATCH_MODE_  -D=_GFORTRAN_ '$preproFlag

export preprocessor
export preprocessorFlag


# Definition of the library directory
# ====================================
libraryDir='-I'$divaModuleLib
libraryObj=$divaModuleLib/*.o

export libraryDir
export libraryObj
