#!/bin/bash

# Definition of the compiler and options
# ======================================
compiler=g95

flag='-O3 -Wall -Wimplicit-none -pedantic -fbounds-check -ftrace=full -march=pentium4 -finteger=0 -freal=zero -fpointer=null'
#flag='-O3 -Wall -Wimplicit-none -pedantic -fbounds-check -ftrace=full -Wno-unused-vars -Wno-unset-vars -march=pentium4 -finteger=0 -freal=zero -fpointer=null'

export compiler
export flag


# Definition of preprocessor options if needed
# ============================================
preprocessor='-cpp'
preprocessorFlag='-D=_BATCH_MODE_ -D=_G95_ '$preproFlag

export preprocessor
export preprocessorFlag


# Definition of the library directory
# ====================================
libraryDir='-I'$divaModuleLib
libraryObj=$divaModuleLib/*.o

export libraryDir
export libraryObj

# Definition of the library directory
# ====================================
libraryMod='-I'$divaModuleMod
libraryPath='-L'$divaModuleLib
libraryLink='-ldiva'$compiler
libraryLink=$libraryLink' -lCommonDiva'$compiler
libraryLink=$libraryLink' -lMath'$compiler
libraryLink=$libraryLink' -lVector'$compiler
libraryLink=$libraryLink' -lMatrix'$compiler
libraryLink=$libraryLink' -lArray'$compiler
libraryLink=$libraryLink' -lSparseMatrix'$compiler
libraryLink=$libraryLink' -lIO'$compiler
#libraryLink=$libraryLink' -lMesh'$compiler

export libraryMod
export libraryPath
export libraryLink
