#!/bin/bash

# Definition of the compiler and options
# ======================================
compiler=ifort

flag='-fast'
#flag='-fast -warn all -implicitnone'
#flag='-fast -xSSE4.2 -unroll-aggressive -scalar-rep -inline-level=2 -warn all -implicitnone'
export compiler
export flag


# Definition of preprocessor options if needed
# ============================================
preprocessor='-cpp'
preprocessorFlag='-D=_BATCH_MODE_ -D=_INTELF90_ '$preproFlag

export preprocessor
export preprocessorFlag


# Definition of the library
# =========================
source ./defineLibrary
