#!/bin/bash

# Definition of the compiler and options
# ======================================
compiler=gfortran
flag='-O0 '
#flag='-O3 -pedantic -ffree-line-length-none -fmax-identifier-length=63 '
#flag='-O3 -Wall -fimplicit-none -pedantic -fbounds-check -ffree-line-length-none -fmax-identifier-length=63 '

export compiler
export flag


# Definition of preprocessor options if needed
# ============================================
preprocessor='-x f95-cpp-input '
preprocessorFlag='-D=_BATCH_MODE_  -D_GFORTRAN_ '$preproFlag

export preprocessor
export preprocessorFlag


# Definition of the library
# =========================
source ./defineLibrary
