#!/bin/bash

# Definition of the compiler and options
# ======================================
compiler=ifort

flag='-fast -warn all -implicitnone'

export compiler
export flag


# Definition of preprocessor options if needed
# ============================================
preprocessor='-cpp'
preprocessorFlag='-D=_BATCH_MODE_ -D=_INTELF90_ '$preproFlag

export preprocessor
export preprocessorFlag


# Definition of the library directory
# ====================================
libraryDir='-I'$divaModuleLib
libraryObj=$divaModuleLib/*.o

export libraryDir
export libraryObj

# Definition of the library directory
# ====================================
libraryMod='-I'$divaModuleMod
libraryPath='-L'$divaModuleLib
libraryLink='-ldiva'$compiler
libraryLink=$libraryLink' -lCommonDiva'$compiler
libraryLink=$libraryLink' -lMath'$compiler
libraryLink=$libraryLink' -lVector'$compiler
libraryLink=$libraryLink' -lMatrix'$compiler
libraryLink=$libraryLink' -lArray'$compiler
libraryLink=$libraryLink' -lSparseMatrix'$compiler
libraryLink=$libraryLink' -lIO'$compiler
libraryLink=$libraryLink' -lMesh'$compiler

export libraryMod
export libraryPath
export libraryLink
