#!/bin/bash

echo ============================
echo ============================
echo ==                        ==
echo ==   Compilation of DIVA  ==
echo ==                        ==
echo ============================
echo ============================
echo ' '

divaDir=$PWD

export divaDir

# Compilation of modules
# ======================

cd $divaDir/Module
./divaCompileModuleCygwin

echo ' '
echo --------------------
echo Compilation finished
echo --------------------
echo ' '

cd $divaDir

