#!/bin/bash

echo ====================================
echo ====================================
echo ==                                ==
echo ==   Compilation of DIVA Modules  ==
echo ==                                ==
echo ====================================
echo ====================================
echo ' '

baseDir=$PWD
divaModuleLib=$baseDir/Module/lib

rm $divaModuleLib/*

echo =====================
echo =====================
echo = Compiling Modules =
echo =====================
echo =====================
echo ' '

cd $baseDir/Mathematic
./divaCompileModuleMathematicCygwin

echo --------------------
echo Compilation finished
echo --------------------
echo ' '

cd $baseDir

