#!/bin/bash

rm -f $divaDir/error.log
rm -f $divaDir/testing.log

_WITH_UTIL_=1 ; export _WITH_UTIL_
_WITH_MESH_=1 ; export _WITH_MESH_

# Testing Util
# ------------
if [ $_WITH_UTIL_ == 1 ]
then
cd $divaDir/Util/TESTDIRECTORY
./testDivaUtil
cat $divaDir/Util/TESTDIRECTORY/testing.log >> $divaDir/testing.log
fi

# Testing Mesh
# ------------
if [ $_WITH_MESH_ == 1 ]
then
cd $divaDir/Mesh/TESTDIRECTORY
./testDivaMesh
cat $divaDir/Mesh/TESTDIRECTORY/testing.log >> $divaDir/testing.log
fi









if [ -f $divaDir/testing.log ]
then
echo 'Check the testing procedure : testing.log'
fi

