#!/bin/bash

rm -f *.o
rm -f *.mod

libName=libMath$compiler.a
export libName

rm -f $divaModuleLib/$libName

# Compilation of : moduleNorm
# ===========================
$divaDir/compileFile moduleNorm.f95 moduleNorm
echo ' '

# Compilation of : VectorReal4
# ============================
dataType='Real4' ; export dataType
Kind='_REAL_' ; export Kind
arrayType='vectorReal4' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType

./compileGenericFirstStep

# Compilation of : VectorReal8
# ============================
dataType=Real8 ; export dataType
Kind='_REAL_' ; export Kind
arrayType='vectorReal8' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType

./compileGenericFirstStep

# Compilation of : VectorInteger2
# ===============================
dataType=Integer2 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='vectorInteger2' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType

./compileGenericFirstStep

# Compilation of : VectorInteger4
# ===============================
dataType=Integer4 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='vectorInteger4' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType

./compileGenericFirstStep

# Compilation of : VectorInteger8
# ===============================
dataType=Integer8 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='vectorInteger8' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType

./compileGenericFirstStep


# Compilation of : MatrixReal4
# ============================
dataType='Real4' ; export dataType
Kind='_REAL_' ; export Kind
arrayType='matrixReal4' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType

./compileGenericFirstStep

# Compilation of : MatrixReal8
# ============================
dataType='Real8' ; export dataType
Kind='_REAL_' ; export Kind
arrayType='matrixReal8' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType

./compileGenericFirstStep

# Compilation of : MatrixInteger2
# ===============================
dataType=Integer2 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='matrixInteger2' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType

./compileGenericFirstStep

# Compilation of : MatrixInteger4
# ===============================
dataType=Integer4 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='matrixInteger4' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType

./compileGenericFirstStep

# Compilation of : MatrixInteger8
# ===============================
dataType=Integer8 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='matrixInteger8' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType

./compileGenericFirstStep

# Compilation of : ArrayReal4
# ============================
dataType='Real4' ; export dataType
Kind='_REAL_' ; export Kind
arrayType='arrayReal4' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType

./compileGenericFirstStep

# Compilation of : ArrayReal8
# ============================
dataType='Real8' ; export dataType
Kind='_REAL_' ; export Kind
arrayType='arrayReal8' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType

./compileGenericFirstStep

# Compilation of : ArrayInteger2
# ===============================
dataType=Integer2 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='arrayInteger2' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType

./compileGenericFirstStep

# Compilation of : ArrayInteger4
# ===============================
dataType=Integer4 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='arrayInteger4' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType

./compileGenericFirstStep

# Compilation of : ArrayInteger8
# ===============================
dataType=Integer8 ; export dataType
Kind='_INTEGER_' ; export Kind
arrayType='arrayInteger8' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType

./compileGenericFirstStep

mv *.mod $divaModuleLib
