#!/bin/bash

rm -f *.o
rm -f *.mod

libName=libMath$compiler.a
export libName

# Compilation of : VectorReal4
# ============================
dataType='Real4' ; export dataType
arrayType='vectorReal4' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType
Kind='_REAL_' ; export Kind

./compileGenericSecondStep

# Compilation of : VectorReal8
# ============================
dataType='Real8' ; export dataType
arrayType='vectorReal8' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType
Kind='_REAL_' ; export Kind

./compileGenericSecondStep

# Compilation of : VectorInteger2
# ===============================
dataType='Integer2' ; export dataType
arrayType='vectorInteger2' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

# Compilation of : VectorInteger4
# ===============================
dataType='Integer4' ; export dataType
arrayType='vectorInteger4' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

# Compilation of : VectorInteger8
# ===============================
dataType='Integer8' ; export dataType
arrayType='vectorInteger8' ; export arrayType
arrayDimension='_ARRAY_1D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep


# Compilation of : MatrixReal4
# ============================
dataType='Real4' ; export dataType
arrayType='matrixReal4' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType
Kind='_REAL_' ; export Kind

./compileGenericSecondStep

# Compilation of : MatrixReal8
# ============================
dataType='Real8' ; export dataType
arrayType='matrixReal8' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType
Kind='_REAL_' ; export Kind

./compileGenericSecondStep

# Compilation of : MatrixInteger2
# ===============================
dataType='Integer2' ; export dataType
arrayType='matrixInteger2' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

# Compilation of : MatrixInteger4
# ===============================
dataType='Integer4' ; export dataType
arrayType='matrixInteger4' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

# Compilation of : MatrixInteger8
# ===============================
dataType='Integer8' ; export dataType
arrayType='matrixInteger8' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

# Compilation of : ArrayReal4
# ============================
dataType='Real4' ; export dataType
arrayType='arrayReal4' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType
Kind='_REAL_' ; export Kind

./compileGenericSecondStep

# Compilation of : ArrayReal8
# ============================
dataType='Real8' ; export dataType
arrayType='arrayReal8' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType
Kind='_REAL_' ; export Kind

./compileGenericSecondStep

# Compilation of : ArrayInteger2
# ===============================
dataType='Integer2' ; export dataType
arrayType='arrayInteger2' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

# Compilation of : ArrayInteger4
# ===============================
dataType='Integer4' ; export dataType
arrayType='arrayInteger4' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

# Compilation of : ArrayInteger8
# ===============================
dataType='Integer8' ; export dataType
arrayType='arrayInteger8' ; export arrayType
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileGenericSecondStep

mv *.mod $divaModuleLib
