#!/bin/bash

moduleArrayDefinition='module'$arrayType'Definition' ; export moduleArrayDefinition
moduleWorkingArray='moduleWorking'$arrayType ; export moduleWorkingArray
moduleMemoryArrayManagement='moduleMemoryManagement'$arrayType ; export moduleMemoryArrayManagement
moduleValuesArrayManagement='moduleValuesManagement'$arrayType ; export moduleValuesArrayManagement
moduleWriteManagement='moduleWrite'$dataType ; export moduleWriteManagement 
moduleIOArrayManagement='moduleIO'$arrayType ; export moduleIOArrayManagement

flag0='-DmoduleArrayDefinition='$moduleArrayDefinition
flag1='-D'$arrayDimension
flag2='-DVARType='$VARType
flag3='-DarrayType='$arrayType
flag4='-DmoduleWorkingArray='$moduleWorkingArray
flag5='-DmoduleMemoryArrayManagement='$moduleMemoryArrayManagement
flag6='-DmoduleValuesArrayManagement='$moduleValuesArrayManagement
flag7='-DmoduleWrite='$moduleWriteManagement
flag8='-D'$Kind
flag9='-D'$dataType
flag10='-DmoduleIOArrayManagement='$moduleIOArrayManagement

preproFlag=$preproFlag' '$flag0
preproFlag=$preproFlag' '$flag1
preproFlag=$preproFlag' '$flag2
preproFlag=$preproFlag' '$flag3
preproFlag=$preproFlag' '$flag4
preproFlag=$preproFlag' '$flag5
preproFlag=$preproFlag' '$flag6
preproFlag=$preproFlag' '$flag7
preproFlag=$preproFlag' '$flag8
preproFlag=$preproFlag' '$flag9
preproFlag=$preproFlag' '$flag10

export preproFlag
