#!/bin/bash



echo //////////////////////////////////////////////////
echo                 Generating topography
echo //////////////////////////////////////////////////
echo ' '

echo Cleaning up old files
echo ' '
rm -f ./divawork/fort.10
rm -f ./divawork/fort.11
rm -f ./divawork/fort.12
rm -f ./divawork/fort.20
echo Finished cleaning 

FILENAME=./input/topo.asc
head -1 $FILENAME > bidon
FNAME=bidon
{ 
read AA BB CC DD EE
} < $FNAME
echo $AA $BB $CC $DD $EE
head -2 $FILENAME | tail -1 > bidon
FNAME=bidon
{ 
read AAB BBB CCB DDB EEB
} < $FNAME
echo $AAB $BBB $CCB $DDB $EEB

echo Making TopoInfo.dat
echo ${AA#*:} > ./output/TopoInfo.dat
echo ${CC#*:} >> ./output/TopoInfo.dat
echo ${EE#*:} >> ./output/TopoInfo.dat
echo ${EE#*:} >> ./output/TopoInfo.dat
echo ${AAB#*:} >> ./output/TopoInfo.dat
echo ${BBB#*:} >> ./output/TopoInfo.dat
echo   >> ./output/TopoInfo.dat
cat ./output/TopoInfo.dat

mv ./output/TopoInfo.dat  ./divawork/fort.10
cat ./input/topo.asc > ./divawork/fort.11

cd ./divawork
../../bin/dbdb2diva.a
cd ..
mv ./divawork/fort.12 ./output/topo.grd
mv ./divawork/fort.20 ./output/TopoInfo.dat
rm ./divawork/fort.10
rm ./divawork/fort.11

echo -----------------------
echo Topography is generated 
echo -----------------------

if [ "$1" == "-r" ]
then
echo 'Moving topography files into ./input directory'
cp -v ./output/topo.grd ./input
cp -v ./output/TopoInfo.dat ./input
fi