#!/bin/bash



echo ///////////////////////////
echo      DIVA compilation
echo ///////////////////////////
echo ' ' 


# GNU-cygwin, netcdf compiled for no-cygwin
compiler=g77
flags='-O3'

noglobals='-Wno-globals'
nocyg='-O3 -mno-cygwin'
nclib=./Win32/libnetcdf.a  


# PGI
#compiler=pgf77
#flags='-O3'
# possible -Bstatic
##noglobals='-Wno-globals'
##nocyg=''
#nclib=/u/acapet/Lib/netcdf-3.6.1/lib/libnetcdf.a  

# SGI
#compiler=f77
#flags='-O3'
##noglobals='-Wno-globals'
##nocyg=''
#nclib=libnetcdf.a  


# ifort
#compiler=ifort
#flags='-O3 -assume bscc'
#possibly -static
##noglobals='-Wno-globals'
##nocyg=''
#nclib=libnetcdf.a  


Plplot=Plplot
Plplot=NoPlplot

# gui = 1 for GUI programs to be compiled
# netcdf = 1 for GUI programs to be compiled

gui=1
netcdf=1


##########################
# end of user parameters #
##########################


echo Compiling CALC programs
echo -----------------------
echo ' ' 

cd Calc
$compiler $flags *.f -o diva.a
n1=`ls -1p *.a | grep -vc "/$"`
n1max=1

echo You have compiled $n1
echo programs out of $n1max
echo 1 >> ./compilation.log

mv diva.a ../../../bin/
rm -f *.o


if [ "$gui" = 1 ]
then

echo ' '
echo Compiling GUI programs
echo ----------------------
echo ' '

cd ../Extensions
$compiler -c $flags ureadc.f
$compiler -c $flags uwritc.f
$compiler $noglobals $nocyg extract.f  -o extract.a $nclib

for jj in `ls *.f`
do
if [ "$jj" != "ureadc.f" ]
then
if [ "$jj" != "uwritc.f" ]
then
if [ "$jj" != "extract.f" ]
then
echo $jj
$compiler $nocyg $jj  $nclib -o `basename $jj .f`.a
fi
fi
fi
done
n2=`ls -1p *.a | grep -vc "/$"` 
let n2=$n2+2
n2max=`ls -1p *.f | grep -vc "/$"` 

echo You have compiled $n2
echo out of $n2max  

mv *.a ../../../bin/

else
n2=0
n2max=0

fi


echo ' '
echo Compiling MESH programs
echo -----------------------
echo ' '

cd ../Mesh
for jj in `ls *.f`
do
echo $jj
$compiler $flags $jj -o `basename $jj .f`.a
done

n3=`ls -1p *.a | grep -vc "/$"` 
n3max=`ls -1p *.f | grep -vc "/$"` 

echo You have compiled $n3 programs 
echo out of $n3max 

mv *.a ../../../bin/


if [ "$netcdf" = 1 ]
then

echo ' '
echo Compiling NETCDF programs
echo -------------------------
echo ' '

cd ../NC
for jj in `ls *.f`
do
echo $jj
$compiler  $nocyg $jj -o `basename $jj .f`.a $nclib
done

n4=`ls -1p *.a | grep -vc "/$"` 
n4max=`ls -1p *.f | grep -vc "/$"` 

echo You have compiled $n4 programs 
echo out of $n4max 

mv *.a ../../../bin/

else
n4=0
n4max=0

fi



echo ' '
echo Compiling PLPLOT programs
echo -------------------------
echo ' '

cd ../$Plplot
for jj in `ls *.f`
do
echo $jj
$compiler $flags $jj -o `basename $jj .f`.a
done

n5=`ls -1p *.a | grep -vc "/$"` 
n5max=`ls -1p *.f | grep -vc "/$"` 

echo You have compiled $n5 programs 
echo out of $n5max 

mv *.a ../../../bin/




echo ' '
echo Compiling UTILITIES programs
echo ----------------------------
echo ' '

cd ../Util
for jj in `ls *.f`
do
echo $jj
$compiler $flags $jj -o `basename $jj .f`.a
done

n6=`ls -1p *.a | grep -vc "/$"` 
n6max=`ls -1p *.f | grep -vc "/$"` 

echo You have compiled $n6 programs 
echo out of $n6max 

mv *.a ../../../bin/





echo ' '
echo Compiling PIPETEST programs
echo ----------------------------
echo ' '

cd ../Pipetest
for jj in `ls *.f`
do
echo $jj
$compiler $flags $jj -o `basename $jj .f`.a
done

n7=`ls -1p *.a | grep -vc "/$"` 
n7max=`ls -1p *.f | grep -vc "/$"` 

echo You have compiled $n7 programs 
echo out of $n7max 

#mv *.a ../../../bin/


echo --------------------
echo Compilation finished
echo --------------------
echo ' '

cd .. 

# total number of compiled programs

let ntotal=$n1+$n2+$n3+$n4+$n5+$n6+$n7
let ntotalmax=$n1max+$n2max+$n3max+$n4max+$n5max+$n6max+$n7max

echo You have compiled $ntotal programs 
echo out of $ntotalmax 

echo '  '
echo Writing log file...
echo '  '


echo 'compiler:          '$compiler  >> ./compilation.log
echo 'compilation flags: '$flags  >> ./compilation.log
echo 'Calc directory:       '$n1/$n1max programs compiled >> ./compilation.log
echo 'Extensions directory: '$n2/$n2max programs compiled >> ./compilation.log
echo 'Mesh directory:       '$n3/$n3max programs compiled >> ./compilation.log
echo 'NC directory:         '$n4/$n4max programs compiled >> ./compilation.log
echo 'PlPlot directory:     '$n5/$n5max programs compiled >> ./compilation.log
echo 'Util directory:       '$n6/$n6max programs compiled >> ./compilation.log
echo 'Pipetest directory:       '$n7/$n7max programs compiled >> ./compilation.log
echo '----------------------------------------------------------' >> ./compilation.log
echo 'TOTAL:                '$ntotal/$ntotalmax programs compiled >> ./compilation.log
echo '----------------------------------------------------------' >> ./compilation.log
echo ' '

echo '  '
echo ... written in compilation.log
echo '  '


cd ../../divastripped
mkdir -p ./divawork
mkdir -p ./meshgenwork
mkdir -p ./output
mkdir -p ./input
mkdir -p ./output/ghertonetcdf
mkdir -p ./output/meshvisu