#!/bin/bash

echo ==========================================
echo ==========================================
echo ==                                      ==
echo ==   Compilation of DIVA Calc Module  ==
echo ==                                      ==
echo ==========================================
echo ==========================================
echo ' '

baseDir=$PWD

echo ===========================
echo ===========================
echo = Compiling Calc Module =
echo ===========================
echo ===========================
echo ' '

preproFlag=''
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir

libName=libCalc$compiler.a
export libName
rm -f $divaModuleLib/$libName

# Compilation of : moduleCalc
# =============================
#$divaDir/compileFile moduleCalc.f95 moduleCalc

$divaDir/compileFile allody.f allody fSTD
$divaDir/compileFile bcondi.f bcondi fSTD
$divaDir/compileFile bilinin.f bilinin fSTD
$divaDir/compileFile constr.f constr fSTD
$divaDir/compileFile coord.f coord fSTD
$divaDir/compileFile covar.f covar fSTD
$divaDir/compileFile datapr.f datapr fSTD
$divaDir/compileFile dataqc.f dataqc fSTD
$divaDir/compileFile esterr.f esterr fSTD
$divaDir/compileFile findca.f findca fSTD
$divaDir/compileFile gcvfac.f gcvfac fSTD
$divaDir/compileFile mathpr.f mathpr fSTD
$divaDir/compileFile meshgn.f meshgn fSTD
$divaDir/compileFile optimi.f optimi fSTD
$divaDir/compileFile repeltest.f repeltest fSTD
$divaDir/compileFile shapef.f shapef fSTD
$divaDir/compileFile solver.f solver fSTD
$divaDir/compileFile stores.f stores fSTD
$divaDir/compileFile topolo.f topolo fSTD
$divaDir/compileFile ureadc.f ureadc fSTD
$divaDir/compileFile utilit.f utilit fSTD
$divaDir/compileFile uur.f uur fSTD
$divaDir/compileFile uwrit2.f uwrit2 fSTD
$divaDir/compileFile varl.f varl fSTD
$divaDir/compileFile vtools.f vtools fSTD


echo ' '

#mv *.mod $divaModuleLib

cd $baseDir

