#!/bin/bash

echo "Compiling object :" $arrayType
echo "------------------"

source ../Generic/flagForGenericFirstStep
source ./flagForVectorFirstStep

$divaDir/compileFile moduleMathematicArray1D.f95 $moduleMathematicArray1D
$divaDir/compileFile moduleMemoryArray1DManagement.f95 $moduleMemoryArray1DManagement
$divaDir/compileFile moduleValuesArray1DManagement.f95 $moduleValuesArray1DManagement

echo ' '