#!/bin/bash

if [ -f fort.68 -a -f fort.99 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
set pm3d  interpolate ii,ii map
set style data pm3d
#set palette defined ( 0 "white", 1 "red", 2 "dark-red" )
set style line 6 linecolor rgbcolor "black" pt 7 ps 0.5 
set style line 9 linetype 1 lw 1 linecolor rgb "black"
splot 'fort.68' using 1:2:4:4 t 'Error field and data location','fort.99' using 1:2:(0.0) with  points ls 6 notitle, 'fort.67' using 1:2:(0.0) with lines ls 9  notitle
#set palette rgbformulae 33,13,10
#end gnuplot commands
exit
EOF

$gplot bidon

else
echo No plot produced

fi
