#!/bin/bash

if [ -f fort.68 -a -f fort.67 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
set pm3d interpolate ii,ii  map
set style data pm3d
#set palette defined ( 0 "white", 1 "red", 2 "dark-red" )
set angles degrees

set xtics ("longref" 0)
set style line 9 linetype 1 lw 1 linecolor rgb "black"

#end gnuplot commands
exit
EOF
echo \
"splot 'fort.68' using " '(($1-longref)*cos($2)):($2):(0.0):($4) ' "t 'Error field, projected'#,'fort.67' using " '(($1-longref)*cos($2)):($2):(0.0) with lines ls 9  notitle '>> bidon


$gplot bidon

else
echo No plot produced

fi

