#!/bin/bash
#
#####################################################
#
#####################################################
#
mkdir -p ./3DWORK
rm -f ./3DWORK/fort.44
FILENAME=./input/takeout.coord
if [ -f "$FILENAME" ]
then
echo Going  to modify gebco.topo
nblines=`cat './input/takeout.coord' |wc -l` 
ln=1
#
  Fileinf=$FILENAME
{
#
while [ $ln -le $nblines ]
do
read location
echo location nbr $ln : $location
echo $location > ./3DWORK/fort.44
cd ./3DWORK
../../bin/gebprep.a
cd ..
mv ./input/modif_topo.gebco  ./input/topo.gebco
let ln=$ln+1
done
} < $Fileinf
#
else
echo Did not find any $FILENAME  file
cd ./3DWORK
../../bin/gebprep.a
cd ..
mv ./input/modif_topo.gebco  ./input/topo.gebco
fi
#
