#!/bin/bash
#
#     WRITES RL.dat from mask.nc netcdf file
# 
#####################################################
#
cd ./3DWORK/
if [ -f ../input/mask.nc ];then
cp ../input/mask.nc .
else
echo 'dvncmask2RL: Did not find ../input/mask.nc file '
exit
fi
#
../../bin/ncmask2RL.a

cp RL.dat RLInfo.dat ../input/.
cp RL.dat RLInfo.dat ../output/.

rm -f mask.nc

cd ../
