#!/bin/bash

echo ========================================
echo ========================================
echo ==                                    ==
echo ==   Compilation of DIVA Mesh Module  ==
echo ==                                    ==
echo ========================================
echo ========================================
echo ' '

baseDir=$PWD

echo =========================
echo =========================
echo = Compiling Mesh Module =
echo =========================
echo =========================
echo ' '

preproFlag=''
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir
libName=libMesh$compiler.a
export libName
rm -f $divaModuleLib/$libName

# Compilation of : node
# =====================
node='node' ; export node
VARType='REAL(KIND=8)' ; export VARType
moduleNodeDefinition='module'$node ; export moduleNodeDefinition
moduleNodeDataBaseDefinition='moduleSpecificDataBase'$node ; export moduleNodeDataBaseDefinition
moduleNodeDataBase=$node'Interface'
moduleGenericDataBase='moduleGenericDataBase'$node
moduleGenericTypeDataBaseDefinition='moduleDataBaseDefinition'$node 

flagNode0='-DnodeType='$node
flagNode1='-DVARType='$VARType
flagNode2='-DmoduleNodeDefinition='$moduleNodeDefinition
flagNode3='-DmoduleNodeDataBaseDefinition='$moduleNodeDataBaseDefinition
flagNode4='-DmoduleNodeDataBase='$moduleNodeDataBase
flagNode5='-DmoduleGenericDataBase='$moduleGenericDataBase
flagNode6='-DmoduleGenericTypeDataBaseDefinition='$moduleGenericTypeDataBaseDefinition

preproFlag=$preproFlag' '$flagNode0
preproFlag=$preproFlag' '$flagNode1
preproFlag=$preproFlag' '$flagNode2
preproFlag=$preproFlag' '$flagNode3
preproFlag=$preproFlag' '$flagNode4
preproFlag=$preproFlag' '$flagNode5
preproFlag=$preproFlag' '$flagNode6

export preproFlag

$divaDir/compileFile moduleNodeDefinition.f95 $moduleNodeDefinition
$divaDir/compileFile moduleNodeDataBaseDefinition.f95 $moduleNodeDataBaseDefinition
$divaDir/Module/DataBase/divaCompileDataBase _DB_1D_ $node $moduleNodeDefinition $moduleNodeDataBaseDefinition
$divaDir/compileFile moduleNodeDataBase.f95 $moduleNodeDataBase

echo ' '
# Compilation of : line
# =====================
line='line' ; export line
moduleLineDefinition='module'$line ; export moduleLineDefinition
moduleLineDataBaseDefinition='moduleSpecificDataBase'$line ; export moduleLineDataBaseDefinition
moduleLineDataBase=$line'Interface'
moduleGenericDataBase='moduleGenericDataBase'$line
moduleGenericTypeDataBaseDefinition='moduleDataBaseDefinition'$line 

flagLine0='-DlineType='$line
flagLine1='-DVARType='$VARType
flagLine2='-DmoduleLineDefinition='$moduleLineDefinition
flagLine3='-DmoduleLineDataBaseDefinition='$moduleLineDataBaseDefinition
flagLine4='-DmoduleLineDataBase='$moduleLineDataBase
flagLine5='-DmoduleGenericDataBase='$moduleGenericDataBase
flagLine6='-DmoduleGenericTypeDataBaseDefinition='$moduleGenericTypeDataBaseDefinition

preproFlag=$flagLine0
preproFlag=$preproFlag' '$flagLine1
preproFlag=$preproFlag' '$flagLine2
preproFlag=$preproFlag' '$flagLine3
preproFlag=$preproFlag' '$flagLine4
preproFlag=$preproFlag' '$flagLine5
preproFlag=$preproFlag' '$flagLine6
preproFlag=$preproFlag' '$flagNode0
preproFlag=$preproFlag' '$flagNode2
preproFlag=$preproFlag' '$flagNode3

export preproFlag

$divaDir/compileFile moduleLineDefinition.f95 $moduleLineDefinition
$divaDir/compileFile moduleLineDataBaseDefinition.f95 $moduleLineDataBaseDefinition
$divaDir/Module/DataBase/divaCompileDataBase _DB_1D_ $line $moduleLineDefinition $moduleLineDataBaseDefinition
$divaDir/compileFile moduleLineDataBase.f95 $moduleLineDataBase

echo ' '
# Compilation of : moduleCoordinateInformation
# ============================================
REALType='REAL(KIND=8)'
INTEGERType='INTEGER'

flag0='-DREALType='$REALType
flag1='-DINTEGERType='$INTEGERType

preproFlag=$flag0
preproFlag=$preproFlag' '$flag1

export preproFlag
$divaDir/compileFile moduleCoordinateInformation.f95 moduleCoordinateInformation


mv *.mod $divaModuleLib

cd $baseDir

