#!/bin/bash

if [ -f fort.68 -a -f fort.69 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
set pm3d map

#set palette defined ( 0 "dark-blue", 1 "blue", 1.7 "green", 2.5 "yellow", 2.6 "yellow", 4 "red", 5 "dark-red" )
set style line 10 linetype 1 lw 2 linecolor rgb "yellow"
set style line 9 linetype 1 lw 1 linecolor rgb "light-gray"



splot 'fort.68' using 1:2:(-0.1):3 with pm3d t 'Analysis and mesh','fort.69' using 1:2:(-0.05) with lines ls 9 notitle

#set palette rgbformulae 33,13,10
#end gnuplot commands
exit
EOF

$gplot bidon

else
echo No plot produced

fi