#!/bin/bash

if [ -f ../output/covariance.dat -a -f ../output/covariance.dat ] 
then

echo gnuplot is $gplot
#awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands

echo \
"plot '../output/covariance.dat' using 1:2 with lines t 'sampled covariance', \
'../output/covariance.dat' using 1:("'$2+$4'") with lines t 'error interval on covariance', \
 '../output/covariance.dat' using 1:("'$2-$4'") with lines ls 2 notitle, \
 '../output/covariancefit.dat' using 1:2 with points t 'covariance used for fitting', \
 '../output/covariancefit.dat' using 1:3 with lines t 'fitted Bessel covariance',\
  '../output/covariance.dat' using 1:5  with points axes x1y2 t 'weights' "\
>> bidon
#end gnuplot commands
echo exit >> bidon


$gplot bidon

else
echo No plot produced

fi