#!/bin/bash

rm -f *.o
rm -f *.mod

libName=libArray$compiler.a
export libName

# Compilation of : ArrayReal4
# ============================
dataType='Real4' ; export dataType
arrayType='array'$dataType ; export arrayType 
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType
Kind='_REAL_' ; export Kind

./compileArraySecondStep

# Compilation of : ArrayReal8
# ============================
dataType='Real8' ; export dataType
arrayType='array'$dataType ; export arrayType 
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType
Kind='_REAL_' ; export Kind

./compileArraySecondStep

# Compilation of : ArrayInteger2
# ===============================
dataType='Integer2' ; export dataType
arrayType='array'$dataType ; export arrayType 
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileArraySecondStep

# Compilation of : ArrayInteger4
# ===============================
dataType='Integer4' ; export dataType
arrayType='array'$dataType ; export arrayType 
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileArraySecondStep

# Compilation of : ArrayInteger8
# ===============================
dataType='Integer8' ; export dataType
arrayType='array'$dataType ; export arrayType 
arrayDimension='_ARRAY_3D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileArraySecondStep

# Compilation of : array3DInterface
# ================================
$divaDir/compileFile array3DInterface.f95 array3DInterface

mv *.mod $divaModuleLib
