#!/bin/bash

isxmlgenerat=$1

WDIR=$(pwd)
DIVADIR="../../DIVA3D"

mkdir -p ${DIVADIR}/divastripped/output
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis
mkdir -p ./output/3Danalysis/MetaDataXMLs
#
./dvtxtmetainfo > ./output/3Danalysis/DriverMetainfo
#
##################################################
# loop on years defined in yearlist
# loop on variables defined in varlist

#########################################################
for var in `cat varlist`
#########################################################
do
echo variable $var
#########################################################
for year in `cat yearlist`
#########################################################
do
echo year $year
#########################################################

yearb=${year:0:4}
yeare=${year:4:4}
monthb=${month:0:2}
monthe=${month:2:2}

echo ' '
echo ' =================== Running divadoNCDF ======================== '
echo ' =================== working on variable: ' $var ' and year: '$year 
echo ' '

rm -f ${DIVADIR}/divastripped/3DWORK/*
rm -rf ${DIVADIR}/divastripped/output/3Danalysis/* 

if [ -f './output/3Danalysis/'$var'.Metainfo.txt' ]; then
cp -v './output/3Danalysis/'$var'.Metainfo.txt'  ${DIVADIR}/divastripped/output/3Danalysis/.
fi

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCliste' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCliste' ${DIVADIR}/divastripped/output/3Danalysis/.

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCinfo' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCinfo' ${DIVADIR}/divastripped/output/3Danalysis/.

cp -v ./output/3Danalysis/Fields/GridInfo.dat ${DIVADIR}/divastripped/output/3Danalysis/.

cd ./output/3Danalysis/
for ncfile in `ls $var.*.anl.nc` ;do
echo $ncfile
cp -v $ncfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.nbrdata'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.3Dparam'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done
cd ../../

cd ${DIVADIR}/divastripped

echo ' '
echo '==================== Running diva4Dncwrite ========================'

varl=$var'.'$year
vld=0
if [ "$isxmlgenerat" -lt "0" ];then
vld=1
fi

diva4Dncwrite $varl $vld

echo ' '
echo '========  Copying netcdf and metadata files to climatology output directory ======'
echo ' '

#echo now saving needs to be done
if [ -f "./output/3Danalysis/$var.$year.4Danl.nc" ];then
cp -v ./output/3Danalysis/$var.$year.4Danl.nc ${WDIR}/output/3Danalysis/.
fi
if [ -f "./output/3Danalysis/$var.4Danl.nc" ];then
cp -v ./output/3Danalysis/$var.4Danl.nc ${WDIR}/output/3Danalysis/.
fi
cp -v ./output/3Danalysis/$var'.4DNCMetainfo' ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/$var'.Metainfo.txt' ${WDIR}/output/3Danalysis/.

cd $WDIR

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCinfo'

fi

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCliste'

fi

cd $WDIR

echo '============================= divadoNCDF: end year loop    '$year

done

cat  ./output/3Danalysis/DriverMetainfo ./output/3Danalysis/$var'.Metainfo.txt' > ./output/3Danalysis/MetaDataXMLs/$var'.Textinfo.txt'

if [ "$isxmlgenerat" == "1" ]; then

echo 'generation of SDN xml metadata file'

divadoxml XMLtempl_sdn
fi

if [ "$isxmlgenerat" == "2" ]; then

echo 'generation of EDMONET xml metadata file'

divadoxml XMLtempl_emodn
fi

echo '============================= divadoNCDF: end var loop    '$var

done

echo =================================
echo Finished writing NC and Xml files 
echo =================================
