#!/bin/bash
####
# divado netcdf files for multi year periods climatologies #
###

FILENAME=driver
{
read isextractcomm
read isextractf
read iscontourcomm
read iscontour
read isdatacleancomm
read isdataclean
read minimumdatanumbercomm
read mindata
read isoptimisecomm
read isoptimise
read CLMINcomm
read CLMIN
read CLMAXcomm
read CLMAX
read SNMINcomm
read SNMIN
read SNMAXcomm
read SNMAX
read isanalysiscomm
read isanalysis
read lowerlevelcomm
read minlevel
read upperlevelcomm
read upperlevel
read isxmlgeneratcom
read isxmlgenerat
read isplotcomm
read isplot
} < $FILENAME

isxmlgenerat=$1

WDIR=$(pwd)
DIVADIR="../../DIVA3D"

mkdir -p ./output/3Danalysis/MetaDataXMLs
#
./dvtxtmetainfo > ./output/3Danalysis/DriverMetainfo
#

#########################################################
saveifs=$IFS
IFS=$'\n'
for var in `cat varlist`
#########################################################
do

echo ' '
echo ' =================== Running divadoNCYR ======================== '
echo ' =================== working on variable: ' "$var"
echo ' '

rm -rf ${DIVADIR}/divastripped/input/*
rm -rf ${DIVADIR}/divastripped/output/3Danalysis/*
rm -f ${DIVADIR}/divastripped/divawork/*
rm -f ${DIVADIR}/divastripped/3DWORK/*


mkdir -p ${DIVADIR}/divastripped/output
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis/Fields
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis/MetaDataXMLs

cp -v './yearlist' ${DIVADIR}/divastripped/input/.
cp -v './monthlist' ${DIVADIR}/divastripped/input/.

counter=0
#########################################################
for year in `cat yearlist`
#########################################################
do
echo year $year
let counter=$(($counter+1))
#########################################################

# Prepare run diva_4Dnc_write

cp -v $WDIR/output/3Danalysis/Fields/GridInfo.dat ${DIVADIR}/divastripped/output/3Danalysis/Fields/.

if [ -f './output/3Danalysis/'"$var"'.Metainfo.txt' ]; then
cp -v './output/3Danalysis/'"$var"'.Metainfo.txt'  ${DIVADIR}/divastripped/output/3Danalysis/.
fi

if [ -f './output/3Danalysis/'"$var"'.'$year'.3DNCliste' ]; then

cp -v './output/3Danalysis/'"$var"'.'$year'.3DNCliste' ${DIVADIR}/divastripped/output/3Danalysis/.
rm './output/3Danalysis/'"$var"'.'$year'.3DNCliste'

if [ -f './output/3Danalysis/'"$var"'.'$year'.3DNCinfo' ]; then

cp -v './output/3Danalysis/'"$var"'.'$year'.3DNCinfo' ${DIVADIR}/divastripped/output/3Danalysis/.
rm './output/3Danalysis/'"$var"'.'$year'.3DNCinfo'

cd ./output/3Danalysis/

cp -v ./Fields/GridInfo.dat ../../${DIVADIR}/divastripped/output/3Danalysis/.

for ncfile in `ls "$var".$year.*.anl.nc` ;do
cp -v $ncfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls "$var"'.'$year'.'*'.nbrdata'` ;do
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls "$var"'.'$year'.'*'.3Dparam'` ;do
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

#2013JMB - 2015 Sylvain Watelet

cd ../../
cd ${DIVADIR}/divastripped

if [[ -f "./output/metajmb" && "$counter" == "1" ]]
then
rm -f ./output/metajmb
fi
let lev=$((0+$minlevel))
let upperlevel=$((0+$upperlevel))
#echo SO SOS
while [ "$lev" -le "$upperlevel" ]
do
echo "working on level $lev"
let levn=$((10000+$lev))

# exloit the 3DNC info file to know which data have been used

#cat './output/3Danalysis/'"$var"'.'$year'.3DNCliste'

for ii in `cat './output/3Danalysis/'"$var"'.'$year'.3DNCliste' | awk -F "  " '{print $1}' | sed 's/^ *//' `

do
#echo $ii
jmm=$(echo $ii | awk -F . '{print $3}')
jmt=$(echo $ii | awk -F . '{print $1}')
jmy=$(echo $ii | awk -F . '{print $2}')

#echo So $jmm $jmt $jmy $levn

ls -l ${WDIR}/input/divadata/$jmt'.'$jmy'.'$jmm'.'$levn
depthval=$(head -$lev ${WDIR}/input/contour.depth | tail -1)
#echo Depth $depthval

cat ${WDIR}/input/divadata/$jmt'.'$jmy'.'$jmm'.'$levn | awk -v depth=$depthval '{print $1,$2,depth,$9,$10}' >> ./output/metajmb

done

let lev=$((1+$lev))
done
#2013JMB - 2015 Sylvain watelet


echo ======
#cat ./output/metajmb
echo ======

cd  $WDIR

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'"$var"'.'$year'.3DNCinfo'

fi
cd  $WDIR

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'"$var"'.'$year'.3DNCliste'

fi

cd $WDIR

done

cd ${DIVADIR}/divastripped

dv4DncYRwrt "$var"
../bin/netcdfobsid.a ./output/metajmb ./output/3Danalysis/"$var".4Danl.nc

echo now saving needs to be done
cp -v ./output/3Danalysis/"$var".4Danl.nc ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/"$var"'.4DNCMetainfo' ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/"$var"'.Metainfo.txt' ${WDIR}/output/3Danalysis/.

cd $WDIR
cat  ./output/3Danalysis/DriverMetainfo ./output/3Danalysis/"$var"'.Metainfo.txt' > ./output/3Danalysis/MetaDataXMLs/"$var"'.Textinfo.txt'

echo '============================= divadoNCDF: end var loop    '"$var"

done
IFS=$saveifs

echo ==================
echo second loop
echo ==================
