#!/bin/bash

if [ -f fort.68 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
set pm3d interpolate ii,ii map 
set style data pm3d
set logscale zcb
#set palette defined ( 0 "dark-blue", 1 "blue", 1.7 "green", 2.5 "yellow", 2.6 "yellow", 4 "red", 5 "dark-red" )
splot 'fort.68' using 1:2:3:3 t 'Analysis'
#end gnuplot commands
exit
EOF

$gplot bidon

else
echo No plot produced

fi