#!/bin/bash

if [ -f fort.71 -a -f fort.67 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
unset pm3d
set style line 10 linetype 1 lw 2 linecolor rgb "black"
set style line 9 linetype 1 lw 1 linecolor rgb "light-gray"

plot 'fort.71' using 1:2 with lines ls 9 t 'DIVA mesh', 'fort.67' using 1:2 with lines ls 10  notitle
#end gnuplot commands
exit
EOF

$gplot bidon

else
echo No plot produced

fi