#!/bin/bash

if [ -f fort.55 ] 
then

echo gnuplot is $gplot
awk '{print $0 >> "bidon"}' << EOF
#the gnuplot commands
plot 'fort.55' using 1:2:3:4 with vectors head filled lt 3  t 'Velocity field','fort.67' using 1:2:(0.0) with lines lt 10  notitle
#end gnuplot commands
exit
EOF

$gplot bidon

else
echo No plot produced

fi