#!/bin/bash

rm -f *.o
rm -f *.mod

thisDir=$PWD
associateDir=$associateDir' -I'$thisDir
export associateDir

arrayDimension=_ARRAY_2D_ ; export arrayDimension

# Compilation of : rowCSRMatrixReal4
# ==================================
dataType='Real4' ; export dataType
arrayType='rowcsrmatrix'$dataType ; export arrayType
vectorValue='vector'$dataType ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='REAL(KIND=4)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType

Kind='_REAL_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixReal8
# ==================================
dataType='Real8' ; export dataType
arrayType='rowcsrmatrix'$dataType ; export arrayType
vectorValue='vector'$dataType ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='REAL(KIND=8)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType

Kind='_REAL_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInteger2
# =====================================
dataType='Integer2' ; export dataType
arrayType='rowcsrmatrix'$dataType ; export arrayType
vectorValue='vector'$dataType ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='INTEGER(KIND=2)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType

Kind='_INTEGER_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInteger4
# =====================================
dataType='Integer4' ; export dataType
arrayType='rowcsrmatrix'$dataType ; export arrayType
vectorValue='vector'$dataType ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='INTEGER(KIND=4)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType
Kind='_INTEGER_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInteger8
# =====================================
dataType='Integer8' ; export dataType
arrayType='rowcsrmatrix'$dataType ; export arrayType
vectorValue='vector'$dataType ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='INTEGER(KIND=8)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType
Kind='_INTEGER_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInterface
# ================================
$divaDir/compileFile rowCSRMatrixInterface.f95 rowCSRMatrixInterface

mv *.mod $divaModuleLib
