#!/bin/bash

rm -f *.o
rm -f *.mod

thisDir=$PWD
associateDir=$associateDir' -I'$thisDir
export associateDir

arrayDimension=_ARRAY_2D_ ; export arrayDimension

# Compilation of : rowCSRMatrixReal4
# ==================================
arrayType='rowcsrmatrixReal4' ; export arrayType
vectorValue='vectorReal4' ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='REAL(KIND=4)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType

Kind='_REAL_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixReal8
# ==================================
arrayType='rowcsrmatrixReal8' ; export arrayType
vectorValue='vectorReal8' ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='REAL(KIND=8)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType

Kind='_REAL_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInteger2
# =====================================
arrayType='rowcsrmatrixInteger2' ; export arrayType
vectorValue='vectorInteger2' ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='INTEGER(KIND=2)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType

Kind='_INTEGER_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInteger4
# =====================================
arrayType='rowcsrmatrixInteger4' ; export arrayType
vectorValue='vectorInteger4' ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='INTEGER(KIND=4)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType
Kind='_INTEGER_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInteger8
# =====================================
arrayType='rowcsrmatrixInteger8' ; export arrayType
vectorValue='vectorInteger8' ; export vectorValue
vectorIndex='vectorInteger4' ; export vectorIndex
VARType='INTEGER(KIND=8)' ; export VARType
ROWIndexVARType='INTEGER(KIND=4)' ; export ROWIndexVARType
Kind='_INTEGER_' ; export Kind

./compileRowCSRMatrix

# Compilation of : rowCSRMatrixInterface
# ================================
$divaDir/compileFile rowCSRMatrixInterface.f95 rowCSRMatrixInterface

mv *.mod $divaModuleLib
