#!/bin/bash

moduleRowCSRMatrix='module'$arrayType ; export moduleRowCSRMatrix
moduleRowCSRMatrixDefinition='module'$arrayType'Definition' ; export moduleRowCSRMatrixDefinition
moduleVectorDefinitionValue='module'$vectorValue'Definition' ; export moduleVectorDefinitionValue
moduleVectorDefinitionIndex='module'$vectorIndex'Definition' ; export moduleVectorDefinitionIndex
vectorTypeValue=$vectorValue ; export vectorTypeValue
vectorTypeIndex=$vectorIndex ; export vectorTypeIndex
moduleValuesRowCSRMatrixManagement='moduleValuesManagement'$arrayType ; export moduleValuesRowCSRMatrixManagement

flag0='-DmoduleRowCSRMatrixDefinition='$moduleRowCSRMatrixDefinition
flag1='-DmoduleVectorDefinitionValue='$moduleVectorDefinitionValue
flag2='-DmoduleVectorDefinitionIndex='$moduleVectorDefinitionIndex
flag3='-DrowCSRMatrixType='$arrayType
flag4='-DvectorTypeValue='$vectorTypeValue
flag5='-DvectorTypeIndex='$vectorTypeIndex
flag6='-D'$Kind
flag7='-DROWIndexVARType='$ROWIndexVARType
flag8='-DmoduleValuesRowCSRMatrixManagement='$moduleValuesRowCSRMatrixManagement
flag9='-DmoduleRowCSRMatrix='$moduleRowCSRMatrix

preproFlag=$preproFlag' '$flag0
preproFlag=$preproFlag' '$flag1
preproFlag=$preproFlag' '$flag2
preproFlag=$preproFlag' '$flag3
preproFlag=$preproFlag' '$flag4
preproFlag=$preproFlag' '$flag5
preproFlag=$preproFlag' '$flag6
preproFlag=$preproFlag' '$flag7
preproFlag=$preproFlag' '$flag8
preproFlag=$preproFlag' '$flag9

export preproFlag
