#!/bin/bash

# Name of the fortran compiler (ex: ifort,gfortran,pgi,...)
compiler=ifort

# Compilation flags
flags='-O3'
flags='-O0' # no optimization

# Netcdf library
nclib=/usr/local/lib/netcdf3ifort/libnetcdf.a

# Use of Plplot (creation of scientific plots)
Plplot=Plplot
Plplot=NoPlplot

# gui = 1 for Graphical User Interface programs to be compiled
gui=1

# netcdf = 1 for NetCDF programs to be compiled
netcdf=1
