#!/bin/bash

echo ====================================
echo ====================================
echo ==                                ==
echo ==   Compilation of DIVA Modules  ==
echo ==                                ==
echo ====================================
echo ====================================
echo ' '

baseDir=$PWD

rm -f $divaModuleLib/*

# Compilation of IO module
# ========================

cd $baseDir/IOModule
./divaCompileIOModule

# Compilation of Mathematic module
# =================================

cd $baseDir/Mathematic
./divaCompileModuleMathematic


# Compilation of General module
# =============================

cd $baseDir/General
./divaCompileModuleGeneral

cd $baseDir

