#!/bin/bash

echo ====================================
echo ====================================
echo ==                                ==
echo ==   Compilation of DIVA Modules  ==
echo ==                                ==
echo ====================================
echo ====================================
echo ' '

baseDir=$PWD
divaModuleLib=$baseDir/lib

export divaModuleLib

rm $divaModuleLib/*

# Compilation of Mathematic module
# =================================

cd $baseDir/Mathematic
source ./divaCompileModuleMathematicG95


# Compilation of IO module
# ========================

cd $baseDir/IOModule
source ./divaCompileIOModuleG95

# Compilation of General module
# =============================

cd $baseDir/General
source ./divaCompileModuleGeneralG95

cd $baseDir

