#!/bin/bash

echo ====================================
echo ====================================
echo ==                                ==
echo ==   Compilation of DIVA Modules  ==
echo ==                                ==
echo ====================================
echo ====================================
echo ' '

baseDir=$PWD

_WITH_COMMON_=1 ; export _WITH_COMMON_
_WITH_IO_=1 ; export _WITH_IO_
_WITH_MATH_=1 ; export _WITH_MATH_
_WITH_DIVA_=1 ; export _WITH_DIVA_ 
_WITH_MESH_=1 ; export _WITH_MESH_


rm -f $divaModuleLib/*.o

# Compilation of Common module
# =============================

if [ $_WITH_COMMON_ == 1 ]
then
cd $baseDir/CommonModule
./divaCompileCommonModule
fi

# Compilation of IO module
# ========================

if [ $_WITH_IO_ == 1 ]
then
cd $baseDir/IOModule
./divaCompileIOModule
fi

# Compilation of Mathematic module
# =================================

if [ $_WITH_MATH_ == 1 ]
then
cd $baseDir/Mathematic
./divaCompileModuleMathematic
fi

# Compilation of Mesh module
# ==========================

if [ $_WITH_MESH_ == 1 ]
then
cd $baseDir/Mesh
./divaCompileModuleMesh
fi

# Compilation of General module
# =============================

if [ $_WITH_DIVA_ == 1 ]
then
cd $baseDir/General
./divaCompileModuleGeneral
fi

cd $baseDir

