#!/bin/bash

rm -f *.o
rm -f *.mod

libName=libMatrix$compiler.a
export libName

# Compilation of : MatrixReal4
# ============================
arrayType='matrixReal4' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType
Kind='_REAL_' ; export Kind

./compileMatrixSecondStep

# Compilation of : MatrixReal8
# ============================
arrayType='matrixReal8' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType
Kind='_REAL_' ; export Kind

./compileMatrixSecondStep

# Compilation of : MatrixInteger2
# ===============================
arrayType='matrixInteger2' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileMatrixSecondStep

# Compilation of : MatrixInteger4
# ===============================
arrayType='matrixInteger4' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileMatrixSecondStep

# Compilation of : MatrixInteger8
# ===============================
arrayType='matrixInteger8' ; export arrayType
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileMatrixSecondStep

# Compilation of : matrixInterface
# ================================
$divaDir/compileFile matrixInterface.f95 matrixInterface

mv *.mod $divaModuleLib
