#!/bin/bash


preproFlag='-DtemplatearrayType=array2DReal8Definition -DarrayType=array2DReal8 -DVARType=REAL(KIND=8) '
preproFlag=$preproFlag' -D=_ARRAY_2D_'
export preproFlag
moduleName=array2DReal8Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DReal4Definition -DarrayType=array2DReal4 -DVARType=REAL(KIND=4) '
preproFlag=$preproFlag' -D=_ARRAY_2D_'
export preproFlag
moduleName=array2DReal4Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DInteger2Definition -DarrayType=array2DInteger2 -DVARType=INTEGER(KIND=2) '
preproFlag=$preproFlag' -D=_ARRAY_2D_'
export preproFlag
moduleName=array2DInteger2Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DInteger4Definition -DarrayType=array2DInteger4 -DVARType=INTEGER(KIND=4) '
preproFlag=$preproFlag' -D=_ARRAY_2D_'
export preproFlag
moduleName=array2DInteger4Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DInteger8Definition -DarrayType=array2DInteger8 -DVARType=INTEGER(KIND=8) '
preproFlag=$preproFlag' -D=_ARRAY_2D_'
export preproFlag
moduleName=array2DInteger8Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

preproFlag='-DtemplatearrayType=array2DReal8Definition -DtemplateBasicArray=basicArray2DReal8 -Dtemplate=moduleArray2DReal8 '
preproFlag=$preproFlag' -DarrayType=array2DReal8 -DVARType=REAL(KIND=8) '
export preproFlag
moduleName=basicArray2DReal8

source $divaDir/compileFileG95 templateBasicArray2D.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DReal4Definition -DtemplateBasicArray=basicArray2DReal4 -Dtemplate=moduleArray2DReal4 '
preproFlag=$preproFlag' -DarrayType=array2DReal4 -DVARType=REAL(KIND=4) '
export preproFlag
moduleName=basicArray2DReal4

source $divaDir/compileFileG95 templateBasicArray2D.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DInteger2Definition -DtemplateBasicArray=basicArray2DInteger2 -Dtemplate=moduleArray2DInteger2 '
preproFlag=$preproFlag' -DarrayType=array2DInteger2 -DVARType=INTEGER(KIND=2) '
export preproFlag
moduleName=basicArray2DInteger2

source $divaDir/compileFileG95 templateBasicArray2D.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DInteger4Definition -DtemplateBasicArray=basicArray2DInteger4 -Dtemplate=moduleArray2DInteger4 '
preproFlag=$preproFlag' -DarrayType=array2DInteger4 -DVARType=INTEGER(KIND=4) '
export preproFlag
moduleName=basicArray2DInteger4

source $divaDir/compileFileG95 templateBasicArray2D.f95 $moduleName

preproFlag='-DtemplatearrayType=array2DInteger8Definition -DtemplateBasicArray=basicArray2DInteger8 -Dtemplate=moduleArray2DInteger8 '
preproFlag=$preproFlag' -DarrayType=array2DInteger8 -DVARType=INTEGER(KIND=8) '
export preproFlag
moduleName=basicArray2DInteger8

source $divaDir/compileFileG95 templateBasicArray2D.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

preproFlag='-DtemplateBasicArray=basicArray2DReal8 -Dtemplate=moduleArray2DReal8 -DarrayType=array2DReal8 -DVARType=REAL(KIND=8) '
preproFlag=$preproFlag' -DtemplatearrayType=array2DReal8Definition'
export preproFlag
moduleName=moduleArray2DReal8

source $divaDir/compileFileG95 templateArray2D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray2DReal4 -Dtemplate=moduleArray2DReal4 -DarrayType=array2DReal4 -DVARType=REAL(KIND=4) '
preproFlag=$preproFlag' -DtemplatearrayType=array2DReal4Definition'
export preproFlag
moduleName=moduleArray2DReal4

source $divaDir/compileFileG95 templateArray2D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray2DInteger2 -Dtemplate=moduleArray2DInteger2 -DarrayType=array2DInteger2 -DVARType=INTEGER(KIND=2) '
preproFlag=$preproFlag' -DtemplatearrayType=array2DInteger2Definition'
export preproFlag
moduleName=moduleArray2DInteger2

source $divaDir/compileFileG95 templateIntegerArray2D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray2DInteger4 -Dtemplate=moduleArray2DInteger4 -DarrayType=array2DInteger4 -DVARType=INTEGER(KIND=4) '
preproFlag=$preproFlag' -DtemplatearrayType=array2DInteger4Definition'
export preproFlag
moduleName=moduleArray2DInteger4

source $divaDir/compileFileG95 templateIntegerArray2D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray2DInteger8 -Dtemplate=moduleArray2DInteger8 -DarrayType=array2DInteger8 -DVARType=INTEGER(KIND=8) '
preproFlag=$preproFlag' -DtemplatearrayType=array2DInteger8Definition'
export preproFlag
moduleName=moduleArray2DInteger8

source $divaDir/compileFileG95 templateIntegerArray2D.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib


preproFlag='-DtemplatearrayType=array3DReal8Definition -DarrayType=array3DReal8 -DVARType=REAL(KIND=8) '
preproFlag=$preproFlag' -D=_ARRAY_3D_'
export preproFlag
moduleName=array3DReal8Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DReal4Definition -DarrayType=array3DReal4 -DVARType=REAL(KIND=4) '
preproFlag=$preproFlag' -D=_ARRAY_3D_'
export preproFlag
moduleName=array3DReal4Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DInteger2Definition -DarrayType=array3DInteger2 -DVARType=INTEGER(KIND=2) '
preproFlag=$preproFlag' -D=_ARRAY_3D_'
export preproFlag
moduleName=array3DInteger2Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DInteger4Definition -DarrayType=array3DInteger4 -DVARType=INTEGER(KIND=4) '
preproFlag=$preproFlag' -D=_ARRAY_3D_'
export preproFlag
moduleName=array3DInteger4Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DInteger8Definition -DarrayType=array3DInteger8 -DVARType=INTEGER(KIND=8) '
preproFlag=$preproFlag' -D=_ARRAY_3D_'
export preproFlag
moduleName=array3DInteger8Definition

source $divaDir/compileFileG95 moduleArray.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

preproFlag='-DtemplatearrayType=array3DReal8Definition -DtemplateBasicArray=basicArray3DReal8 -Dtemplate=moduleArray3DReal8 '
preproFlag=$preproFlag' -DarrayType=array3DReal8 -DVARType=REAL(KIND=8) '
export preproFlag
moduleName=basicArray3DReal8

source $divaDir/compileFileG95 templateBasicArray3D.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DReal4Definition -DtemplateBasicArray=basicArray3DReal4 -Dtemplate=moduleArray3DReal4 '
preproFlag=$preproFlag' -DarrayType=array3DReal4 -DVARType=REAL(KIND=4) '
export preproFlag
moduleName=basicArray3DReal4

source $divaDir/compileFileG95 templateBasicArray3D.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DInteger2Definition -DtemplateBasicArray=basicArray3DInteger2 -Dtemplate=moduleArray3DInteger2 '
preproFlag=$preproFlag' -DarrayType=array3DInteger2 -DVARType=INTEGER(KIND=2) '
export preproFlag
moduleName=basicArray3DInteger2

source $divaDir/compileFileG95 templateBasicArray3D.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DInteger4Definition -DtemplateBasicArray=basicArray3DInteger4 -Dtemplate=moduleArray3DInteger4 '
preproFlag=$preproFlag' -DarrayType=array3DInteger4 -DVARType=INTEGER(KIND=4) '
export preproFlag
moduleName=basicArray3DInteger4

source $divaDir/compileFileG95 templateBasicArray3D.f95 $moduleName

preproFlag='-DtemplatearrayType=array3DInteger8Definition -DtemplateBasicArray=basicArray3DInteger8 -Dtemplate=moduleArray3DInteger8 '
preproFlag=$preproFlag' -DarrayType=array3DInteger8 -DVARType=INTEGER(KIND=8) '
export preproFlag
moduleName=basicArray3DInteger8

source $divaDir/compileFileG95 templateBasicArray3D.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

preproFlag='-DtemplateBasicArray=basicArray3DReal8 -Dtemplate=moduleArray3DReal8 -DarrayType=array3DReal8 -DVARType=REAL(KIND=8) '
preproFlag=$preproFlag' -DtemplatearrayType=array3DReal8Definition'
export preproFlag
moduleName=moduleArray3DReal8

source $divaDir/compileFileG95 templateArray3D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray3DReal4 -Dtemplate=moduleArray3DReal4 -DarrayType=array3DReal4 -DVARType=REAL(KIND=4) '
preproFlag=$preproFlag' -DtemplatearrayType=array3DReal4Definition'
export preproFlag
moduleName=moduleArray3DReal4

source $divaDir/compileFileG95 templateArray3D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray3DInteger2 -Dtemplate=moduleArray3DInteger2 -DarrayType=array3DInteger2 -DVARType=INTEGER(KIND=2) '
preproFlag=$preproFlag' -DtemplatearrayType=array3DInteger2Definition'
export preproFlag
moduleName=moduleArray3DInteger2

source $divaDir/compileFileG95 templateIntegerArray3D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray3DInteger4 -Dtemplate=moduleArray3DInteger4 -DarrayType=array3DInteger4 -DVARType=INTEGER(KIND=4) '
preproFlag=$preproFlag' -DtemplatearrayType=array3DInteger4Definition'
export preproFlag
moduleName=moduleArray3DInteger4

source $divaDir/compileFileG95 templateIntegerArray3D.f95 $moduleName

preproFlag='-DtemplateBasicArray=basicArray3DInteger8 -Dtemplate=moduleArray3DInteger8 -DarrayType=array3DInteger8 -DVARType=INTEGER(KIND=8) '
preproFlag=$preproFlag' -DtemplatearrayType=array3DInteger8Definition'
export preproFlag
moduleName=moduleArray3DInteger8

source $divaDir/compileFileG95 templateIntegerArray3D.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

moduleName=matrixInterface
source $divaDir/compileFileG95 $moduleName.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

