#!/bin/bash

rm -f *.o
rm -f *.mod

libName=libMatrix$compiler.a
export libName

rm -f $divaModuleLib/$libName

# Compilation of : MatrixReal4
# ============================
dataType='Real4' ; export dataType
arrayType='matrix'$dataType ; export arrayType 
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=4)' ; export VARType
Kind='_REAL_' ; export Kind

./compileMatrixFirstStep

# Compilation of : MatrixReal8
# ============================
dataType='Real8' ; export dataType
arrayType='matrix'$dataType ; export arrayType 
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='REAL(KIND=8)' ; export VARType
Kind='_REAL_' ; export Kind

./compileMatrixFirstStep

# Compilation of : MatrixInteger2
# ===============================
dataType='Integer2' ; export dataType
arrayType='matrix'$dataType ; export arrayType 
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=2)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileMatrixFirstStep

# Compilation of : MatrixInteger4
# ===============================
dataType='Integer4' ; export dataType
arrayType='matrix'$dataType ; export arrayType 
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=4)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileMatrixFirstStep

# Compilation of : MatrixInteger8
# ===============================
dataType='Integer8' ; export dataType
arrayType='matrix'$dataType ; export arrayType 
arrayDimension='_ARRAY_2D_' ; export arrayDimension
VARType='INTEGER(KIND=8)' ; export VARType
Kind='_INTEGER_' ; export Kind

./compileMatrixFirstStep


mv *.mod $divaModuleLib
