#!/bin/bash

echo ===============================================
echo ===============================================
echo ==                                           ==
echo ==   Compilation of DIVA Mathematic Modules  ==
echo ==                                           ==
echo ===============================================
echo ===============================================
echo ' '

baseDir=$PWD

echo ============================
echo ============================
echo = Compiling General Module =
echo ============================
echo ============================
echo ' '

preproFlag=''
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir

for ii in `ls *.f95`
do
source $divaDir/compileFileG95 $ii `basename $ii .f95`
done

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

echo ===========================
echo ===========================
echo = Compiling Vector Module =
echo ===========================
echo ===========================
echo ' '

cd $baseDir/Vector
source ./divaCompileModuleVectorG95

echo ===========================
echo ===========================
echo = Compiling Matrix Module =
echo ===========================
echo ===========================
echo ' '

cd $baseDir/Matrix
source ./divaCompileModuleArrayG95

cd $baseDir

