#!/bin/bash

echo ===============================================
echo ===============================================
echo ==                                           ==
echo ==   Compilation of DIVA Mathematic Modules  ==
echo ==                                           ==
echo ===============================================
echo ===============================================
echo ' '

baseDir=$PWD

echo ========================
echo ========================
echo = Compiling First step =
echo ========================
echo ========================
echo ' '

./divaCompileModuleMathematicFirstStep

echo =========================
echo =========================
echo = Compiling Second step =
echo =========================
echo =========================
echo ' '

./divaCompileModuleMathematicSecondStep


