#!/bin/bash

echo ===============================================
echo ===============================================
echo ==                                           ==
echo ==   Compilation of DIVA Mathematic Modules  ==
echo ==                                           ==
echo ===============================================
echo ===============================================
echo ' '

baseDir=$PWD

echo ============================
echo ============================
echo = Compiling General Module =
echo ============================
echo ============================
echo ' '

preproFlag=''
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir

for ii in `ls *.f95`
do
$divaDir/compileFile $ii `basename $ii .f95`
done

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

echo ===========================
echo ===========================
echo = Compiling Vector Module =
echo ===========================
echo ===========================
echo ' '

cd $baseDir/Vector

preproFlag='-DtemplatevectorType=vectorReal8Definition -DvectorType=vectorReal8 -DVARType=REAL*8 '
associateDir=''
export preproFlag
export associateDir
moduleName=vectorReal8Definition

$divaDir/compileFile moduleVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorReal4Definition -DvectorType=vectorReal4 -DVARType=REAL*4 '
associateDir=''
export preproFlag
export associateDir
moduleName=vectorReal4Definition

$divaDir/compileFile moduleVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorInteger2Definition -DvectorType=vectorInteger2 -DVARType=INTEGER*2 '
associateDir=''
export preproFlag
export associateDir
moduleName=vectorInteger2Definition

$divaDir/compileFile moduleVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorInteger4Definition -DvectorType=vectorInteger4 -DVARType=INTEGER*4 '
associateDir=''
export preproFlag
export associateDir
moduleName=vectorInteger4Definition

$divaDir/compileFile moduleVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorInteger8Definition -DvectorType=vectorInteger8 -DVARType=INTEGER*8 '
associateDir=''
export preproFlag
export associateDir
moduleName=vectorInteger8Definition

$divaDir/compileFile moduleVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorReal8Definition -Dtemplate=moduleVectorReal8 -DvectorType=vectorReal8 -DVARType=REAL*8 '
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir
moduleName=moduleVectorReal8

$divaDir/compileFile templateVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorReal4Definition -Dtemplate=moduleVectorReal4 -DvectorType=vectorReal4 -DVARType=REAL*4 '
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir
moduleName=moduleVectorReal4

$divaDir/compileFile templateVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorInteger2Definition -Dtemplate=moduleVectorInteger2 -DvectorType=vectorInteger2 -DVARType=INTEGER*2 '
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir
moduleName=moduleVectorInteger2

$divaDir/compileFile templateIntegerVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorInteger4Definition -Dtemplate=moduleVectorInteger4 -DvectorType=vectorInteger4 -DVARType=INTEGER*4 '
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir
moduleName=moduleVectorInteger4

$divaDir/compileFile templateIntegerVector.f95 $moduleName

preproFlag='-DtemplatevectorType=vectorInteger8Definition -Dtemplate=moduleVectorInteger8 -DvectorType=vectorInteger8 -DVARType=INTEGER*8 '
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir
moduleName=moduleVectorInteger8

$divaDir/compileFile templateIntegerVector.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

preproFlag=''
associateDir=''
export preproFlag
export associateDir
moduleName=vectorInterface

$divaDir/compileFile $moduleName.f95 $moduleName

mv *.mod $divaModuleLib
mv *.o $divaModuleLib

cd $baseDir

