#!/bin/bash

echo ===============================================
echo ===============================================
echo ==                                           ==
echo ==   Compilation of DIVA Mathematic Modules  ==
echo ==                                           ==
echo ===============================================
echo ===============================================
echo ' '

baseDir=$PWD

preproFlag=''
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir

echo ============================
echo ============================
echo = Compiling Generic Module =
echo ============================
echo ============================
echo ' '

cd $baseDir/Generic
./divaCompileModuleGenericFirstStep

echo ===========================
echo ===========================
echo = Compiling Vector Module =
echo ===========================
echo ===========================
echo ' '

cd $baseDir/Vector
./divaCompileModuleVectorFirstStep

echo ===========================
echo ===========================
echo = Compiling Matrix Module =
echo ===========================
echo ===========================
echo ' '

cd $baseDir/Matrix
./divaCompileModuleMatrixFirstStep

echo ==========================
echo ==========================
echo = Compiling Array Module =
echo ==========================
echo ==========================
echo ' '

cd $baseDir/Array
./divaCompileModuleArrayFirstStep

cd $baseDir

