#!/bin/bash

echo ===============================================
echo ===============================================
echo ==                                           ==
echo ==   Compilation of DIVA Mathematic Modules  ==
echo ==                                           ==
echo ===============================================
echo ===============================================
echo ' '

baseDir=$PWD

preproFlag=''
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir

echo ============================
echo ============================
echo = Compiling Generic Module =
echo ============================
echo ============================
echo ' '

cd $baseDir/Generic
./divaCompileModuleGenericSecondStep

echo ===========================
echo ===========================
echo = Compiling Vector Module =
echo ===========================
echo ===========================
echo ' '

cd $baseDir/Vector
./divaCompileModuleVectorSecondStep

echo ===========================
echo ===========================
echo = Compiling Matrix Module =
echo ===========================
echo ===========================
echo ' '

cd $baseDir/Matrix
./divaCompileModuleMatrixSecondStep

echo ==========================
echo ==========================
echo = Compiling Array Module =
echo ==========================
echo ==========================
echo ' '

cd $baseDir/Array
./divaCompileModuleArraySecondStep


echo =================================
echo =================================
echo = Compiling SparseMatrix Module =
echo =================================
echo =================================
echo ' '

cd $baseDir/SparseMatrix
./divaCompileModuleSparseMatrix

cd $baseDir

