#!/bin/bash

isxmlgenerat=$1

WDIR=$(pwd)
DIVADIR="../../DIVA3D"

mkdir -p ${DIVADIR}/divastripped 

mkdir -p ./output/3Danalysis/MetaDataXMLs

./dvtxtmetainfo > ./output/3Danalysis/DriverMetainfo

#
##################################################
# loop on years defined in yearlist
# loop on variables defined in varlist

#########################################################
for var in `cat varlist`
#########################################################
do
echo variable $var
#########################################################
for year in `cat yearlist`
#########################################################
do
echo year $year
#########################################################

yearb=${year:0:4}
yeare=${year:4:4}
monthb=${month:0:2}
monthe=${month:2:2}

echo working on variable $var 

# Prepare run diva4Dncwrite

rm -f ${DIVADIR}/divastripped/3DWORK/*
rm -rf ${DIVADIR}/divastripped/output/3Danalysis/* 

if [ -f './output/3Danalysis/'$var'.Metainfo.txt' ]; then
cp -v './output/3Danalysis/'$var'.Metainfo.txt'  ${DIVADIR}/divastripped/output/3Danalysis/.
fi

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCliste' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCliste' ${DIVADIR}/divastripped/output/3Danalysis/.

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCinfo' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCinfo' ${DIVADIR}/divastripped/output/3Danalysis/.

cd ./output/3Danalysis/
for ncfile in `ls $var.*.anl.nc` ;do
echo $ncfile
cp -v $ncfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.nbrdata'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.3Dparam'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

cd ../../
cd ${DIVADIR}/divastripped

diva4Dncwrite

echo now saving needs to be done
cp -v ./output/3Danalysis/$var.$year.4Danl.nc ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/$var.4Danl.nc ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/$var'.4DNCMetainfo' ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/$var'.Metainfo.txt' ${WDIR}/output/3Danalysis/.

cd $WDIR

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCinfo'

fi

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCliste'

fi

cd $WDIR

done

cat  ./output/3Danalysis/DriverMetainfo ./output/3Danalysis/$var'.Metainfo.txt' > ./output/3Danalysis/MetaDataXMLs/$var'.Textinfo.txt'

if [ "$isxmlgenerat" == "1" ]; then

echo 'generation of SDN xml metadata file'

divadoxml XMLtempl_sdn
fi

if [ "$isxmlgenerat" == "2" ]; then

echo 'generation of EMODNET xml metadata file'

divadoxml XMLtempl_emodn
fi
done

echo '  '
echo '============ Finished producing 4D  netcdf and XML files =============='
echo '======================================================================='
echo ' '
