#!/bin/bash



echo =================================
echo =================================
echo ==                             ==
echo == Procedure to test : matrix  ==
echo ==                             ==
echo =================================
echo =================================
echo ' '

# Chech program : testMatrix
# --------------------------

fileToCheck=testMatrix
typeToCheck=Real8
VARType='REAL(KIND=8)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DmatrixType=matrix'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testMatrix
typeToCheck=Real4
VARType='REAL(KIND=4)'

echo Test : $fileToCheck.$typeToCheck
echo ------

echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DmatrixType=matrix'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

# Chech program : testIntegerMatrix
# ---------------------------------

fileToCheck=testIntegerMatrix
typeToCheck=Integer2
VARType='INTEGER(KIND=2)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DmatrixType=matrix'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testIntegerMatrix
typeToCheck=Integer4
VARType='INTEGER(KIND=4)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DmatrixType=matrix'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testIntegerMatrix
typeToCheck=Integer8
VARType='INTEGER(KIND=8)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DmatrixType=matrix'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log
