#!/bin/bash

baseDir=$PWD

echo Testing procedure in progress...
echo ================================
rm -f ./testing.log
rm -f *.$OSused


# Testing vector
# ==============

#./testDivaVector


# Testing matrix
# ==============

#./testDivaMatrix

# Testing array
# ==============

#./testDivaArray

# Testinf IO
# ==========
./testDivaIO

cd $baseDir

