#!/bin/bash

baseDir=$PWD

echo Testing procedure in progress...
echo ================================
rm -f ./testing.log
rm -f *.$OSused

_WITH_IO_=1 ; export _WITH_IO_
_WITH_VECTOR_=0 ; export _WITH_MATH_
_WITH_MATRIX_=0 ; export _WITH_DIVA_ 
_WITH_ARRAY_=0 ; export _WITH_DIVA_ 


# Testing vector
# ==============

if [ $_WITH_VECTOR_ == 1 ]
then
./testDivaVector
fi

# Testing matrix
# ==============

if [ $_WITH_MATRIX_ == 1 ]
then
./testDivaMatrix
fi

# Testing array
# ==============

if [ $_WITH_ARRAY_ == 1 ]
then
./testDivaArray
fi

# Testinf IO
# ==========
if [ $_WITH_IO_ == 1 ]
then
./testDivaIO
fi

cd $baseDir

