#!/bin/bash



echo =================================
echo =================================
echo ==                             ==
echo == Procedure to test : array  ==
echo ==                             ==
echo =================================
echo =================================
echo ' '

cp ./Mathematic/testArray3D.f95 .
cp ./Mathematic/testIntegerArray3D.f95 .

# Chech program : testArray
# --------------------------

fileToCheck=testArray3D
typeToCheck=Real8
VARType='REAL(KIND=8)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DarrayType=array'$typeToCheck' -DVARType='$VARType
preproFlag=$preproFlag' -D'$typeToCheck
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused

#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck'WriteTHK'.$typeToCheck.out
rm ./$fileToCheck'Write'.$typeToCheck.out
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testArray3D
typeToCheck=Real4
VARType='REAL(KIND=4)'

echo Test : $fileToCheck.$typeToCheck
echo ------

echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DarrayType=array'$typeToCheck' -DVARType='$VARType
preproFlag=$preproFlag' -D'$typeToCheck
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck'WriteTHK'.$typeToCheck.out
rm ./$fileToCheck'Write'.$typeToCheck.out
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

# Chech program : testIntegerArray
# ---------------------------------

fileToCheck=testIntegerArray3D
typeToCheck=Integer2
VARType='INTEGER(KIND=2)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DarrayType=array'$typeToCheck' -DVARType='$VARType
preproFlag=$preproFlag' -D'$typeToCheck
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck'WriteTHK'.$typeToCheck.out
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testIntegerArray3D
typeToCheck=Integer4
VARType='INTEGER(KIND=4)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DarrayType=array'$typeToCheck' -DVARType='$VARType
preproFlag=$preproFlag' -D'$typeToCheck
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck'WriteTHK'.$typeToCheck.out
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testIntegerArray3D
typeToCheck=Integer8
VARType='INTEGER(KIND=8)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DarrayType=array'$typeToCheck' -DVARType='$VARType
preproFlag=$preproFlag' -D'$typeToCheck
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'WriteTHK'.$typeToCheck.out ./OUTPUTS/$fileToCheck'WriteTHK'.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck'WriteTHK'.$typeToCheck.out
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

rm -r testArray3D.f95
rm -r testIntegerArray3D.f95
