#!/bin/bash



echo =================================
echo =================================
echo ==                             ==
echo == Procedure to test : vector  ==
echo ==                             ==
echo =================================
echo =================================
echo ' '

# Chech program : testVector
# --------------------------

fileToCheck=testVector
typeToCheck=Real8
VARType='REAL(KIND=8)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vector'$typeToCheck' -DVARType='$VARType
preproFlag=$preproFlag' -D'$typeToCheck
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck'Write'.$typeToCheck.out
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testVector
typeToCheck=Real4
VARType='REAL(KIND=4)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vector'$typeToCheck' -DVARType='$VARType
preproFlag=$preproFlag' -D'$typeToCheck
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
diff -s ./$fileToCheck'Write'.$typeToCheck.out ./OUTPUTS/$fileToCheck'Write'.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck'Write'.$typeToCheck.out
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

# Chech program : testIntegerVector
# ---------------------------------

fileToCheck=testIntegerVector
typeToCheck=Integer2
VARType='INTEGER(KIND=2)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vector'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testIntegerVector
typeToCheck=Integer4
VARType='INTEGER(KIND=4)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vector'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log

fileToCheck=testIntegerVector
typeToCheck=Integer8
VARType='INTEGER(KIND=8)'

echo Test : $fileToCheck.$typeToCheck
echo ------
echo Test : $fileToCheck.$typeToCheck >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vector'$typeToCheck' -DVARType='$VARType
export preproFlag

$divaDir/compileAndLinkFile $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.$typeToCheck.$compiler.$OSused
#cp ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused
diff -s ./$fileToCheck.$typeToCheck.$compiler.$OSused ./OUTPUTS/$fileToCheck.$typeToCheck.$compiler.$OSused >> testing.log
rm ./$fileToCheck.$typeToCheck.$compiler.$OSused
rm ./$fileToCheck.a

echo ' ' >> testing.log
