#!/bin/bash



echo =============================================
echo =============================================
echo ==                                         ==
echo == Procedure to test programs in : MODULE  ==
echo ==                                         ==
echo =============================================
echo =============================================
echo ' '

divaDir=../../
divaModuleLib=../lib
export divaModuleLib

echo Testing procedure in progress...
echo ================================
rm ./testing.log

extension=.f95
osUsed=cygwin

# Chech program : testVector
# --------------------------
fileToCheck=testVector
echo Test : $fileToCheck.Real8
echo ------
echo Test : $fileToCheck.Real8 >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vectorReal8 -DVARType=REAL(KIND=8) '
export preproFlag

$divaDir/compileLinkFile $fileToCheck$extension $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.cygwin
diff -s ./$fileToCheck.cygwin ./OUTPUTS/$fileToCheck.Real8.cygwin >> testing.log
rm ./$fileToCheck.cygwin
rm ./$fileToCheck.a
echo ' ' >> testing.log

fileToCheck=testVector
echo Test : $fileToCheck.Real4
echo ------
echo Test : $fileToCheck.Real4 >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vectorReal4 -DVARType=REAL(KIND=4) '
export preproFlag

$divaDir/compileLinkFile $fileToCheck$extension $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.cygwin
diff -s ./$fileToCheck.cygwin ./OUTPUTS/$fileToCheck.Real4.cygwin >> testing.log
rm ./$fileToCheck.cygwin
rm ./$fileToCheck.a
echo ' ' >> testing.log

fileToCheck=testIntegerVector
echo Test : $fileToCheck.Integer2
echo ------
echo Test : $fileToCheck.Integer2 >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vectorInteger2 -DVARType=INTEGER(KIND=2) '
export preproFlag

$divaDir/compileLinkFile $fileToCheck$extension $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.cygwin
diff -s ./$fileToCheck.cygwin ./OUTPUTS/$fileToCheck.Integer2.cygwin >> testing.log
rm ./$fileToCheck.cygwin
rm ./$fileToCheck.a
echo ' ' >> testing.log

fileToCheck=testIntegerVector
echo Test : $fileToCheck.Integer4
echo ------
echo Test : $fileToCheck.Integer4 >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vectorInteger4 -DVARType=INTEGER(KIND=4) '
export preproFlag

$divaDir/compileLinkFile $fileToCheck$extension $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.cygwin
diff -s ./$fileToCheck.cygwin ./OUTPUTS/$fileToCheck.Integer4.cygwin >> testing.log
rm ./$fileToCheck.cygwin
rm ./$fileToCheck.a
echo ' ' >> testing.log

fileToCheck=testIntegerVector
echo Test : $fileToCheck.Integer8
echo ------
echo Test : $fileToCheck.Integer8 >> testing.log
echo ------ >> testing.log

preproFlag='-DvectorType=vectorInteger8 -DVARType=INTEGER(KIND=8) '
export preproFlag

$divaDir/compileLinkFile $fileToCheck$extension $fileToCheck >> testing.log
./$fileToCheck.a >> $fileToCheck.cygwin
diff -s ./$fileToCheck.cygwin ./OUTPUTS/$fileToCheck.Integer8.cygwin >> testing.log
rm ./$fileToCheck.cygwin
rm ./$fileToCheck.a
echo ' ' >> testing.log

# Chech program : testReadWrite
# -----------------------------
fileToCheck=testReadWrite
echo Test : $fileToCheck
echo ------
echo Test : $fileToCheck >> testing.log
echo ------ >> testing.log

$divaDir/compileLinkFile $fileToCheck$extension $fileToCheck >> testing.log
./$fileToCheck.a
diff -s ./fort.412 ./OUTPUTS/fort.412.$fileToCheck.cygwin >> testing.log
diff -s ./fort.413 ./OUTPUTS/fort.413.$fileToCheck.cygwin >> testing.log
diff -s ./fort.414 ./OUTPUTS/fort.414.$fileToCheck.cygwin >> testing.log
diff -s ./fort.415 ./OUTPUTS/fort.415.$fileToCheck.cygwin >> testing.log
diff -s ./fort.812 ./OUTPUTS/fort.812.$fileToCheck.cygwin >> testing.log
diff -s ./fort.813 ./OUTPUTS/fort.813.$fileToCheck.cygwin >> testing.log
diff -s ./fort.814 ./OUTPUTS/fort.814.$fileToCheck.cygwin >> testing.log
diff -s ./fort.815 ./OUTPUTS/fort.815.$fileToCheck.cygwin >> testing.log
rm ./$fileToCheck.a
rm ./fort.*

echo ' ' >> testing.log

echo Testing procedure finished
echo ==========================
echo Check 'testing.log'
 
