#!/bin/bash
####
# divado netcdf files for multi year periods climatologies #
###

isxmlgenerat=$1

WDIR=$(pwd)
DIVADIR="../../DIVA3D"

mkdir -p ./output/3Danalysis/MetaDataXMLs
#
./dvtxtmetainfo > ./output/3Danalysis/DriverMetainfo
#

#########################################################
for var in `cat varlist`
#########################################################
do

echo ' '
echo ' =================== Running divadoNCYR ======================== '
echo ' =================== working on variable: ' $var
echo ' '

rm -rf ${DIVADIR}/divastripped/input/*
rm -rf ${DIVADIR}/divastripped/output/*
rm -f ${DIVADIR}/divastripped/divawork/*
rm -f ${DIVADIR}/divastripped/3DWORK/*


mkdir -p ${DIVADIR}/divastripped/output
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis/MetaDataXMLs

cp -v './yearlist' ${DIVADIR}/divastripped/input/.
cp -v './monthlist' ${DIVADIR}/divastripped/input/.


#########################################################
for year in `cat yearlist`
#########################################################
do
echo year $year
#########################################################

# Prepare run diva_4Dnc_write

##mkdir -p ${DIVADIR}/divastripped/output/3Danalysis
mkdir -p ${DIVADIR}/divastripped/output/3Danalysis/Fields

cp -v $WDIR/output/3Danalysis/Fields/GridInfo.dat ${DIVADIR}/divastripped/output/3Danalysis/Fields/.

if [ -f './output/3Danalysis/'$var'.Metainfo.txt' ]; then
cp -v './output/3Danalysis/'$var'.Metainfo.txt'  ${DIVADIR}/divastripped/output/3Danalysis/.
fi

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCliste' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCliste' ${DIVADIR}/divastripped/output/3Danalysis/.

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCinfo' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCinfo' ${DIVADIR}/divastripped/output/3Danalysis/.

cd ./output/3Danalysis/

cp -v ./Fields/GridInfo.dat ${DIVADIR}/divastripped/output/3Danalysis/.

for ncfile in `ls $var.$year.*.anl.nc` ;do
cp -v $ncfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.nbrdata'` ;do
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.3Dparam'` ;do
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done
cd  $WDIR


else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCinfo'

fi
cd  $WDIR

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCliste'

fi

cd $WDIR

done

cd ${DIVADIR}/divastripped

dv4DncYRwrt $var

echo now saving needs to be done
cp -v ./output/3Danalysis/$var.4Danl.nc ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/$var'.4DNCMetainfo' ${WDIR}/output/3Danalysis/.
cp -v ./output/3Danalysis/$var'.Metainfo.txt' ${WDIR}/output/3Danalysis/.

cd $WDIR
cat  ./output/3Danalysis/DriverMetainfo ./output/3Danalysis/$var'.Metainfo.txt' > ./output/3Danalysis/MetaDataXMLs/$var'.Textinfo.txt'

echo '============================= divadoNCDF: end var loop    '$var

done

if [ $isxmlgenerat == "11" ]; then

echo 'generation of SDN xml metadata file'

divadoxml XMLtempl_sdn
fi

if [ $isxmlgenerat == "12" ]; then

echo 'generation of EDMONET xml metadata file'

divadoxml XMLtempl_emodn
fi

echo ==================
echo second loop
echo ==================
