#!/bin/bash

####
# divado netcdf file for multi year climatologies
###

WDIR=$(pwd)
DIVADIR="../../DIVA3D"

##################################################
# loop on years defined in yearlist
# loop on variables defined in varlist

#########################################################
for var in `cat varlist`
#########################################################
do
echo working on variable $var 

rm -rf ${DIVADIR}/divastripped/input/*
rm -f ${DIVADIR}/divastripped/output/*
rm -f ${DIVADIR}/divastripped/output/*/*
rm -rf ${DIVADIR}/divastripped/output/3Danalysis/* 
rm -f ${DIVADIR}/divastripped/divawork/*
rm -f ${DIVADIR}/divastripped/3DWORK/*

cp -v './yearlist' ${DIVADIR}/divastripped/input/.
cp -v './monthlist' ${DIVADIR}/divastripped/input/.


#########################################################
for year in `cat yearlist`
#########################################################
do
echo year $year
#########################################################

# Prepare run diva_4Dnc_write

mkdir ${DIVADIR}/divastripped/output/3Danalysis
mkdir ${DIVADIR}/divastripped/output/3Danalysis/Fields
cp $WDIR/output/3Danalysis/Fields/GridInfo.dat ${DIVADIR}/divastripped/output/3Danalysis/Fields/.

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCliste' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCliste' ${DIVADIR}/divastripped/output/3Danalysis/.

if [ -f './output/3Danalysis/'$var'.'$year'.3DNCinfo' ]; then

cp -v './output/3Danalysis/'$var'.'$year'.3DNCinfo' ${DIVADIR}/divastripped/output/3Danalysis/.

cd ./output/3Danalysis/
for ncfile in `ls $var.*.anl.nc` ;do
echo $ncfile
cp -v $ncfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.nbrdata'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done

for dtfile in `ls $var'.'$year'.'*'.3Dparam'` ;do
echo $dtfile
cp -v $dtfile ../../${DIVADIR}/divastripped/output/3Danalysis/.
done
cd  $WDIR


else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCinfo'

fi
cd  $WDIR

else

echo ====SEVERE ERROR==================
echo 'did not find ./output/3Danalysis/'$var'.'$year'.3DNCliste'

fi

cd $WDIR

done

echo ==================
echo first loop
echo ==================

cd ${DIVADIR}/divastripped

dv4DncYRwrt $var

echo now saving needs to be done
cp -v ./output/3Danalysis/$var.4Danl.nc ${WDIR}/output/3Danalysis/.
cd $WDIR

done

echo ==================
echo second loop
echo ==================
