#!/bin/bash

FILENAME=./input/NCDFinfo

if [ -f "$FILENAME" ]
then
{
read titlecomm
read titlestr
read reftimecomm
read reftimestr
read valtimecomm
read valtimestr
read cellmethcomm
read cellmethstr
read institcomm
read institstr
read produccomm
read producstr
read sourcecomm
read sourcestr
read commentcomm
read commentstr
read JRAxxcomm
read JRAxxstr
read accconcomm
read accconstr
read delinfocomm
read delinfostr
read estivolcomm
read estivolstr
read QACcomm
read QACstr
read SETUcomm
read SETUstr
read Refscomm
read Refsstr
} < $FILENAME
else
echo Please provide information file $FILENAME
exit
fi

mindep=$(tail -1 ./input/contour.depth)
echo mindep $mindep
maxdep=$(head -1 ./input/contour.depth)
echo maxdep $maxdep
minmon=$(head -1 ./monthlist)
echo minmon $minmon
maxmon=$(tail -1 ./monthlist)
echo maxmon $maxmon
#########################################################
for var in `cat varlist`
#########################################################
do
echo variable $var

#########################################################
for year in `cat yearlist`
#########################################################
do
echo year $year


FILENAME=./output/3Danalysis/$var'.'$year'.4DNCMetainfo'

if [ -f "$FILENAME" ]
then
{
read Sunit
read SouthBL
read NorthBL
read WestBL
read EastBL
read deltaX
read deltaY
read today
read year1
read year2
} < $FILENAME
else
echo Could not find $FILENAME
echo Please generate information file $FILENAME first
exit
fi

longvarname=$(grep -i $var ODVcolumns | awk -F "\t" '{print $1}' | awk -F " " '{print $1}')
longvarunit=$(grep -i $var ODVcolumns | awk -F "\t" '{print $1}' | awk -F " " '{print $2}')
if [ -f "${var}.units" ]
then
{
read longvarunit
} < $var.units
fi

if [ -f "${var}.longname" ]
then
{
read longvarname
} < $var.longname
fi


echo longvarname $longvarname
echo longvarunit $longvarunit


FILENAME='./input/Mdata_'$var'_'$year
if [ -f "$FILENAME" ]
then
rm './input/Mdata_'$var'_'$year
fi

echo ${longvarname} >> './input/Mdata_'$var'_'$year
echo ${longvarunit} >> './input/Mdata_'$var'_'$year
echo $QACstr >> './input/Mdata_'$var'_'$year
echo $SETUstr >> './input/Mdata_'$var'_'$year
echo $Refsstr >> './input/Mdata_'$var'_'$year
echo $Sunit >> './input/Mdata_'$var'_'$year
echo $SouthBL >> './input/Mdata_'$var'_'$year
echo $NorthBL >> './input/Mdata_'$var'_'$year
echo $WestBL >> './input/Mdata_'$var'_'$year
echo $EastBL >> './input/Mdata_'$var'_'$year
echo $deltaX'X'$deltaY >> './input/Mdata_'$var'_'$year
echo $mindep >> './input/Mdata_'$var'_'$year
echo $maxdep >> './input/Mdata_'$var'_'$year
echo $year1 >> './input/Mdata_'$var'_'$year
echo $year2 >> './input/Mdata_'$var'_'$year
echo ' '
echo './input/Mdata_'$var'_'$year':'
cat './input/Mdata_'$var'_'$year

done
done
