#!/bin/bash

FILENAME=driver
{
read isextractcomm
read isextractf
read iscontourcomm
read iscontour
read isdatacleancomm
read isdataclean
read minimumdatanumbercomm
read mindata
read isoptimisecomm
read isoptimise
read CLMINcomm
read CLMIN
read CLMAXcomm
read CLMAX
read SNMINcomm
read SNMIN
read SNMAXcomm
read SNMAX
read isanalysiscomm
read isanalysis
read lowerlevelcomm
read minlevel
read upperlevelcomm
read upperlevel
read referencecomm
read referenceflag
read isplotcomm
read isplot
} < $FILENAME

WDIR=$(pwd)
jmtrend=$(cat driver | wc -l)

echo "        DIVA CLIMATOLOGY RUN    INFORMATION FILE"
echo "        ****************************************"
echo "        ****************************************"
echo "   "
echo "   "
echo "   "
date
echo "   "
echo "   "
echo "   "
echo " Liste of variables:"
echo " *******************"
cat ./varlist
echo "   "
echo "   "
echo " Liste of years:"
echo " ***************"
cat ./yearlist
echo "   "
echo "   "
echo " Liste of months:"
echo " ****************"
cat ./monthlist
echo "   "
echo "   "
echo " Driver flag values for actions performed:"
echo " *****************************************"

echo "Extract data .....................................: " $isextractf
echo "Boundary lines and coastlines generation .........: " $iscontour
echo "Data cleaning ....................................: " $isdataclean
echo "Parameters optimisation ..........................: " $isoptimise
echo "Perform analysis .................................: " $isanalysis
echo "Gnu plots generation .............................: " $isplot

if [ "$jmtrend" -ge "29" ]
then
ngrp=`head -30 ${WDIR}'/driver'  |  tail -1`
fi
echo "Perform detrending ...............................: " $ngrp
echo "   "
echo "   "

echo " Driver bounds values:"
echo " *********************"

echo "Minimum data in a layer ..........................: "$mindata
echo "Minimum value for correlation length .............: "$CLMIN
echo "Maximum value for correlation length .............: "$CLMAX
echo "Minimum value for signal to noise ratio...........: "$SNMIN
echo "Maximum value for signal to noise ratio...........: "$SNMAX
echo "Lower level considered ...........................: "$minlevel
echo "Upper level considered ...........................: "$upperlevel
echo "   "
echo "   "
