#!/bin/bash

echo ==========================================
echo ==========================================
echo ==                                      ==
echo ==   Compilation of DIVA Stabil Module  ==
echo ==                                      ==
echo ==========================================
echo ==========================================
echo ' '

baseDir=$PWD

echo ===========================
echo ===========================
echo = Compiling Stabil Module =
echo ===========================
echo ===========================
echo ' '

preproFlag=''
associateDir='-I'$divaDir'/Module/General -I'$divaDir'/Module/IOModule '
export preproFlag
export associateDir

libName=libStabil$compiler.a
export libName
rm -f $divaModuleLib/$libName

# Compilation of : moduleStabil
# =============================
$divaDir/compileFile moduleStabil.f95 moduleStabil

echo ' '

mv *.mod $divaModuleLib

cd $baseDir

