#!/bin/bash



echo //////////////////////////////////////////////////
echo Cleaning up the mess
echo //////////////////////////////////////////////////
echo ' ' 

echo Making directories
echo ' ' 
mkdir -p ./divawork
mkdir -p ./meshgenwork
mkdir -p ./output
mkdir -p ./input
mkdir -p ./output/ghertonetcdf
mkdir -p ./output/meshvisu
mkdir -p ./gnuwork

echo Cleaning divawork and gnuwork directory
echo ' ' 
rm -f ./divawork/diva.log
rm -f ./divawork/fort.*
rm -f ./divawork/dvping
rm -f ./divawork/dvpong
rm -f ./divawork/divapipe
rm -f ./divawork/*.stackdump
rm -f ./gnuwork/*.stackdump
rm -f ./gnuwork/fort.*
rm -f ./gnuwork/plots/*
rm -f ./divawork/sub/*

echo Cleaning meshgenwork directory
echo ' ' 
rm -f ./meshgenwork/fort.*

echo Cleaning output directory
echo ' ' 
rm -f ./output/meshvisu/fort.*
rm -f ./output/*.anl
rm -f ./output/ghertonetcdf/GridInfo.dat
rm -f ./output/ghertonetcdf/fort.*
rm -f ./output/*.dat
rm -f ./output/*.nc
rm -f ./output/*.ref

echo Looking for density file...
echo ' ' 
if [ -f ./input/coast.cont.dens ] 
then
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo ... there is a coast.cont.dens file
echo Are you sure you provided it for this application?
echo
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo In any case, make sure the input files in ./input are OK
echo
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
else 
echo ... there is no density file	
fi

echo ' ' 
echo --------------------
echo Cleaning is finished
echo --------------------