#!/bin/bash



echo ///////////////////////////////////////////
echo           Cross Validation
echo ///////////////////////////////////////////
echo ' '

nddd=$(cat ./input/data.dat | wc -l)

if [ $# -eq 0 ] 
then
echo ==============================
echo Need at least two paramteres for divacv:
echo number of points for cross references
echo number of repeated data removal
echo ===============================
else


if [ "$1" == "-r" ]
then
echo Please put option -r after the two numbers
else




let nppp=$1*$2
if [ "$nppp" -gt "$nddd" ]
then
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo Your statistics will not be independant
echo $1 times $2 = $nppp is larger than $nddd
echo Stopping
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
else

cp ./input/param.par  ./input/param.par.ori
cp ./input/data.dat  ./input/data.dat.ori
rm -f ./input/valatxy.coord.ori
mv ./input/valatxy.coord ./input/valatxy.coord.ori
rm -f ./output/gcv.dat

if [ -f ./input/gcvsampling.dat ]
then
#Create mesh once
if [ -f ./meshgenwork/fort.22 ]
then 
echo ===========================================================================
echo Mesh files aready exist, hope they are correct: otherwise exectute divamesh
echo ===========================================================================
else
divamesh
fi
else
echo Need to provide gcvsampling.dat in ./input !
fi



for gcv in `cat ./input/gcvsampling.dat`
do
echo working with $gcv


#For a given subsample size
isize=$1
ijm=0
N=$2
rm -f ./divawork/cverror.dat
rm -f ./divawork/cvdatavar.dat
#Repeat N times the estimates
while [ "$ijm" -lt "$N" ]
do
# Extract a random subsample 


dvsample $isize $ijm




let ijm=$ijm+1
head -17 ./input/param.par.ori > bidon
echo 1 >> bidon
echo   >> bidon
echo 1 >> bidon
echo   >> bidon
echo -99 >> bidon
echo >> bidon
echo $gcv >> bidon
#tail -2 ./input/param.par.ori >> bidon
# no error field
echo >> bidon
echo 0 >> bidon
mv bidon ./input/param.par

divacalc


#now calculate errors from differences in valatxy.coord and fieldatxyascii.anl
# only in real points
# with valex=-99
# and cat them into a file

cd divawork
cp ../input/valatxy.coord fort.20
cp ../output/valatxyascii.anl fort.21
echo -99 | ../../bin/cverror.a
cat fort.22 >> cverror.dat
cat fort.33 >> cvdatavar.dat
cd ..

# End loops
# 
done
cd divawork
cp cverror.dat fort.20
cp cvdatavar.dat fort.21
echo $gcv | ../../bin/cvtotalerror.a
cat fort.22 >> ../output/gcv.dat
cd ..
#Next cv test
done



mv ./input/param.par.ori ./input/param.par
mv ./input/data.dat.ori ./input/data.dat
mv ./input/valatxy.coord.ori ./input/valatxy.coord
cp ./output/gcv.dat ./divawork/fort.11
cd divawork

echo Looking for the minimum of GCV
echo ' '

if [ -f ../input/gcvsampling.dat ] 
then 
../../bin/findmin.a
echo ' '
echo ----------------------------------------
echo CV finished
echo Results written in ./output/gcvsnvar.dat
echo ----------------------------------------
else
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo Check execution track
echo --------------------------------------------
fi

mv fort.12 ../output/gcvsnvar.dat




echo -----------------------------------------------------
echo 'Creating adapted param.par in ./output/param.par.gcv'
echo -----------------------------------------------------
head -23 ../input/param.par  > ../output/param.par.gcv
head -2 ../output/gcvsnvar.dat | tail -1 >> ../output/param.par.gcv
head -25 ../input/param.par | tail -1 >> ../output/param.par.gcv
head -4 ../output/gcvsnvar.dat  | tail -1 >> ../output/param.par.gcv


if [ "$3" == "-r" ]
then
echo =======================================================
echo Replacing  param file with fit
cd ..
cp -v ./input/param.par ./input/param.par.old
cp -v ./output/param.par.gcv ./input/param.par
echo =======================================================
fi




fi
fi

fi
