#!/bin/bash



echo ' '
echo %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
echo %% Try to translate contours into gridded  format %%%
echo %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


cp ./input/TopoInfo.dat ./divawork/fort.13

cp ./input/coast.cont ./divawork/fort.10

cd ./divawork
../../bin/cont2grid.a

cp -v fort.99 ../output/topomask.grd


rm -f fort13
rm -f fort.10
rm -f fort.99
rm -f fort.66

if [ "$1" == "-r" ] 
then
echo Placing new contour file as input
cp -v ../output/topomask.grd ../input/topomask.grd
fi

cd ..
