#!/bin/bash
echo //////////////////////////////////////////////////
echo                Mesh generation
echo //////////////////////////////////////////////////
echo ' '
if [ -f ./input/coast.cont ] 
then
cp ./input/coast.cont ./meshgenwork/fort.10
else
echo Need to provide coast.cont in ./input !
fi
isdens=0
if [ -f ./input/coast.cont.dens ] 
then
echo There is a density file for the mesh
cp -v ./input/coast.cont.dens ./meshgenwork/fort.12
isdens=1
fi
##echo $isdens
if [ -f ./input/param.par ] 
then
echo Reading parameters
else
echo Need to provide param.par in ./input/
fi
Filepar=./input/param.par
{
read linecomment
read lc
read linecomment
read icoordchange
read linecomment
read ispec
read linecomment
read ireg
read linecomment
read xori
read linecomment
read yori
read linecomment
read dx
read linecomment
read dy
read linecomment
read nx
read linecomment
read ny
read linecomment
read valex
read linecomment
read snr
read linecomment
read varbak
} < $Filepar
#param.par
#creation of files for mesh generation
#creation of file fort.11 for gener.a
#rm fort.11
#exec 11<>fort.11
#echo 0 > ./meshgenwork/fort.11
#echo $lc >> ./meshgenwork/fort.11
#echo 1.5 >> ./meshgenwork/fort.11
#echo 5 >> ./meshgenwork/fort.11
#exec 11>&-

rm -f fort.11
echo $isdens $lc | ../bin/lcelem.a
mv fort.11 ./meshgenwork/fort.11
echo 1.5 >> ./meshgenwork/fort.11
echo 5 >> ./meshgenwork/fort.11
#exec 11>&-
#generation of the mesh
cd ./meshgenwork
if [ -f ../output/diva.log ] ; then
 cp -f ../output/diva.log .
fi
echo $icoordchange | ../../bin/generopt.a >> diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          divamesh      generopt.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> diva.log
echo -------------------------------------------- >> diva.log
echo A problem was encountered during execution ! >> diva.log
echo          divamesh      generopt.a  >> diva.log
echo Check execution track >> diva.log
echo -------------------------------------------- >> diva.log
fi
 cp -f diva.log ../output/.
File23=./fort.23
{
read nnt1
read nnint
read nelt
} < $File23
#output of info for mesh visualisation with meshvisu.m
echo ' '
echo Copying output files for visualisation 
echo in directory ./output/meshvisu/ 
cp fort.10 ../output/meshvisu/
cp fort.22 ../output/meshvisu/
cp fort.23 ../output/meshvisu/
 
#exec 23<>fort.23
#read  nnt1 nnint nelt <&3
#exec 23>&-
cd ..
echo ' '
echo ---------------
echo Mesh is created
echo ---------------
echo ' '

