#!/bin/bash



#echo Cleaning up the mess
divaclean
#echo Gridding
divamesh
#echo Analysing
divacalc
#echo Looking for outliers
divaqcbis
echo oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo Diva finished the performance
echo oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
