#!/bin/bash
#
##########################################
#
  Fileinf=./input/3Dinfo
{
read comment
read var
read comment
read lay1
read comment
read lay2
read comment
read cont
read comment
read datop
read comment
read parop
read comment
read ana3d
} < $Fileinf
#
if [ "$cont" -ge "1" ]; then
./diva3Dcont
fi
#
if [ "$datop" -ge "1" ]; then
./diva3Ddat
fi
#
if [ "$parop" == "1" -o  "$parop" == "-1" ]; then
./diva3Dclop
fi
if [ "$parop" == "2" -o  "$parop" == "-2" ]; then
./diva3Dsnop
fi
if [ "$parop" == "3" -o  "$parop" == "-3" ]; then
./diva3Dclop
./diva3Dsnop
fi
if [ "$parop" == "10" -o  "$parop" == "-10" ]; then
./diva3Dclop
fi
if [ "$parop" == "30" -o  "$parop" == "-30" ]; then
./diva3Dclop
./diva3Dsnop
fi
#
if [ "$ana3d" -ge "1" ]; then
./diva3Dsub
fi
#

