#!/bin/bash

# Usage divadatacoverage [-n] [-r]
# -n: only needed if no gridded solution in output
# -r: creates RL.dat and RLinfo.dat in input

echo ' '
echo =============================================================
echo Preparing RL field based on data coverage
echo Preparing data density field DATABINS.dat
echo =============================================================

if [ "$1" == "-n" -o "$2" == "-n" ]
then
echo Preparing a dummy gridded solution first
echo ========================================
cp ./input/param.par ./input/param.par.orirl

Filepar=./input/param.par
{
read linecomment
read lc
read linecomment
read icoordchange
read linecomment
read ispec
read linecomment
read ireg
read linecomment
read xori
read linecomment
read yori
read linecomment
read dx
read linecomment
read dy
read linecomment
read nx
read linecomment
read ny
read linecomment
read valex
read linecomment
read snr
read linecomment
read varbak
} < $Filepar

cd input
head -1 param.par.orirl > param.par
echo $lc 10 | ../../bin/multiply.a >> param.par
head -7 param.par.orirl  | tail -5 >> param.par
echo 3 >> param.par
head -23 param.par.orirl   | tail -15 >> param.par
echo $snr 0.1 | ../../bin/multiply.a >> param.par
echo varba >> param.par
echo 0 >> param.par
cd ..

divamesh

divacalc




# echo saving reference fields

mv ./input/param.par.orirl ./input/param.par
echo '  '
echo ==============================================================
echo Finished preparing gridded field
echo ==============================================================

fi


cp -v ./output/fieldgher.anl ./divawork/fort.10
cp -v ./output/ghertonetcdf/GridInfo.dat ./divawork/fort.11
cp -v ./input/data.dat ./divawork/fort.40
cd divawork

if [ -f ../output/diva.log ] ; then
 cp -f ../output/diva.log .
fi

echo 10 | ../../bin/datalengthscale.a >> diva.log

if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          divadataclean      datalengthscale.a
echo Check execution track
echo --------------------------------------------

echo ' ' >> diva.log
echo -------------------------------------------- >> diva.log
echo A problem was encountered during execution ! >> diva.log
echo          divadataclean      datalengthscale.a  >> diva.log
echo Check execution track >> diva.log
echo -------------------------------------------- >> diva.log
fi

 cp -f diva.log ../output/.

cd ..
cp -v ./divawork/fort.11 ./output/RLinfo.dat
cp -v ./divawork/fort.20 ./output/RL.dat
cp -v ./divawork/fort.21 ./output/DATABINS.dat
cp -v ./divawork/fort.11 ./output/DATABINSinfo.dat
cp -v ./divawork/fort.33 ./output/meandistance.dat

if [ "$1" == "-r" -o "$2" == "-r" ]
then
echo =======================================================
echo Replacing  RL files

cp -v ./output/RL*.dat ./input
echo =======================================================
fi


echo ' '
echo ==============================================================
echo Finished preparing binning field
echo ==============================================================