#!/bin/bash

echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo  Applying iterative detrending on classes
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


echo need to modify param.par for iterations to desactivate error calculations

cp -v ./input/param.par ./input/param.detrend.par

head -17 ./input/param.detrend.par > bidon
echo 1 >> bidon
echo   >> bidon
echo 1 >> bidon
echo   >> bidon
echo -99 >> bidon
echo >> bidon
echo $gcv >> bidon
echo >> bidon
echo 0 >> bidon
mv bidon ./input/param.par

nsteps=10

if [ "$#" -gt "0" ]
then
let nsteps=$1+0
fi
echo =============================================
echo Number of iterations to be performed: $nsteps
echo =============================================


i=0

while [ "$i" -le "$nsteps" ]
do
let i=$i+1
echo Iteration $i

if [ "$i" -gt "$nsteps" ]
then
echo Last final analysis

cp -v ./input/param.detrend.par ./input/param.par 
rm -f ./input/param.detrend.par

fi

divacalc
echo Calculating misfit of classes and create new input data

if [ -f ./input/data.undetrend.dat ]
then
cp -v ./input/data.undetrend.dat ./input/data.dat
fi


cd divawork
cp ../input/data.dat fort.88
cp ../output/fieldatdatapoint.anl fort.89
../../bin/detrend.a
cp fort.90 ../input/data.detrend.dat
cp fort.97 ../output/trends.dat
cd ..


if [ -f ./input/data.undetrend.dat ]
then
cp -v ./input/data.detrend.dat ./input/data.dat
else
cp -v ./input/data.dat ./input/data.undetrend.dat
cp -v ./input/data.detrend.dat ./input/data.dat
fi
if [ "$i" -gt "1" ]
then
paste ./output/trends.dat ./output/trends.all.dat > bidon
else
cp ./output/trends.dat bidon
fi
mv bidon ./output/trends.all.dat


done






echo ' '
echo ----------------------
echo Detrending is finished
echo ----------------------








