#!/bin/bash
#
#     WRITES 4D NETCDF FILES
# 
#####################################################
#
var=$1
#
cd ./3DWORK/
cp -v '../output/3Danalysis/'$var'.3DNCliste' './3Dncliste'
cp -v '../output/3Danalysis/'$var'.3DNCinfo' './3DNCinfo'
#
if [ -f fort.44 ];then
rm fort.44
fi
#
nbfls=`cat './3Dncliste' |wc -l`
echo $nbfls >> ./fort.44
../../bin/diva4Dstr.a
#
cd ../
