#!/bin/bash

export LC_ALL=C 






cd divawork

cp ../input/data.dat fort.44
LR=0
LD=1
if [ -f ../output/fieldatdatapoint.anl.ref ]
then
 LD=$(cat ../input/data.dat | wc -l)
 LR=$(cat ../output/fieldatdatapoint.anl.ref | wc -l)
 echo $LD $LR
fi

if [ "$LD" -eq "$LR" ]
then
echo ' '
echo ===================================================================
echo There are already reference fields at data points. Will use them
echo Preparing data anomalies based on ./output/fieldatdatapoint.anl.ref
echo ===================================================================

else
echo ' '
echo ===================================================================
echo !!!!! Will try to use gridded reference field by interpolation !!!!!
echo !!!!! Will also create reference field at valatxy.coord !!!!!!!!!!!!
echo ===================================================================

cp ../output/fieldgher.anl.ref fort.20
cp ../output/ghertonetcdf/GridInfo.dat fort.21
cp ../input/valatxy.coord fort.45
../../bin/interprefe.a


cp -v fort.81 ../output/fieldatdatapoint.anl.ref
cp -v  fort.82 ../output/valatxyascii.anl.ref
rm fort.45
rm fort.20
rm fort.21
rm fort.81
rm fort.82
# keep fort.44
fi

echo ============================
echo       Now anomalies
echo ============================


head -22 ../input/param.par | tail -1 > coucou
{
read valex
} < coucou
rm coucou
paste ../output/fieldatdatapoint.anl.ref ../input/data.dat > bidon

mv ../input/data.dat ../input/data.dat.full
awk -v valex=$valex '{$6=$6-$3; $1=""; $2=""; $3=""; print $0}' bidon > ../input/data.dat


rm bidon

echo ===================================================================
echo data.dat now contains anomalies
echo data.dat.full are original data
echo ===================================================================
echo  ' '
