#!/bin/bash
#
#####################################################
#
#####################################################
#
if [ -d  ./output/3Danalysis/ ];then
echo  ./output/3Danalysis exists
else
mkdir -p ./output/3Danalysis/
fi
#
#
  Fileinf=./input/3Dinfo
{
read comment
read var
read comment
read bottm
read comment
read surf
read comment
read cont
read comment
read datop
read comment
read parop
read comment
read ana3d
read comment
read comment
read comment
read comment
read comment
read comment
read comment
read comment
read comment
read gnpl
read comment
read gmin
read comment
read gmax
} < $Fileinf
#
dep=$bottm
#
while [ $dep -le $surf ]
do
#
let lev=10000+$dep
#
errflag=0
if [ -f ./input/divaparam/param.par.$var'.'$lev ];then
 cp -f ./input/divaparam/param.par.$var'.'$lev ./input/param.par
else
 if [ -f ./input/divaparam/param.par.$lev ];then
   cp -f ./input/divaparam/param.par.$lev ./input/param.par
 else
    if [ -f ./input/divaparam/param.par ];then
     cp -f ./input/divaparam/param.par ./input/param.par
    else
     if [ -f ./input/param.par ];then
       echo diva3Ddat uses param.par found in input
     else
       errflag=1
     fi
    fi
 fi
fi
#
if [ -f  ./input/divadata/$var.$lev ] ; then
 cp ./input/divadata/$var.$lev  ./input/divadata/$var.$lev.ori
 cp ./input/divadata/$var.$lev  ./input/data.dat
 nbdat=`cat './input/data.dat' |wc -l` 
 if [ "$nbdat" == "0" ] ; then
  errflag=4
 fi
else
 errflag=2
fi
#
if [ -f  ./input/divaparam/coast.cont.$lev ] ; then
 cp ./input/divaparam/coast.cont.$lev ./input/coast.cont
else
 errflag=3
fi
#
if [ "$errflag" == "0" ];then
#
#--------------------------------------------------------
#
if [ -f ./input/divaparam/3Dconstraint ]
then
dep=10001
  Fileinf=./input/divaparam/3Dconstraint
{
while [ $dep -le $lev ]
do
read constvals
dep=`expr $dep + 1`
done
} < $Fileinf
echo $constvals > ./input/constraint.dat
fi
#
if [ -f ./input/constraint.dat ]
then
 if [ -f ./input/divaUVcons/UVinfo.$var.$lev ];then
  cp -f ./input/divaUVcons/UVinfo.$var.$lev ./input/UVinfo.dat
 else
  if [ -f ./input/divaUVcons/UVinfo.$lev ];then
   cp -f ./input/divaUVcons/UVinfo.$lev ./input/UVinfo.dat
  else
   if [ -f ./input/divaUVcons/UVinfo.dat ];then
    cp -f ./input/divaUVcons/UVinfo.dat ./input/UVinfo.dat
   fi
  fi
 fi
#
 if [ -f ./input/divaUVcons/Uvel.$var.$lev ];then
  cp -f ./input/divaUVcons/Uvel.$var.$lev ./input/Uvel.dat
 else
  if [ -f ./input/divaUVcons/Uvel.$lev ];then
   cp -f ./input/divaUVcons/Uvel.$lev ./input/Uvel.dat
  else
   if [ -f ./input/divaUVcons/Uvel.dat ];then
    cp -f ./input/divaUVcons/Uvel.dat ./input/Uvel.dat
   fi
  fi
 fi
#
 if [ -f ./input/divaUVcons/Vvel.$var.$lev ];then
  cp -f ./input/divaUVcons/Vvel.$var.$lev ./input/Vvel.dat
 else
  if [ -f ./input/divaUVcons/Vvel.$lev ];then
   cp -f ./input/divaUVcons/Vvel.$lev ./input/Vvel.dat
  else
   if [ -f ./input/divaUVcons/Vvel.dat ];then
    cp -f ./input/divaUVcons/Vvel.dat ./input/Vvel.dat
   fi
  fi
 fi
fi
#
if [ -f ./input/divaparam/RLinfo.$var.$lev ];then
 cp -f ./input/divaparam/RLinfo.$var..$lev ./input/RLinfo.dat
else
 if [ -f ./input/divaparam/RLinfo.$lev ];then
  cp -f ./input/divaparam/RLinfo.$lev ./input/RLinfo.dat
 else
  if [ -f ./input/divaparam/RLinfo.dat ];then
   cp -f ./input/divaparam/RLinfo.dat ./input/RLinfo.dat
  fi
 fi
fi
if [ -f ./input/RLinfo.dat ];then
 if [ -f ./input/divaparam/RL.$var.$lev ];then
  cp -f ./input/divaparam/RL.$var.$lev ./input/RL.dat 
 else
  if [ -f ./input/divaparam/RL.$lev ];then
   cp -f ./input/divaparam/RL.$lev ./input/RL.dat 
  else
   if [ -f ./input/divaparam/RL.dat ];then
    cp -f ./input/divaparam/RL.dat ./input/RL.dat
   fi
  fi
 fi
fi
#------------------------------------------------------------
#
if [ "$datop" -eq "1" -o "$datop" -eq "3"  -o "$datop" -ge "4" -o "$datop" -ge "5" ];then
./divaclean
echo '%%%%%%%%%%%%  cleaning '$var'.'$lev' %%%%%%%%%%'
./divadataclean
cp -v ./input/data.dat ./input/divadata/$var.$lev
cp -v ./input/data.beforeclean.dat ./input/divadata/$var.$lev.notclean
fi
#
if [ "$datop" -eq "3" ];then
   ./divadatacoverage -n
 cp -v ./output/RL.dat ./input/divaparam/RL.$var.$lev
 cp -v ./output/RLinfo.dat ./input/divaparam/RLinfo.dat
fi
if [ "$datop" -eq "2" ];then
  ./divaclean
  ./divadatacoverage -n
  cp -v ./output/RL.dat ./input/divaparam/RL.$var.$lev
  cp -v ./output/RLinfo.dat ./input/divaparam/RLinfo.dat
fi
#
if [ "$datop" -eq "4" -o "$datop" -eq "5" ];then
#
if [ -d  ./output/3Danalysis/FieldWithOutliers ];then
echo  ./output/3Danalysis/FieldWithOutliers exists
else
mkdir -p ./output/3Danalysis/FieldWithOutliers
fi
#
echo '%%%%%%%%%%%%  ELIMINATION OF OUTLIERS '$var'.'$lev' %%%%%%%%%%'
 ./divadress
 ./divaqcbis
 ./dvoutlierclean -r
  cp -v ./input/data.dat.withoutliers ./input/divadata/$var.$lev.withoutliers
  cp -v ./input/data.dat.nooutliers ./input/divadata/$var.$lev
if [ "$datop" -eq "5" ];then
 cp -f ./input/data.dat.nooutliers ./input/data.dat
   ./divadatacoverage -n
 cp -v ./output/RL.dat ./input/divaparam/RL.$var.$lev
 cp -v ./output/RLinfo.dat ./input/divaparam/RLinfo.dat
fi

./divadatacoverage
cp -v ./output/DATABINS.dat ./input/divadata/$var'.'$lev'.DATABINS'
cp -v ./output/DATABINSinfo.dat ./input/divadata/$var'.'$lev'.DATABINSinfo'


######## saving analysis and co
cp -v ./output/ghertonetcdf/results.nc ./output/3Danalysis/FieldWithOutliers/$var'.'$lev'.anl.nc'
cp -v ./output/ghertonetcdf/fort.84 ./output/3Danalysis/FieldWithOutliers/$var'.'$lev'.anl'
cp -v ./output/ghertonetcdf/GridInfo.dat ./output/3Danalysis/FieldWithOutliers/GridInfo.dat
cp -v ./output/errorfieldgher.anl ./output/3Danalysis/FieldWithOutliers/$var'.'$lev'.error'
cp -v ./output/fieldascii.anl ./output/3Danalysis/FieldWithOutliers/$var'.'$lev'.ascii.anl'
cp -v ./output/errorfieldascii.anl ./output/3Danalysis/FieldWithOutliers/$var'.'$lev'.errorascii'
#
if [ -f ./output/outliersbis.normalized.dat ];then
cp -v ./output/outliersbis.normalized.dat ./output/3Danalysis/FieldWithOutliers/$var'.'$lev'.outliersbis.norm'
fi
if [ -f ./output/outliersbis.dat ];then
cp -v ./output/outliersbis.dat ./output/3Danalysis/FieldWithOutliers/$var'.'$lev'.outliersbis'
fi
##
if [ "$gnpl" == "1" ]
then
#
mkdir -p ./output/3Danalysis/GPlotsWOutlrs
#
if [ -f './output/covariancefit.'${var}.${lev} ];then
cp -v './output/covariancefit.'${var}.${lev} ./output/covariancefit.dat
fi
if [ -f './output/covariance.'${var}.${lev} ];then
cp -v './output/covariance.'${var}.${lev} ./output/covariance.dat
fi
./divagnu $gmin $gmax
#
cd ./gnuwork/plots
for i in `ls *.png`
do
cp -v $i ../../output/3Danalysis/GPlotsWOutlrs/$var'.'$lev'.'$i
done
fi
####################

fi
#
else
if [ "$errflag" -eq "1" ];then
echo '!!!!!!!!!!!!!diva3Ddat WARNING: !!!!!!!!!!!!!!!!!!'
echo '!!!!!!!!DID NOT FIND param.par FILE FOR '$var $lev'!' 
echo '!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
fi
if [ "$errflag" -eq "2" ];then
echo '!!!!!!!!!!!!!diva3Ddat WARNING: !!!!!!!!!!!!!!!!!!'
echo '!!!!!!!!!!!!!DID NOT FIND DATA FILE FOR '$var $lev'!' 
echo '!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
fi
if [ "$errflag" -eq "3" ];then
echo '!!!!!!!!!!!!!diva3Ddat WARNING: !!!!!!!!!!!!!!!!!!'
echo '!!!!!!!!!!DID NOT FIND CONTOUR FILE FOR '$var $lev'!' 
echo '!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
fi
if [ "$errflag" -eq "4" ];then
echo '!!!!!!!!!!!!!diva3Ddat WARNING: !!!!!!!!!!!!!!!!!!'
echo '!!!!!!!!!!DATA FILE  '$var $lev' IS EMPTY!' 
echo '!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
fi
fi
#
 dep=`expr $dep + 1`
done
echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo ' cleaned data files are in ./input/divadata/.'
echo ' and/or RL files are in ./input/divaparam/.' 
echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
#