#!/bin/bash

# Flat colors, ie boxes with uniform filling
smooth=1
# smooth=1 will interpolate color filling


cd gnuwork
rm fort.*
echo preparing files for mesh plot
cp ../meshgenwork/fort.22 .
cp ../meshgenwork/fort.23 .
../../bin/forgnuplotmesh.a
# output if fort.69
../../bin/forgnuplotmeshl.a
# output if fort.71

echo preparing files for coast plot
cp ../input/coast.cont fort.66
../../bin/forgnuplotcoastfilled.a
# output is fort.67
cat dvcoastlineheader > diva_coastlinefilled
cat dvcoastlinetailer>> diva_coastlinefilled




rm -f fort.19
if [ -f ../input/RL.dat ] 
then
echo preparing RL field
cp ../input/RL.dat fort.20
cp ../input/RLinfo.dat fort.21
if [ "$smooth" == "1" ]
then
../../bin/forgnuplotanalysissmooth.a
else
../../bin/forgnuplotanalysis.a
fi
# output is fort.68
mv fort.68 fort.72
fi


rm -f fort.19
if [ -f ../output/DATABINS.dat ] 
then
echo preparing DATABINS field
cp ../output/DATABINS.dat fort.20
cp ../output/DATABINSinfo.dat fort.21

../../bin/forgnuplotanalysis.a

# output is fort.68
mv fort.68 fort.73
fi



if [ -f ../input/Uvel.dat ] 
then
echo preparing velocity field
cp ../input/Uvel.dat fort.30
cp ../input/Vvel.dat fort.31
cp ../input/UVinfo.dat fort.32
../../bin/forgnuplotuv.a
# output is fort.55
fi

echo ' ' > fort.99
cat ../input/data.dat >> fort.99

awk 'NF<2{printf"\n"}{print}' < fort.71 > fort.11


echo preparing files for analysis and error plot
rm -f fort.19
if [ -f ../output/errorfieldgher.anl ] 
then
echo preparing error field
cp ../output/errorfieldgher.anl fort.19
fi
cp ../output/fieldgher.anl fort.20
cp ../output/ghertonetcdf/GridInfo.dat fort.21
#../../bin/forgnuplotanalysis.a
if [ "$smooth" == "1" ]
then
../../bin/forgnuplotanalysissmooth.a
else
../../bin/forgnuplotanalysis.a
fi
# output is fort.68
mv fort.41 dvanalysisrange
mv fort.40 longref.dat.default


jj=$(cat ../output/outliersbis.normalized.dat | wc -l)
let jj=$jj-4
if [ "$jj" -ge "0" ]
then
head -$jj ../output/outliersbis.normalized.dat | tac > fort.43
fi

if [ "$#" == "2" ]
then 
. divaplotall $1 $2
else
. divaplotall
fi

cd ..