#!/bin/bash



echo //////////////////////////////////////////////////
echo Going to select data in bounding box
echo //////////////////////////////////////////////////

if [ "$#" == "2" ]
then

echo //////////////////////////////////////////////////
echo Going to select data in range $1 $2
echo //////////////////////////////////////////////////
echo $1 $2 > ./divawork/fort.60
fi

cp ./input/data.dat ./divawork/fort.44
cp ./input/coast.cont ./divawork/fort.10
cd divawork
nbccol=$(head -n 1 ./fort.44 | wc -w)
echo $nbccol | ../../bin/datacheck.a

cd ..
rm -f ./divawork/fort.60
mv ./input/data.dat ./input/data.dat.full
cp ./divawork/fort.20 ./input/data.dat
echo //////////////////////////////////////////////////
echo Finished eliminating data out of the bounding box
echo Data retained are in ./input/data.dat
echo Original data are in ./input/data.dat.full
echo //////////////////////////////////////////////////
echo ////////////////////////////////////////////////////////
echo Now eliminating points outside of the mesh
if [ -f ./output/fieldatdatapoint.anl ]
then
echo Analysed field already exists: will use it
else
echo Analysed field does not exists: will create it
divadatacoverage -n
fi
dvdataclean
