#!/bin/bash
#######################################
#
# $1 = level number
# $2 = variable name.
#======================================
lev=$1
var=$2
ntrans=$3
act=$4

flag=1
nblines=0
if [ "$act" == "1" ];then

if [ -f ./output/3Danalysis/Fields/$var.$lev.anl.nc ];then

 cp ./output/3Danalysis/Fields/$var.$lev.anl.nc ./output/3Danalysis/Fields/$var.$lev.anl.tr.nc
 cp ./output/3Danalysis/Fields/$var.$lev.anl ./output/3Danalysis/Fields/$var.$lev.anl.tr

ncdfile=$var.$lev.anl.nc
binfile=$var.$lev.anl
ascfile=$var.$lev.ascii.anl
echo 'dv3Dinvtrsh '$gherfile' '$binfile

flag=0

fi
fi

if [ "$act" == "2" ];then

if [ -f ./output/3Danalysis/Fields/$var.$lev.ref.nc ];then

 cp ./output/3Danalysis/Fields/$var.$lev.ref.nc ./output/3Danalysis/Fields/$var.$lev.ref.tr.nc
 if [ -f ./output/3Danalysis/Fields/$var.$lev.ref ];then
  cp ./output/3Danalysis/Fields/$var.$lev.ref ./output/3Danalysis/Fields/$var.$lev.ref.tr
  binfile=$var.$lev.ref
  echo 'dv3Dinvtrsh ncfile '$binfile
 fi
 if [ -f ./output/3Danalysis/Fields/$var.$lev.datapoint.ref ];then
  cp ./output/3Danalysis/Fields/$var.$lev.datapoint.ref ./output/3Danalysis/Fields/$var.$lev.datapoint.ref.tr
  ascfile=$var.$lev.datapoint.ref
  nblines=`cat ./output/3Danalysis/Fields/$ascfile |wc -l` 
  echo 'dv3Dinvtrsh ascfile '$ascfile
 fi

ncdfile=$var.$lev.ref.nc
echo 'dv3Dinvtrsh ncfile '$binfile

flag=0

fi
fi

if [ "$flag" == "1" ];then

echo ' did not find '$var'.'$lev' 2D file (analysis of transformed data)'

exit

fi

##if [ -d ./3DWORK ];then
##echo 'starting transformation of '$var'.'$lev'.anl.nc'
##else
mkdir -p ./3DWORK
echo 'starting transformation of '$var'.'$lev'.anl.nc'
##fi
#
echo $ncdfile > ./3DWORK/ncname
echo $binfile >> ./3DWORK/ncname
echo $ascfile >> ./3DWORK/ncname
echo $var >> ./3DWORK/ncname
echo $lev >> ./3DWORK/ncname
echo $act >> ./3DWORK/ncname
echo $ntrans >> ./3DWORK/ncname
echo $nblines >> ./3DWORK/ncname
#
# Start analyses inverse transformation
#######################################
#
echo 'Start analyses inverse transformation '$ntrans

  cd ./3DWORK
  if [ -f ERR.$var.$lev ];then
  echo 'No inverse transformation for '$var.$lev
  else
  echo ' Inverse transformation for '$var.$lev
  ../../bin/anatrans.a
  fi
  cd ../
#
# End analyses inverse transformations
######################################
#
