#!/bin/bash
#######################################
#
# $1 = level number
# $2 = variable name.
#======================================
lev=$1
var=$2
ntrans=$3
if [ -f ./output/3Danalysis/Fields/$var.$lev.anl.nc ];then
  cp ./output/3Danalysis/Fields/$var.$lev.anl.nc ./output/3Danalysis/Fields/$var.$lev.anl.tr.nc
  gherfile=$var.$lev.anl.nc
  ascfile=$var.$lev.anl.asc
  echo $gherfile
else
if [ -f ./output/3Danalysis/Fields/$var.$lev.ref.nc ];then
  cp ./output/3Danalysis/Fields/$var.$lev.ref.nc ./output/3Danalysis/Fields/$var.$lev.ref.tr.nc
  gherfile=$var.$lev.ref.nc
  ascfile=$var.$lev.ref.asc
  echo $gherfile
else
  echo dv3Dinvtrsh: did not find $var.$lev 2D ncfile
  exit
fi
fi
#
if [ -d ./3DWORK ];then
echo 'starting transformation of '$var'.'$lev'.anl.nc'
else
mkdir ./3DWORK
echo 'starting transformation of '$var'.'$lev'.anl.nc'
fi
#
  echo $gherfile > ./3DWORK/ncname
##  echo $ascfile >> ./3DWORK/ncname
  echo $var >> ./3DWORK/ncname
  echo $lev >> ./3DWORK/ncname
  echo $ntrans >> ./3DWORK/ncname

# Start analyses inverse transformation
#######################################
#
echo 'Start analyses inverse transformation'

  cd ./3DWORK
  if [ -f ERR.$var.$lev ];then
  echo 'No inverse transformation for '$var.$lev
  else
  ../../bin/anatrans.a
  fi
  cd ../
#
# End analyses inverse transformations
######################################
#
