#!/bin/bash
export LC_ALL=C
# Flat colors, ie boxes with uniform filling
smooth=1
# smooth=1 will interpolate color filling
#
##lev=$3
##var=$4
gmin=$1
gmax=$2

saveifs=$IFS
IFS=$'\n'
{
read lev
read var
} < levvar
IFS=$saveifs

echo 'lev var gmin gmax '$lev "$var" $gmin $gmax
rm -f dvanalysisrange
#
cd gnuwork
rm fort.*
echo "preparing files for mesh plot"
cp '../input/divamesh/meshtopo.'$lev fort.22 
cp '../input/divamesh/mesh.dat.'$lev fort.23 
../../bin/forgnuplotmesh.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotmesh.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotmesh.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
# output if fort.69
../../bin/forgnuplotmeshl.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotmeshl.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotmeshl.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
# output if fort.71
echo "preparing files for coast plot"
cp ../input/divaparam/coast.cont.$lev fort.66
../../bin/forgnuplotcoastfilled.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotcoastfilled.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotcoastfilled.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
# output is fort.67
#cat dvcoastlineheader > diva_coastlinefilled
#cat dvcoastlinetailer>> diva_coastlinefilled
rm -f fort.19
rm -f fort.21
echo preparing RL field
if [ -f ../input/divaparam/RLinfo."$var".$lev ];then
 cp -f ../input/divaparam/RLinfo."$var".$lev  fort.21
else
 if [ -f ../input/divaparam/RLinfo.$lev ];then
  cp -f ../input/divaparam/RLinfo.$lev fort.21
 else
  if [ -f ../input/divaparam/RLinfo.dat ];then
   cp -f ../input/divaparam/RLinfo.dat fort.21
  fi
 fi
fi
if [ -f ./fort.21 ];then
 if [ -f ../input/divaparam/RL."$var".$lev ];then
  cp -f ../input/divaparam/RL."$var".$lev fort.20
 else
  if [ -f ../input/divaparam/RL.$lev ];then
   cp -f ../input/divaparam/RL.$lev fort.20
  else
   if [ -f ../input/divaparam/RL.dat ];then
    cp -f ../input/divaparam/RL.dat fort.20
   fi
  fi
 fi

if [ "$smooth" == "1" ]
then
../../bin/forgnuplotanalysissmooth.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotanalysissmooth.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotanalysissmooth.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
else
../../bin/forgnuplotanalysis.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotanalysis.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotanalysis.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
fi
# output is fort.68
mv fort.68 fort.72
fi
rm -f fort.19
if [ -f ../input/divadata/"$var"'.'$lev'.DATABINS' ] 
then
echo preparing DATABINS field
cp ../input/divadata/"$var"'.'$lev'.DATABINS' fort.20
cp ../input/divadata/"$var"'.'$lev'.DATABINSinfo' fort.21
../../bin/forgnuplotanalysis.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotanalysis.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotanalysis.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
# output is fort.68
mv fort.68 fort.73
fi
rm -f fort.19
if [ -f ../output/3Danalysis/Fields/"$var"'.'$lev'.anl' ] 
then
echo preparing standard deviation field
cp '../output/3Danalysis/Fields/'"$var"'.'$lev'.anl' fort.20
cp ../output/3Danalysis/Fields/GridInfo.dat fort.21
../../bin/forgnuplotanalysis.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotanalysis.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotanalysis.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
# output is fort.68
mv fort.68 fort.79
fi
###if [ -f ../input/Uvel.dat ] 
###then
###echo preparing velocity field
###cp ../input/Uvel.dat fort.30
###cp ../input/Vvel.dat fort.31
###cp ../input/UVinfo.dat fort.32
###../../bin/forgnuplotuv.a >> ../output/diva.log
###if [ $? -ne 0 ];then
###echo ' '
###echo --------------------------------------------
###echo A problem was encountered during execution !
###echo          dv3Dgnu      forgnuplotuv.a
###echo Check execution track
###echo --------------------------------------------
###echo ' ' >> ../output/diva.log
###echo -------------------------------------------- >> ../output/diva.log
###echo A problem was encountered during execution ! >> ../output/diva.log
###echo          dv3Dgnu      forgnuplotuv.a  >> ../output/diva.log
###echo Check execution track >> ../output/diva.log
###echo -------------------------------------------- >> ../output/diva.log
###fi
# output is fort.55
###fi
echo ' ' > fort.99
cat ../input/divadata/"$var".$lev >> fort.99
awk 'NF<2{printf"\n"}{print}' < fort.71 > fort.11
echo "preparing files for analysis and error plot"
rm -f fort.19
if [ -f ../output/3Danalysis/Fields/"$var"'.'$lev'.error' ] 
then
echo preparing error field
cp ../output/3Danalysis/Fields/"$var"'.'$lev'.error' fort.19
fi
cp ../output/3Danalysis/Fields/"$var"'.'$lev'.anl' fort.20
cp ../output/3Danalysis/Fields/GridInfo.dat fort.21
#../../bin/forgnuplotanalysis.a >> ../output/diva.log
if [ "$smooth" == "1" ]
then
../../bin/forgnuplotanalysissmooth.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotanalysissmooth.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotanalysissmooth.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
else
../../bin/forgnuplotanalysis.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          dv3Dgnu      forgnuplotanalysis.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          dv3Dgnu      forgnuplotanalysis.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
fi
# output is fort.68
mv fort.41 dvanalysisrange
mv fort.40 longref.dat.default
jj=$(cat ../output/outliersbis.normalized.dat | wc -l)
let jj=$jj-4
if [ "$jj" -ge "0" ]
then
head -$jj ../output/outliersbis.normalized.dat | tac > fort.43
fi
if [ "$#" == "2" ]
then 

echo ' 111111 dolar3 dolar4 = ' $gmin $gmax

. divaplotall $gmin $gmax
else
echo ' 222222 dolar3 dolar4 = ' $gmin $gmax

. divaplotall
fi
cd ..
