#!/bin/bash



echo //////////////////////////////////////////////////
echo           Going to compute covariances sums
echo           called when ispec minus 116
echo //////////////////////////////////////////////////
echo ' ' 


if [ -f ./input/data.dat ] 
then 
cp ./input/data.dat ./divawork/fort.79
head -1 ./meshgenwork/fort.22 > ./divawork/bidon
{
read nnn xxx yyy
} < ./divawork/bidon
rm ./divawork/bidon
echo $xxx $yyy 1 1.E-10 > ./divawork/fort.44
else
echo Need to provide data.dat in ./input !
fi

# put into valatxy the list of points for the sum
# need to put also weights??? (three columns)


cd ./divawork
rm -f fort.59
rm -f fort.61
wc -l ../input/integrationpoints.dat > fort.55
cp ../input/integrationpoints.dat fort.45
wc -l ../input/data.dat >> fort.55
echo coord 1 > ./fort.10
echo $icoordchange >> ./fort.10
echo mathpr 1 >> ./fort.10
echo 2 >> ./fort.10
echo 0 >> ./fort.10
echo 2 >> ./fort.10
echo topolo 1 >> ./fort.10
echo $nnt1 >> ./fort.10
echo $nnint >> ./fort.10
echo $nelt >> ./fort.10
echo datapr 1 >> ./fort.10
echo 0 >> ./fort.10
if [ "$itcs" != "0" ] 
then 
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo  Module constraint activated
echo $itcs
echo constr 1 >> ./fort.10
echo $itcs >> ./fort.10

echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
fi

echo solver 1 >> ./fort.10
echo 0 >> ./fort.10
echo stores 1 >> ./fort.10
echo 3 >> ./fort.10
echo VARBAK: $varbak
if [ "$varbak" != "0" ]
then
if [ "$ispec" != "0" ]
then
echo errors will be calculated
echo covar 1 >> ./fort.10
echo $ispec >> ./fort.10
fi
fi


echo stopex >> ./fort.10


echo $lc 1 4 $xi | ../../bin/calcmu.a

#execute diva


let NREA=$NREA+3*$NDATA
let NREA=$NREA+$NDDLT
let NINT=$NINT+$NDATA





echo $NINT $NREA | ../../bin/diva.a 


let NREA=$NREA-3*$NDATA
let NREA=$NREA-$NDDLT
let NINT=$NINT-$NDATA

echo now saving sums
cp fort.64 ../output/Pfsumum.dat
cp fort.65 ../output/Csum.dat
