#!/bin/bash



echo //////////////////////////////////////////////////
echo           Going to compute covariances
echo //////////////////////////////////////////////////
echo ' ' 


if [ -f ./input/data.dat ] 
then 
cp ./input/data.dat ./divawork/fort.45
head -1 ./meshgenwork/fort.22 > ./divawork/bidon
{
read nnn xxx yyy
} < ./divawork/bidon
rm ./divawork/bidon
echo $xxx $yyy 1 1.E-10 > ./divawork/fort.44
else
echo Need to provide data.dat in ./input !
fi

cd ./divawork
rm -f fort.59
rm -f fort.61
wc -l fort.45 > fort.55
echo coord 1 > ./fort.10
echo $icoordchange >> ./fort.10
echo mathpr 1 >> ./fort.10
echo 2 >> ./fort.10
echo 0 >> ./fort.10
echo 2 >> ./fort.10
echo topolo 1 >> ./fort.10
echo $nnt1 >> ./fort.10
echo $nnint >> ./fort.10
echo $nelt >> ./fort.10
echo datapr 1 >> ./fort.10
echo 0 >> ./fort.10
if [ "$itcs" != "0" ] 
then 
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo  Module constraint activated
echo $itcs
echo constr 1 >> ./fort.10
echo $itcs >> ./fort.10

echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
fi

echo solver 1 >> ./fort.10
echo 0 >> ./fort.10
echo stores 1 >> ./fort.10
echo 3 >> ./fort.10
echo VARBAK: $varbak
if [ "$varbak" != "0" ]
then
if [ "$ispec" != "0" ]
then
echo errors will be calculated
echo covar 1 >> ./fort.10
echo $ispec >> ./fort.10
fi
fi


echo stopex >> ./fort.10


echo $lc 1 4 $xi | ../../bin/calcmu.a

#execute diva


let NREA=$NREA+3*$NDATA
let NREA=$NREA+$NDDLT
let NINT=$NINT+$NDATA




mkdir -p sub
rm -f fort.61
echo $ipipe > fort.59
cd sub
rm -f fort.*
cp ../fort.* .

cd ..
rm -f divapipe
if [ "$ipipe" == "1" ] 
then
#mknod divapipe p
rm -f dvping
mknod dvping p
rm -f dvpong
mknod dvpong p

sleep 1
cd sub
echo Launching a detached diva.a
echo $NINT $NREA | ../../../bin/diva.a &

else

cd sub
echo Launching a sequential diva.a
echo $NINT $NREA | ../../../bin/diva.a 

fi

let NREA=$NREA-3*$NDATA
let NREA=$NREA-$NDDLT
let NINT=$NINT-$NDATA

cd ..
cd ..
echo ==============================================
echo ----------------------------------------------
echo Analysed for covariance is launched
echo Now will start diva for fields and errors
echo ----------------------------------------------
echo ==============================================
