#!/bin/bash

cd divawork
cp ../input/data.dat fort.88
cp ../output/fieldatdatapoint.anl fort.89
../../bin/detrend.a
cp fort.90 ../input/data.detrend.dat
cp fort.97 ../output/trends.dat



cd ..

echo ' '








