#!/bin/bash
#
#####################################################
#
#####################################################
#

mkdir -p ./3DWORK

FILENAME=./input/takeout.coord

if [ -f "$FILENAME" ]
then

echo Going  to modify gebco.topo

nblines=`cat './input/takeout.coord' |wc -l` 
ln=1
#
  Fileinf=$FILENAME
{
#
while [ $ln -le $nblines ]
do
read location
echo location nbr $ln : $location
echo $location > ./3DWORK/fort.44

cd ./3DWORK
../../bin/gebprep.a
cd ..

mv ./input/modif_topo.gebco  ./input/topo.gebco

let ln=$ln+1
done
} < $Fileinf
#
else
echo Missing file $FILENAME
echo Please provide file $FILENAME
exit
fi

#
