#!/bin/bash
export LC_ALL=C
echo here you can select only a subset of grid points for integretion
if [ -f ./input/integrationpoints.dat ]
then
echo will try to make subselectio
# Select only points where analysis ($3>0) is positive or coordinates in a box 
# awk '{ if ($1 > -4 && $1 < 4 && $2 > -4 && $2 < 4 ) print $1,$2,$3,$4}' ./input/integrationpoints.dat > bidon
# mv bidon ./input/integrationpoints.dat
else
echo Sorry, no list available
exit
fi