#!/bin/bash

echo here you can select only a subset of grid points for integretion

if [ -f ./input/integrationpoints.dat ]
then
echo will try to make subselectio
# Select only points where analysis is positive 
# awk '{ if ($3 > 0) print $1,$2,$3}' > bidon
# mv bidon ./input/integrationpoints.dat
else
echo Sorry, no list available
exit
fi