#!/bin/bash




cd divawork
cp ../input/data.dat.ori fort.20
nbcol=$(head -1 fort.20 | wc -w)
echo $2 $nbcol
ndata=$(cat fort.20 | wc -l)
echo Subsampling of $1 from $ndata data points
if [ "$1" -ge "$ndata" ] 
then
echo subsample size too large
else


if [ -f ../../output/diva.log ] ; then
 cp -f ../../output/diva.log .
fi

echo $1 $ndata $2 $nbcol  | ../../bin/subsampling.a >> diva.log

if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo                subsampling.a
echo Check execution track
echo --------------------------------------------

echo ' ' >> diva.log
echo -------------------------------------------- >> diva.log
echo A problem was encountered during execution ! >> diva.log
echo                subsampling.a  >> diva.log
echo Check execution track >> diva.log
echo -------------------------------------------- >> diva.log
fi

 cp -f diva.log ../output/.

fi
mv -f fort.44 ../input/data.dat
mv -f fort.45 ../input/valatxy.coord
rm -f fort.20
echo New data and reference data ready
cd ..
