#!/bin/bash




cd divawork
cp ../input/data.dat.ori fort.20
nbcol=$(head -1 fort.20 | wc -w)
echo $2 $nbcol
ndata=$(cat fort.20 | wc -l)
echo Subsampling of $1 from $ndata data points
if [ "$1" -ge "$ndata" ] 
then
echo subsample size too large
else
echo $1 $ndata $2 $nbcol  | ../../bin/subsampling.a
fi
mv -f fort.44 ../input/data.dat
mv -f fort.45 ../input/valatxy.coord
rm -f fort.20
echo New data and reference data ready
cd ..
