#!/bin/bash
cd divawork
if [ -f ../output/diva.log ] ; then
 cp -f ../output/diva.log .
fi
cp ../input/valatxy.coord fort.20
cp ../output/valatxyascii.anl fort.21
VALEX=$(head -22 ../input/param.par | tail -1)
echo $VALEX | ../../bin/cverror.a >> diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo                cverror.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> diva.log
echo -------------------------------------------- >> diva.log
echo A problem was encountered during execution ! >> diva.log
echo                cverror.a  >> diva.log
echo Check execution track >> diva.log
echo -------------------------------------------- >> diva.log
fi
echo Exclusion value used $VALEX
cat fort.22 >> crossval.dat
 cp -f diva.log ../output/.
cd ..
