#!/bin/bash
export LC_ALL=C

source divalogging

infolog -- | tee -a $divalog
infolog 'Mesh generation' | tee -a $divalog
infolog -- | tee -a $divalog

divaecho ' '
divaecho "Mesh logs written in ${divameshlog}"
divaecho ' '

if [ -f ./input/coast.cont ]; then
  cp ./input/coast.cont ./meshgenwork/fort.10
else
  errorlog "No file coast.cont in ./input" | tee -a $divameshlog $divalog
  exit 1
fi
isdens=0
if [ -f ./input/coast.cont.dens ]; then
  divaecho "There is a density file for the mesh" | tee -a $divameshlog
  cp -v ./input/coast.cont.dens ./meshgenwork/fort.12
  isdens=1
fi

##echo $isdens
if [ -f ./input/param.par ]; then
  divaecho "Reading parameters" | tee -a $divameshlog
else
  divaerror "No file param.par in ./input/" | tee -a $divameshlog $divalog
  exit 1
fi
Filepar=./input/param.par
{
read linecomment
read lc
read linecomment
read icoordchange
read linecomment
read ispec
read linecomment
read ireg
read linecomment
read xori
read linecomment
read yori
read linecomment
read dx
read linecomment
read dy
read linecomment
read nx
read linecomment
read ny
read linecomment
read valex
read linecomment
read snr
read linecomment
read varbak
} < $Filepar
#param.par
#creation of files for mesh generation
#creation of file fort.11 for gener.a
#rm fort.11
#exec 11<>fort.11
#echo 0 > ./meshgenwork/fort.11
#echo $lc >> ./meshgenwork/fort.11
#echo 1.5 >> ./meshgenwork/fort.11
#echo 5 >> ./meshgenwork/fort.11
#exec 11>&-

rm -f fort.11

##replaced by Awk command
#
#echo $isdens $lc | ../bin/lcelem.a
#mv fort.11 ./meshgenwork/fort.11
#echo 1.5 >> ./meshgenwork/fort.11
#echo 5 >> ./meshgenwork/fort.11

echo $isdens > ./meshgenwork/fort.11
echo $(echo $lc | awk '{print ($1/5.)}') >> ./meshgenwork/fort.11
echo 1.5 >> ./meshgenwork/fort.11
echo 5 >> ./meshgenwork/fort.11


#exec 11>&-
#generation of the mesh
cd ./meshgenwork

divaecho ////////////////////////////////////////// >> $divalog
divaecho '           Mesh generation (generopt)' >> $divalog
divaecho ////////////////////////////////////////// >> $divalog
divaecho ' '  >> $divalog
echo $icoordchange | ../../bin/generopt.a >> $divameshlog
if [ $? -ne 0 ]; then
  divaecho ' ' | tee -a $divalog $divameshlog
  divaecho -------------------------------------------- | tee -a $divalog $divameshlog
  divaecho A problem was encountered during execution ! | tee -a $divalog $divameshlog
  divaecho          divamesh      generopt.a  | tee -a $divalog $divameshlog
  divaecho Check execution track | tee -a $divalog $divameshlog
  divaecho -------------------------------------------- | tee -a $divalog $divameshlog
fi
File23=./fort.23
{
read nnt1
read nnint
read nelt
} < $File23
#output of info for mesh visualisation with meshvisu.m
divaecho ' '
divaecho Copying output files for visualisation >> $divameshlog
divaecho in directory ./output/meshvisu/  >> $divameshlog
cp fort.10 ../output/meshvisu/
cp fort.22 ../output/meshvisu/
cp fort.23 ../output/meshvisu/

#exec 23<>fort.23
#read  nnt1 nnint nelt <&3
#exec 23>&-
cd ..
divaecho ---------------   | tee -a $divameshlog
divaecho Mesh is created   | tee -a $divameshlog
divaecho ---------------   | tee -a $divameshlog
divaecho ' '   | tee -a $divameshlog
