#!/bin/bash
export LC_ALL=C

source divalogging

infolog -- | tee -a $divalog
infolog 'Mesh generation' | tee -a $divalog
infolog -- | tee -a $divalog



echo "Now testing divacalc"

inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
datafile=${inputdir}'data.dat'
paramfile=${inputdir}'param.par'

./divaclean

##echo ${inputdir}
infolog --
infolog 'Running a simple test'
infolog --

divaecho '1. creating data file'
divaecho ' '

echo '0.3 0.3 1' > ${datafile}
echo '0.55 0.9 -1' >> ${datafile}
echo '0.85 0.1 0.2' >> ${datafile}

divaecho '2. creating contour file'
divaecho ' '

echo 2 > ${contfile}
echo 4 >> ${contfile}
echo -0.001 -0.001 >> ${contfile}
echo 1.001 -0.001 >> ${contfile}
echo 1.001 1.001 >> ${contfile}
echo -0.001 1.001 >> ${contfile}
echo 4 >> ${contfile}
echo 0.401 0.201 >> ${contfile}
echo 0.401 0.801 >> ${contfile}
echo 0.601 0.801 >> ${contfile}
echo 0.601 0.201 >> ${contfile}


divaecho '3. creating parameter file'
divaecho ' '

echo '# Correlation Length lc' > ${paramfile}
echo '0.2' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '11' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '51' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '51' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

./divamesh

./divacalc

divaecho ' '
divaecho 'Check the results in'
divaecho './ouput/ghertonetcdf/results.nc (netcdf)'


divaecho 'Now checking if you have gawk or nawk'
whichawk=$(echo 0 | awk '{if (PROCINFO["version"])  print "1"; else print "0"; }')
echo $whichawk
if [ "$whichawk" != "1" ]
then
  warnlog !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  warnlog !!! PLEASE INSTALL GAWK !!!!!!!!!!!!
  warnlog !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  sleep 1
else
  divaecho gawk is present
fi

divaecho "Finally testing pipes needed for exact error calculations"
divaecho "If the program hangs it means pipes are not supported"
divaecho "In this case you need to adapt parameter ipipe to ipipe=0 in divacalc"
cd ../src/Fortran/Pipetest
./pipetest

cd ../../../divastripped

divaecho

divaecho "Now checking if dos2unix is present..."
rm -f testdos2unixbis.txt
echo "test" > testdos2unix.txt
dos2unix -n testdos2unix.txt testdos2unixbis.txt > /dev/null 2>&1
if [ -s testdos2unixbis.txt ]
then
  divaecho "...dos2unix is present."
else
  divaecho "...dos2unix is absent !"
  divaecho
  warnlog !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  warnlog !!! PLEASE INSTALL DOS2UNIX !!!!!!!!!!!!!!!!
  warnlog !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  sleep 1
fi
rm -f testdos2unix.txt
rm -f testdos2unixbis.txt
echo

divaecho "Now checking if bc is present..."
test=$(echo '1+1' | bc -l)
if [ "$test" == "2" ]
then
  divaecho "...bc is present."
else
  divaecho "...bc is absent !"
  divaecho
  warnlog !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  warnlog !!! PLEASE INSTALL BC !!!!!!!!!!!!!!!!
  warnlog !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  sleep 1
fi
