#!/bin/bash

source divalogging

infolog --			| tee -a $divalog
infolog 'Diva test on a big data set'	| tee -a $divalog
infolog --			| tee -a $divalog

if [ "$#" == "1" ]
then
  ndata=$1
else
  ndata='15000'
fi

divaecho ' '
divaecho 'Now testing divacalc with' ${ndata} ' data points and a fine mesh'
divaecho ' '


inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
datafile=${inputdir}'data.dat'
paramfile=${inputdir}'param.par'

# Add divaclean to avoid working on old files!
divaclean

##echo ${inputdir}
infolog //////////////////////////////////////////////////
infolog 'Running a heavy test'
infolog //////////////////////////////////////////////////

divaecho '1. creating huge data file, be patient'
divaecho ' '

echo $ndata | awk '{NP=$1;{for (i = 1; i <= NP; i++) {x=-1+2*rand();y=-1+2*rand();z=sin(3.14*x)*cos(3.14*y)*exp(x+y);print x,y,z,1}}}' > ${datafile}

divaecho '2. creating contour file'
divaecho ' '

echo 2 > ${contfile}
echo 4 >> ${contfile}
echo -1 -1 >> ${contfile}
echo 1 -1 >> ${contfile}
echo 1  1 >> ${contfile}
echo -1 1 >> ${contfile}
echo 4 >> ${contfile}
echo 0.4 0.2 >> ${contfile}
echo 0.4 0.8 >> ${contfile}
echo 0.6 0.8 >> ${contfile}
echo 0.6 0.2 >> ${contfile}


divaecho '3. creating parameter file'
divaecho ' '

echo '# Correlation Length lc' > ${paramfile}
echo '0.07' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '11' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '-1' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '-1' >> ${paramfile}
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '101' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '101' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

timeinit=$(date +%s.%N)

divamesh

timeinterm=$(date +%s.%N)

echo 'Now into the calculation itself'

divacalc

infolog 'Check the results in'
infolog './ouput/ghertonetcdf/results.nc (netcdf)'

timeend=$(date +%s.%N)

timemesh=$(echo ${timeinterm} ${timeinit} | awk '{print ($1-$2)}')
timecalc=$(echo ${timeend} ${timeinterm} | awk '{print ($1-$2)}')
timerun=$(echo ${timeend} ${timeinit} | awk '{print ($1-$2)}')

infolog 'Time for mesh creation:  ' $timemesh ' s'
infolog 'Time for calculation:    ' $timecalc ' s'
infolog 'Total time for analysis: ' $timerun ' s'
