#!/bin/bash

source divalogging

infolog --
infolog "          Cross Validation"
infolog --

divaecho ' '
divaecho "CVrand logs written in ${divacvrandlog}"
divaecho ' '

divaecho "///////////////////////////////////////////" > ${divacvrandlog}
divaecho "          Cross Validation" >> ${divacvrandlog}
divaecho "///////////////////////////////////////////" >> ${divacvrandlog}
divaecho ' ' >> ${divacvrandlog}

nddd=$(cat ./input/data.dat | wc -l)
if [ $# -eq "0" ]; then
  warnline  | tee -a ${divacvrandlog}
  warnlog "Need at least two parameters for divacv:" | tee -a ${divacvrandlog}
  warnlog "number of points for cross references" | tee -a ${divacvrandlog}
  warnlog "number of repeated data removal" | tee -a ${divacvrandlog}
  warnline | tee -a ${divacvrandlog}
else
  if [ "$1" == "-r" ]; then
    warnlog "Please put option -r after the two numbers" | tee -a ${divacvrandlog}
  else
    let nppp=$(($1*$2))
    if [ "$nppp" -gt "$nddd" ]; then
      warnline | tee -a ${divacvrandlog}
      warnlog "Your statistics will not be independant" | tee -a ${divacvrandlog}
      warnlog "$1 times $2 = $nppp is larger than $nddd"| tee -a ${divacvrandlog}
      warnlog "Stopping" >> ${divacvrandlog} | tee -a $divacvrandlog
      warnline | tee -a  ${divacvrandlog}
    else
      cp ./input/param.par  ./input/param.par.ori
      cp ./input/data.dat  ./input/data.dat.ori
      rm -f ./input/valatxy.coord.ori
      mv -f ./input/valatxy.coord ./input/valatxy.coord.ori
      rm -f ./output/gcv.dat
      if [ -f ./input/gcvsampling.dat ]; then
        #Create mesh once
        if [ -f ./meshgenwork/fort.22 ]; then
          warnline >> ${divacvrandlog}
          warnlog "Mesh files aready exist, hope they are correct: otherwise exectute divamesh" >> ${divacvrandlog}
          warnline >> ${divacvrandlog}
        else
          ./divamesh
          cat  ${divacvrandlog} ./output/divamesh.log > bidon
          mv bidon ${divacvrandlog}
        fi
      else
        errorline | tee -a $divacvrandlog
        errorlog "Need to provide gcvsampling.dat in ./input !" | tee -a ${divacvrandlog}
        errorline | tee -a $divacvrandlog
      fi
      for gcv in `cat ./input/gcvsampling.dat`
      do
        divaecho "Working with $gcv" | tee -a ${divacvrandlog}
        #For a given subsample size
        isize=$1
        ijm=0
        N=$2
        rm -f ./divawork/cverror.dat
        rm -f ./divawork/cvdatavar.dat
        #Repeat N times the estimates
        while [ "$ijm" -lt "$N" ]
        do
          # Extract a random subsample
          ./dvsample $isize $ijm
          let ijm=$(($ijm+1))
          #head -17 ./input/param.par.ori > bidon
          head -5 ./input/param.par.ori > bidon
          echo 0 >> bidon
          head -17 ./input/param.par.ori | tail -11 >> bidon
          echo 1 >> bidon
          echo   >> bidon
          echo 1 >> bidon
          echo   >> bidon
          echo -99 >> bidon
          echo >> bidon
          echo $gcv >> bidon
          #tail -2 ./input/param.par.ori >> bidon
          # no error field
          echo >> bidon
          echo 0 >> bidon
          mv bidon ./input/param.par
          ./divacalc
          cat  ${divacvrandlog} $divacalclog > bidon
          mv bidon ${divacvrandlog}

          #now calculate errors from differences in valatxy.coord and fieldatxyascii.anl
          # only in real points
          # with valex=-99
          # and cat them into a file
          cd divawork
          cp ../input/valatxy.coord fort.20
          cp ../output/valatxyascii.anl fort.21

          echo -99 | ../../bin/cverror.a >> $divalog
          if [ $? -ne 0 ];  then
            errorlog ' ' | tee -a ${divacvrandlog} ${divalog}
            errorline | tee -a ${divacvrandlog} ${divalog}
            errorlog "A problem was encountered during execution !" | tee -a ${divacvrandlog} ${divalog}
            errorlog "        divacvrand       cverror.a" | tee -a ${divacvrandlog} ${divalog}
            errorlog "Check execution track" | tee -a ${divacvrandlog} ${divalog}
            errorline  | tee -a ${divacvrandlog} ${divalog}
          fi
          cat fort.22 >> cverror.dat
          cat fort.33 >> cvdatavar.dat
          cd ..
          # End loops
          #
        done
        cd divawork
        cp cverror.dat fort.20
        cp cvdatavar.dat fort.21
        #if [ -f ../output/diva.log ] ; then
        # cp -f ../output/diva.log .
        #fi
        echo $gcv | ../../bin/cvtotalerror.a >> $divalog
        if [ $? -ne 0 ]; then
          errorlog ' ' | tee -a ${divacvrandlog} ${divalog}
          errorline | tee -a ${divacvrandlog} ${divalog}
          errorlog "A problem was encountered during execution !" | tee -a ${divacvrandlog} ${divalog}
          errorlog "         divacvrand      cvtotalerror.a" | tee -a ${divacvrandlog} ${divalog}
          errorlog "Check execution track" | tee -a ${divacvrandlog} ${divalog}
          errorline | tee -a ${divacvrandlog} ${divalog}
        fi
        cat fort.22 >> ../output/gcv.dat
        cd ..
        #Next cv test
      done
      mv -f ./input/param.par.ori ./input/param.par
      mv -f ./input/data.dat.ori ./input/data.dat
      mv -f ./input/valatxy.coord.ori ./input/valatxy.coord
      cp ./output/gcv.dat ./divawork/fort.11
      cd divawork
      divaecho "Looking for the minimum of GCV"  >> ${divacvrandlog}
      divaecho ' ' 			         >> ${divacvrandlog}
      if [ -f ../input/gcvsampling.dat ]; then
        ../../bin/findmin.a >> $divalog
        if [ $? -ne 0 ]; then
          errorline ' '
          errorlog "--------------------------------------------" | tee -a ${divacvrandlog}
          errorlog "A problem was encountered during execution !" | tee -a ${divacvrandlog}
          errorlog "         divacvrand      findmin.a" | tee -a ${divacvrandlog}
          errorlog "Check execution track" | tee -a ${divacvrandlog}
          errorline | tee -a ${divacvrandlog}
        fi
        divaecho ' ' >> ${divacvrandlog}
        divaecho "divacvrand:----------------------------------------" >> ${divacvrandlog}
        divaecho "divacvrand:CV finished" >> ${divacvrandlog}
        divaecho "divacvrand:Results written in ./output/gcvsnvar.dat" >> ${divacvrandlog}
        divaecho "divacvrand:----------------------------------------" >> ${divacvrandlog}
      else
        errorlog ' ' | tee -a ${divacvrandlog} ${divalog}
        errorline | tee -a ${divacvrandlog} ${divalog}
        errorlog "A problem was encountered during execution !" | tee -a ${divacvrandlog} ${divalog}
        errorlog "Check execution track" | tee -a ${divacvrandlog} ${divalog}
        errorline | tee -a ${divacvrandlog} ${divalog}
      fi
      mv fort.12 ../output/gcvsnvar.dat
      divaecho "-----------------------------------------------------" >> ${divacvrandlog}
      divaecho "Creating adapted param.par in ./output/param.par.gcv " >> ${divacvrandlog}
      divaecho "-----------------------------------------------------" >> ${divacvrandlog}
      head -23 ../input/param.par  > ../output/param.par.gcv
      head -2 ../output/gcvsnvar.dat | tail -1 >> ../output/param.par.gcv
      head -25 ../input/param.par | tail -1 >> ../output/param.par.gcv
      head -4 ../output/gcvsnvar.dat  | tail -1 >> ../output/param.par.gcv
      if [ "$3" == "-r" ]; then
        divaecho "=======================================================" tee -a ${divacvrandlog}
        divaecho "Replacing SNR by new value from CV in param.par" tee -a ${divacvrandlog}
        cd ..
        cp -v ./input/param.par ./input/param.par.old
        cp -v ./output/param.par.gcv ./input/param.par
        divaecho "======================================================="
      else
        cd ..
      fi
    fi
  fi
fi
