#!/bin/bash

source divalogging

infolog --
infolog "Contour generation"
infolog --

divaecho ///////////////////////////////// > ${divacontlog}
divaecho        Contour generation >> ${divacontlog}
divaecho ///////////////////////////////// >> ${divacontlog}
divaecho ' ' >>${divacontlog}

divaecho Cleaning up old files >> ${divacontlog}
rm -f ./divawork/fort.10
rm -f ./divawork/fort.11
rm -f ./divawork/fort.12
rm -f ./divawork/fort.13
echo Cleaning finished   >> ${divacontlog}
if [ -f ./input/TopoInfo.dat ]; then
  cat ./input/TopoInfo.dat
  cp ./input/TopoInfo.dat ./divawork/fort.10
else
  errorline | tee -a ${divacontlog}
  errorlog Need to provide TopoInfo.dat in ./input ! | tee -a ${divacontlog}
  errorline | tee -a ${divacontlog}
fi
if [ -f ./input/topo.grd ]; then
  cp ./input/topo.grd ./divawork/fort.12
else
  errorline | tee -a ${divacontlog}
  errorlog "Need to provide topo.grd in ./input !" | tee -a ${divacontlog}
  errorline | tee -a ${divacontlog}
fi
if [ -f ./input/contour.depth ]
then
  cp ./input/contour.depth ./divawork/fort.13
else
  warnline | tee -a ${divacontlog}
  warnline Need to provide contour.depth in ./input ! | tee -a ${divacontlog}
  warnline Assuming zero depth contour is asked | tee -a ${divacontlog}
fi
divaecho Contour creation >>${divacontlog}
cd ./divawork

divaecho '//////////////////////////////////////////' >> ${divalog}
divaecho '           Generating contour files' >> ${divalog}
divaecho '//////////////////////////////////////////' >> ${divalog}

../../bin/contourgen.a >> ../output/diva.log
if [ $? -ne 0 ]; then
  errorline | tee -a ${divalog}
  errorlog  'A problem was encountered during execution !' | tee -a ${divalog}
  errorlog  '     divacont:   contourgen.a' | tee -a ${divalog}
  errorlog' Check execution track' | tee -a ${divalog}
  errorline | tee -a ${divalog}
fi
cd ..
if [ -f ./divawork/coast.cont ]; then
  divaecho Copying coast files in output >>${divacontlog}
  cp -v ./divawork/coast.cont*  ./output
  rm -f ./divawork/fort.10
  rm -f ./divawork/fort.11
  divaecho '----------------' >> ${divacontlog}
  divaecho 'Contours created'  >> ${divacontlog}
  divaecho '----------------' >> ${divacontlog}
  if [ "$1" == "-r" ]
  then
    divaecho 'Moving coast.cont into ./input directory' >>${divacontlog}
    cp -v ./output/coast.cont* ./input
  fi
else
  errorline | tee -a ${divacontlog}
  errorlog '--------------------------------------------' | tee -a ${divacontlog}
  errorlog 'A problem was encountered during execution !' | tee -a ${divacontlog}
  errorlog 'Check execution track >>${divacontlog}'  | tee -a ${divacontlog}
  errorline | tee -a ${divacontlog}
fi

infolog --
infolog "End contour generation"
infolog --
