#!/bin/bash
echo //////////////////////////////////////////////////
echo             Looking for outliers
echo //////////////////////////////////////////////////
echo ' '
divaqcbislog=./output/divaqcbis.log
echo ////////////////////////////////////////////////// > $divaqcbislog
echo             Looking for outliers >> $divaqcbislog
echo ////////////////////////////////////////////////// >> $divaqcbislog
echo ' '

if [ -f ./input/data.dat ]
then 
cp ./input/data.dat ./divawork/fort.44
else
echo Need to provide data.dat in ./input
fi
Filepar=./input/param.par
{
read linecomment
read lc
read linecomment
read icoordchange
read linecomment
read ispec
read linecomment
read ireg
read linecomment
read xori
read linecomment
read yori
read linecomment
read dx
read linecomment
read dy
read linecomment
read nx
read linecomment
read ny
read linecomment
read valex
read linecomment
read snr
read linecomment
read varbak
} < $Filepar
cd divawork
nbccol=$(head -n 1 ./fort.44 | wc -w)
GGGGG=../output/gcvval.dat
{
read GCVVAL BBBBBB TRACEA tutu
}<$GGGGG
echo $TRACEA  >> ../$divaqcbislog

echo $lc $snr $nbccol $GCVVAL $TRACEA $varbak | ../../bin/calcestbis.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          divaqcbis      calcestbis.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../$divaqcbislog
echo -------------------------------------------- >> ../$divaqcbislog
echo A problem was encountered during execution ! >> ../$divaqcbislog
echo          divaqcbis      calcestbis.a >> ../$divaqcbislog
echo Check execution track >> ../$divaqcbislog
echo -------------------------------------------- >> ../$divaqcbislog
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          divaqcbis      calcestbis.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
#output of results to user
cp -v fort.76 ../output/expectederroratdatapointbis.anl

echo ' ' >> ../$divaqcbislog
echo Looking for outliers >> ../$divaqcbislog
echo ' '
echo Looking for outliers
echo ' '

if [ -f fort.71 ] 
then
echo Using fort.71 found in divawork
else
echo Try using fieldatdatapoint.anl
if [ -f ./output/fieldatdatapoint.anl ]
then
cp ../output/fieldatdatapoint.anl fort.71
else
echo Need to execute divacalc before
fi
fi
echo $valex | ../../bin/lookforoutliers.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo          divaqcbis      lookforoutliers.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../$divaqcbislog
echo -------------------------------------------- >> ../$divaqcbislog
echo A problem was encountered during execution ! >> ../$divaqcbislog
echo          divaqcbis      lookforoutliers.a >> ../$divaqcbislog
echo Check execution track >> ../$divaqcbislog
echo -------------------------------------------- >> ../$divaqcbislog
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo          divaqcbis      lookforoutliers.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi
echo ' '
echo Copying outlier lists
echo ' '
if [ -f fort.66 ]
then
mv -v fort.66 ../output/outliersbis.dat
mv -v fort.67 ../output/outliersbis.normalized.dat
else
echo ' ' >> ../$divaqcbislog
echo -------------------------------------------- >> ../$divaqcbislog
echo A problem was encountered during execution ! >> ../$divaqcbislog
echo Check execution track >> ../$divaqcbislog
echo -------------------------------------------- >> ../$divaqcbislog
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo Check execution track
echo --------------------------------------------
fi
cd ..
dvvariance 2
echo ' ' >> $divaqcbislog
echo -------------------------- >> $divaqcbislog
echo Outlier detection finished >> $divaqcbislog
echo -------------------------- >> $divaqcbislog
echo ' '
echo --------------------------
echo Outlier detection finished
echo --------------------------
