#!/bin/bash

source divalogging

infolog --
infolog "       Cross Validation"
infolog --

divaecho ' '
divaecho "///////////////////////////////////////////" > $divacvlog
divaecho "       Cross Validation" >> $divacvlog
divaecho "///////////////////////////////////////////" >> $divacvlog
divaecho ' ' >> $divacvlog

cp ./input/param.par  ./input/param.par.ori
rm -f ./input/valatxy.coord.ori
if [ -f ./input/valatxy.coord ]; then
  mv -f ./input/valatxy.coord ./input/valatxy.coord.ori
fi

rm -f ./output/gcv.dat
if [ -f ./input/gcvsampling.dat ]; then
  #Create mesh once
  if [ -f ./meshgenwork/fort.22 ]; then 
    warnline >> $divacvlog
    warnlog "Mesh files already exist, hope they are correct: otherwise execute divamesh" >> $divacvlog
    warnline >> $divacvlog
  else
    divamesh
    cat  $divacvlog $divameshlog > bidon
    mv bidon $divacvlog
  fi
else
  errorline | tee -a $divacvlog
  errorlog "Need to provide gcvsampling.dat in ./input !" | tee -a $divacvlog
  errorline | tee -a $divacvlog
fi

ijm=0
for gcv in `cat ./input/gcvsampling.dat`
do
  divaecho ' ' | tee -a $divacvlog
  divaecho ":=============================================  " | tee -a $divacvlog
  divaecho "divacv:Cross validation working with value $gcv " | tee -a $divacvlog
  divaecho "=============================================   " | tee -a $divacvlog
  let ijm=$ijm+1
  head -17 ./input/param.par.ori > bidon
  echo 1 >> bidon
  echo   >> bidon
  echo 1 >> bidon
  echo   >> bidon
  echo -99 >> bidon
  echo >> bidon
  echo $gcv >> bidon
  #tail -2 ./input/param.par.ori >> bidon
  # no error field but qc needs a value
  echo >> bidon
  echo 1 >> bidon
  mv bidon ./input/param.par
  divacalc qc
  cat  $divacvlog $divacalclog > bidon
  mv bidon $divacvlog

  # Now get misfit from adequate files: data, analysis at data and
  # A_ii

  cd divawork

  cp ../input/data.dat fort.20
  cp ../output/fieldatdatapoint.anl fort.21
  cp ../output/expectederroratdatapoint.anl fort.22
  echo -99 $gcv | ../../bin/cverroraii.a >> $divalog

  if [ $? -ne 0 ];then
    errorlog ' ' | tee -a $divacvlog $divalog
    errorline | tee -a $divacvlog $divalog
    errorlog "A problem was encountered during execution !" | tee -a $divacvlog $divalog
    errorlog "        divacv:     cverroraii.a		  " | tee -a $divacvlog $divalog
    errorlog "Check execution track			  " | tee -a $divacvlog $divalog
    errorline | tee -a $divacvlog $divalog
  fi
  # cp -f ../output/diva.log ../output/.
  cat fort.23 >> ../output/gcv.dat

  cd ..

  divaecho "=============================================" >> $divacvlog
  divaecho "Finished working with value" $gcv >> $divacvlog
  divaecho "=============================================" >> $divacvlog
  divaecho ' ' | tee -a >> ${divacvlog}
done

mv -f ./input/param.par.ori ./input/param.par
if [ -f ./input/valatxy.coord.ori ]; then
  mv -f ./input/valatxy.coord.ori ./input/valatxy.coord
fi

cp ./output/gcv.dat ./divawork/fort.11

cd divawork

echo divacv:Looking for the minimum of CV >> $divacvlog
echo ' ' >> $divacvlog

if [ -f ../input/gcvsampling.dat ]; then 
  ../../bin/findmin.a >> $divalog
  if [ $? -ne 0 ]; then
    errorlog ' ' | tee -a $divacvlog $divalog
    errorline | tee -a $divacvlog $divalog
    errorlog "A problem was encountered during execution  !" | tee -a $divacvlog $divalog
    errorlog "        divacv:     findmin.a 		   " | tee -a $divacvlog $divalog
    errorlog "Check execution track 		           " | tee -a $divacvlog $divalog
    errorline | tee -a $divacvlog $divalog
  fi
  divaecho ' ' | tee -a $divacvlog
  divaecho "----------------------------------------" | tee -a $divacvlog
  divaecho "CV finished 			    " | tee -a $divacvlog
  divaecho "Results written in ./output/gcvsnvar.dat" | tee -a $divacvlog
  divaecho "----------------------------------------" | tee -a $divacvlog
else
  errorlog ' ' | tee -a $divacvlog
  errorline | tee -a $divacvlog
  errorlog "A problem was encountered during execution !" | tee -a $divacvlog
  errorlog "Check execution track 			" | tee -a $divacvlog
  errorline | tee -a $divacvlog
fi

mv fort.12 ../output/gcvsnvar.dat
divaecho ' ' | tee -a $divacvlog
divaecho "----------------------------------------" | tee -a $divacvlog
divaecho "GCV finished" | tee -a $divacvlog
divaecho "Estimated value of SNR = ' $(awk 'FNR == 2 { print; exit }' ../output/gcvsnvar.dat)" | tee -a $divacvlog
divaecho "Results written in ./output/gcvsnvar.dat" | tee -a $divacvlog
divaecho "----------------------------------------" | tee -a $divacvlog

divaecho "-----------------------------------------------------" >> $divacvlog
divaecho "Creating adapted param.par in ./output/param.par.gcv " >> $divacvlog
divaecho "-----------------------------------------------------" >> $divacvlog
head -23 ../input/param.par  > ../output/param.par.gcv
head -2 ../output/gcvsnvar.dat | tail -1 >> ../output/param.par.gcv
head -25 ../input/param.par | tail -1 >> ../output/param.par.gcv
head -4 ../output/gcvsnvar.dat  | tail -1 >> ../output/param.par.gcv
if [ "$1" == "-r" ]; then
  divaecho "=======================================================" | tee -a $divacvlog
  divaecho "Replacing SNR with new value from GCV in param.par 	   " | tee -a $divacvlog
  cd ..
  cp -v ./input/param.par ./input/param.par.old
  cp -v ./output/param.par.gcv ./input/param.par
  divaecho "=======================================================" | tee -a $divacvlog
fi
