#!/bin/bash
export LC_ALL=C

source divalogging



infolog --
infolog 'Testing domain integral computation'
infolog --

inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
datafile=${inputdir}'data.dat'
paramfile=${inputdir}'param.par'

./divaclean

echo '0.3 0.3 1' > ${datafile}
echo '0.55 0.9 -1' >> ${datafile}
echo '0.85 0.1 0.2' >> ${datafile}

echo 2 > ${contfile}
echo 4 >> ${contfile}
echo -0.001 -0.001 >> ${contfile}
echo 1.001 -0.001 >> ${contfile}
echo 1.001 1.001 >> ${contfile}
echo -0.001 1.001 >> ${contfile}
echo 4 >> ${contfile}
echo 0.401 0.201 >> ${contfile}
echo 0.401 0.801 >> ${contfile}
echo 0.601 0.801 >> ${contfile}
echo 0.601 0.201 >> ${contfile}


echo '# Correlation Length lc' > ${paramfile}
echo '0.2' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '2' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '101' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '51' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '51' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

./divamesh

./divacalc

divaecho "Computing integral over domain"

./divaintegral

integralfile=./output/integral.dat
{
read integralvalues
} < $integralfile

# Split values (written in same line)
integralvaluesplit=(${integralvalues// / })

infolog --
infolog "                Obtained values (expected)"
infolog "---------------------------------------------------"
infolog "Integral value: "  ${integralvaluesplit[0]} "(5.14786e+08)"
infolog "Surface:        "  ${integralvaluesplit[1]} "(1.13761e+10)"
infolog "Averaged value: "  ${integralvaluesplit[2]} "(0.0452516)"
