#!/bin/bash

source divalogging

infolog 'Sanity check:'
infolog 'Control the value of the field at (0,0)'
infolog 'Should be 0.5'

divaclean

##echo ${inputdir}
divaecho //////////////////////////////////////////////////
divaecho 'Running a simple test'
divaecho //////////////////////////////////////////////////
divaecho ' '

divaecho '1. creating data file'
divaecho ' '

echo '0 0 1' > ${datafile}

divaecho '2. creating contour file'
divaecho ' '

echo 1 > ${contfile}
echo 4 >> ${contfile}
echo -10 -10 >> ${contfile}
echo 10 -10 >> ${contfile}
echo 10 10 >> ${contfile}
echo -10 10 >> ${contfile}


divaecho '3. creating parameter file'
divaecho ' '

echo '# Correlation Length lc' > ${paramfile}
echo '1.0' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '11' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '-10' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '-10' >> ${paramfile}
echo '# dx' >> ${paramfile}
echo '0.1' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.1' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '201' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '201' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

divaecho '4. creating coordinate list file'
divaecho ' '

echo 0.0 0.0 > ${valatxyfile}

divamesh

divacalc

field0=$(awk '{print $3}' output/valatxyascii.anl)

echo ' '
infolog 'Check the results in'
infolog './ouput/ghertonetcdf/results.nc (netcdf)'
echo ' '
infolog 'Field value at origin = ' ${field0}
echo ' '
