#!/bin/bash
echo divagcv:///////////////////////////////////////////
echo divagcv:       Generalized Cross Validation
echo divagcv:///////////////////////////////////////////
echo ' '

divarundir=$(pwd)
divagcvlog=$divarundir'/output/divagcv.log'
divacalclog=$divarundir'/output/divagcv.log'

echo divagcv://///////////////////////////////////////// > $divagcvlog
echo divagcv:       Generalized Cross Validation >> $divagcvlog
echo divagcv://///////////////////////////////////////// >> $divagcvlog
echo ' ' >> $divagcvlog


cp ./input/param.par  ./input/param.par.ori
if [ -f ./input/valatxy.coord.ori ]
then
rm -f ./input/valatxy.coord.ori
fi
if [ -f ./input/valatxy.coord ]
then
mv ./input/valatxy.coord ./input/valatxy.coord.ori
fi
rm -f ./output/gcv.dat
if [ -f ./input/gcvsampling.dat ]
then
#Create mesh once if no mesh present
if [ -f ./meshgenwork/fort.22 ]
then 
echo divagcv:=========================================================================== >> $divagcvlog
echo divagcv:Mesh files already exist, hope they are correct: otherwise execute divamesh >> $divagcvlog
echo divagcv:=========================================================================== >> $divagcvlog
else
divamesh
fi
else
echo divagcv:Need to provide gcvsampling.dat in ./input ! | tee -a $divagcvlog
fi
ijm=0
for gcv in `cat ./input/gcvsampling.dat`
do
echo ' ' | tee -a $divagcvlog
echo divagcv:============================================= | tee -a $divagcvlog
echo divagcv:Generalized Cross Validation  with value $gcv | tee -a $divagcvlog
echo divagcv:============================================= | tee -a $divagcvlog
let ijm=$(($ijm+1))
#head -17 ./input/param.par.ori > bidon
#
head -5 ./input/param.par.ori > bidon
echo 0 >> bidon
head -17 ./input/param.par.ori | tail -11 >> bidon
#
echo 1 >> bidon
echo   >> bidon
echo 1 >> bidon
echo   >> bidon
echo -99 >> bidon
echo >> bidon
echo $gcv >> bidon
#tail -2 ./input/param.par.ori >> bidon
# no error field
echo >> bidon
echo 0 >> bidon
mv bidon ./input/param.par

./divacalc
 cat  $divagcvlog $divacalclog > bidon
 mv bidon $divagcvlog

FILENAME=./divawork/fort.77
{ 
read gcvval 
} < $FILENAME
FILENAME=bidon
echo $gcv > bidon
{ 
read gcv 
} < $FILENAME
rm bidon
echo divagcv:$gcvval >> $divagcvlog
echo divagcv:$gcv $gcvval >> $divagcvlog

echo $gcv $gcvval >> ./output/gcv.dat
########for testing
itestGCV=0
itestsingle=0
if [ "$itestGCV" != "0" ] 
then
cp ./output/fieldatdatapoint.anl ./divawork/fort.71
cp ./input/data.dat ./divawork/fort.20
cd ./divawork
../input/GCVtest/exactgcv.a
cat fort.30 >> ../input/GCVtest/exactgcv.dat
cd ..
fi
if [ "$itestsingle" != "0" ]
then
cat ./output/fieldatdatapoint.anl >> ./input/GCVtest/localvalue.dat
fi
########end testing
echo divagcv:============================================= >> $divagcvlog
echo divagcv:Finished working with value $gcv >> $divagcvlog
echo divagcv:============================================= >> $divagcvlog
echo ' ' >> $divagcvlog
done
mv ./input/param.par.ori ./input/param.par
if [ -f ./input/valatxy.coord.ori ]
then
mv ./input/valatxy.coord.ori ./input/valatxy.coord
fi
cp ./output/gcv.dat ./divawork/fort.11
cd divawork
echo divagcv:Looking for the minimum of GCV  >> $divagcvlog
echo ' ' >> $divagcvlog
if [ -f ../input/gcvsampling.dat ] 
then 
../../bin/findmin.a >> ../output/diva.log
if [ $? -ne 0 ];then
echo ' ' | tee -a $divagcvlog $divalog
echo -------------------------------------------- | tee -a $divagcvlog $divalog
echo A problem was encountered during execution ! | tee -a $divagcvlog $divalog
echo          divagcv      findmin.a		  | tee -a $divagcvlog $divalog
echo Check execution track			  | tee -a $divagcvlog $divalog
echo -------------------------------------------- | tee -a $divagcvlog $divalog
fi
else
echo ' ' | tee -a $divagcvlog $divalog
echo -------------------------------------------- | tee -a $divalog
echo A problem was encountered during execution ! | tee -a $divalog
echo Check execution track 			  | tee -a $divalog
echo -------------------------------------------- | tee -a $divalog
fi
mv fort.12 ../output/gcvsnvar.dat
echo ' ' | tee -a $divagcvlog
echo ---------------------------------------- | tee -a $divagcvlog
echo 'GCV finished' | tee -a $divagcvlog
echo 'Estimated value of SNR = ' $(awk 'FNR == 2 { print; exit }' ../output/gcvsnvar.dat) | tee -a $divagcvlog
echo Results written in ./output/gcvsnvar.dat | tee -a $divagcvlog
echo ---------------------------------------- | tee -a $divagcvlog
echo ' ' >> $divagcvlog
echo ----------------------------------------------------- >> $divagcvlog
echo 'Creating adapted param.par in ./output/param.par.gcv' >> $divagcvlog
echo ----------------------------------------------------- >> $divagcvlog
head -23 ../input/param.par  > ../output/param.par.gcv
head -2 ../output/gcvsnvar.dat | tail -1 >> ../output/param.par.gcv
head -25 ../input/param.par | tail -1 >> ../output/param.par.gcv
head -4 ../output/gcvsnvar.dat  | tail -1 >> ../output/param.par.gcv
if [ "$1" == "-r" ]
then
echo divagcv:======================================================= | tee -a $divagcvlog 
echo divagcv:Replacing SNR by new value from GCV in param.par  	     | tee -a $divagcvlog 
cd ..
cp -v ./input/param.par ./input/param.par.old
cp -v ./output/param.par.gcv ./input/param.par
echo =======================================================
else
cd ..
fi
