#!/bin/bash

source divalogging

if [ "$#" == "1" ]
then
	Ndata=$1
else
	Ndata=100
fi

##echo ${inputdir}
infolog -- 
infolog 'Running a test with divagcv'
infolog -- 

divaecho ' '
divaecho '1. creating data file'
divaecho '   with points at random coordinates'
divaecho ' '

awk -v N=$Ndata 'BEGIN { for (i = 1; i <= N; i++)
        {x=rand();y=rand();print x,y,3*x-2*y-1} }' > ${datafile}

divaecho '2. creating contour file'
divaecho ' '

echo 2 > ${contfile}
echo 4 >> ${contfile}
echo 0 0 >> ${contfile}
echo 1 0 >> ${contfile}
echo 1 1 >> ${contfile}
echo 0 1 >> ${contfile}
echo 4 >> ${contfile}
echo 0.4 0.2 >> ${contfile}
echo 0.4 0.8 >> ${contfile}
echo 0.6 0.8 >> ${contfile}
echo 0.6 0.2 >> ${contfile}


divaecho '3. creating parameter file'
divaecho ' '

echo '# Correlation Length lc' > ${paramfile}
echo '1.0' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '0' >> ${paramfile} 
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '51' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '51' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

divaecho '4. creating list of SNR values to test in GCV'
divaecho '   (file gcvsampling.dat)'
divaecho ' '

echo '0.01' > ${gcvsamplingfile}
echo '0.03' >> ${gcvsamplingfile}
echo '0.1' >> ${gcvsamplingfile}
echo '0.3' >> ${gcvsamplingfile}
echo '0.6' >> ${gcvsamplingfile}
echo '1.0' >> ${gcvsamplingfile}
echo '3.0' >> ${gcvsamplingfile}
echo '6.0' >> ${gcvsamplingfile}
echo '10.0' >> ${gcvsamplingfile}
echo '30.0' >> ${gcvsamplingfile}
echo '100.0' >> ${gcvsamplingfile}

divamesh

divaecho ' '

divacalc

cp ./output/ghertonetcdf/results.nc ./output/ghertonetcdf/results_nogcv.nc

divagcv -r  

divacalc 

cp ./output/ghertonetcdf/results.nc ./output/ghertonetcdf/results_gcv.nc

divaecho ' '
infolog 'Check the results in'
infolog './ouput/ghertonetcdf/results_notgcv.nc (before estimation of SNR)'
infolog './ouput/ghertonetcdf/results_gcv.nc    (after estimation of SNR)'



