#!/bin/bash
export LC_ALL=C

source divalogging

infolog --			| tee -a $divalog
infolog 'Anomaly calculation'	| tee -a $divalog
infolog --			| tee -a $divalog

cd divawork

divaecho 'divaanom: ' > $divaanomlog

cp ../input/data.dat fort.44
LR=0
LD=1
if [ -f ../output/fieldatdatapoint.anl.ref ]
then
  LD=$(cat ../input/data.dat | wc -l)
  LR=$(cat ../output/fieldatdatapoint.anl.ref | wc -l)
  echo ' data.dat & fieldatdatapoint.anl.ref ' $LD $LR
fi
if [ "$LD" -eq "$LR" ]
then
  divaecho ' '
  divaecho =================================================================== | tee -a $divaanomlog
  divaecho There are already reference fields at data points. Will use them | tee -a $divaanomlog
  divaecho Preparing data anomalies based on ./output/fieldatdatapoint.anl.ref | tee -a $divaanomlog
  divaecho =================================================================== | tee -a $divaanomlog

else

  divaecho ' ' | tee -a $divaanomlog
  divaecho =================================================================== | tee -a $divaanomlog
  divaecho !!!!! Will try to use gridded reference field by interpolation !!!!!| tee -a $divaanomlog
  divaecho !!!!! Will also create reference field at valatxy.coord !!!!!!!!!!!!| tee -a $divaanomlog
  divaecho =================================================================== | tee -a $divaanomlog

  if [ -f ../output/fieldgher.anl.ref ]; then
    cp ../output/fieldgher.anl.ref fort.20
  else
    errorlog "File ../output/fieldgher.anl.ref does not exist" | tee -a $divaanomlog
    exit 1
  fi
  cp ../output/ghertonetcdf/GridInfo.dat fort.21
  if [ -f ../input/valatxy.coord ]
  then
    cp ../input/valatxy.coord fort.45
  else
    echo no valatxy.coord
    rm -f fort.45
  fi

  echo divaanom: ////////////////////////////////////////// >> $divalog
  echo divaanom:        interprefe  >> $divalog
  echo divaanom: ////////////////////////////////////////// >> $divalog
  echo ' '  >> $divalog

  ../../bin/interprefe.a
  if [ $? -ne 0 ];then
    errorlog ' '
    errorlog -------------------------------------------- | tee -a $divaanomlog $divalog
    errorlog A problem was encountered during execution ! | tee -a $divaanomlog $divalog
    errorlog      divaanom:     interprefe.a              | tee -a $divaanomlog $divalog
    errorlog Check execution track                        | tee -a $divaanomlog $divalog
    errorlog -------------------------------------------- | tee -a $divaanomlog $divalog
  fi
  cp -v fort.81 ../output/fieldatdatapoint.anl.ref
  cp -v  fort.82 ../output/valatxyascii.anl.ref
  rm fort.45
  rm fort.20
  rm fort.21
  rm fort.81
  rm fort.82
  # keep fort.44
fi
divaecho ============================ >> $divaanomlog
divaecho       Now anomalies >> $divaanomlog
divaecho ============================ >> $divaanomlog
head -22 ../input/param.par | tail -1 > coucou
{
  read valex
} < coucou
rm coucou
paste ../output/fieldatdatapoint.anl.ref ../input/data.dat > bidon
mv ../input/data.dat ../input/data.dat.full
awk -v valex=$valex '{$6=$6-$3; $1=""; $2=""; $3=""; print $0}' bidon > ../input/data.dat
rm bidon
divaecho =================================================================== >> $divaanomlog
divaecho data.dat now contains anomalies >> $divaanomlog
divaecho data.dat.full are original data >> $divaanomlog
divaecho =================================================================== >> $divaanomlog
divaecho  ' ' >> $divaanomlog

cd ..
