#!/bin/bash

source divalogging

infolog --			| tee -a $divalog
infolog 'Best guess for the parameter estimation'	| tee -a $divalog
infolog --			| tee -a $divalog

small="100"
medium="2000"
ndata=$(cat ./input/data.dat| wc -l)
divaecho ========================================
divaecho    Full parameter estimation
divaecho ========================================
if [ "$ndata" -le "$small" ]
then
  divaecho ===============
  divaecho Small data set
  divaecho ===============
  divafit -r
else
  if [ "$ndata" -le "$medium" ]
  then
    divaecho ===============
    divaecho Medium data set
    divaecho ===============
    divafit -r
  else
    divaecho ==============
    divaecho Large data set
    divaecho ==============
    divafit $medium -r
  fi
fi
# OK, so now we have a first guess on L
# Make the mesh accordingly (option -r already made the param.par)
divamesh
FIRSTL=$(head -2 ./input/param.par | tail -1)
divaecho ==========
divaecho L: $FIRSTL
divaecho will try
rm ./input/gcvsamplingL.dat
echo $(echo $FIRSTL | awk '{print ($1*0.3)}') >>  ./input/gcvsamplingL.dat
echo $(echo $FIRSTL | awk '{print ($1*0.5)}') >>  ./input/gcvsamplingL.dat
echo $(echo $FIRSTL | awk '{print ($1*1.0)}') >>  ./input/gcvsamplingL.dat
echo $(echo $FIRSTL | awk '{print ($1*2.0)}') >>  ./input/gcvsamplingL.dat
echo $(echo $FIRSTL | awk '{print ($1*5.0)}') >>  ./input/gcvsamplingL.dat
echo ==========
if [ -f ./output/gcvL.dat ]
then
  divaecho Erasing old gcvL.dat
  rm ./output/gcvL.dat
fi
for Lgcv in `cat ./input/gcvsamplingL.dat`
do
  divaecho Working with length scale $Lgcv
  # Prepare adapted param.par
  cp -v ./input/param.par ./input/param.par.oriL
  head -1 ./input/param.par.oriL > ./input/param.par
  echo $Lgcv >> ./input/param.par
  head -26 ./input/param.par.oriL | tail -24 >> ./input/param.par
  if [ "$ndata" -le "$small" ]; then
    divacv -r
  else
    if [ "$ndata" -le "$medium" ]; then
      divagcv -r
    else
      let nsamp=$(($ndata/20))
      divacvrand $nsamp 2 -r
    fi
  fi
  # restore param.par
  cp -v ./input/param.par.oriL ./input/param.par
  cat ./output/gcv.dat >> ./output/gcvL.dat
done

infolog --			| tee -a $divalog
infolog 'End parameter estimation'	| tee -a $divalog
infolog --			| tee -a $divalog
