#!/bin/bash



echo 'Sanity check:'
echo 'Control the value of the field at 0,0'
echo 'should be 0.5'
 
inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
datafile=${inputdir}'data.dat'
paramfile=${inputdir}'param.par'
valatxyfile=${inputdir}'valatxy.coord'

divaclean

##echo ${inputdir}
echo //////////////////////////////////////////////////
echo 'Running a simple test'
echo //////////////////////////////////////////////////
echo ' '

echo '1. creating data file'
echo ' '

echo '0 0 1' > ${datafile}

echo '2. creating contour file'
echo ' '

echo 1 > ${contfile}
echo 4 >> ${contfile}
echo -10 -10 >> ${contfile}
echo 10 -10 >> ${contfile}
echo 10 10 >> ${contfile}
echo -10 10 >> ${contfile}


echo '3. creating parameter file'
echo ' '

echo '# Correlation Length lc' > ${paramfile}
echo '1.0' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '11' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '-10' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '-10' >> ${paramfile} 
echo '# dx' >> ${paramfile}
echo '0.1' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.1' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '201' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '201' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

echo '4. creating coordinate list file'
echo ' '
echo 0.0 0.0 > ${valatxyfile}

divamesh

divacalc

field0=$(awk '{print $3}' output/valatxyascii.anl)

echo ' '
echo 'Check the results in'
echo './ouput/ghertonetcdf/results.nc (netcdf)'
echo ' '
echo 'Field value at origin = ' ${field0}
echo ' '

