#!/bin/bash





echo Now testing divacalc

inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
datafile=${inputdir}'data.dat'
paramfile=${inputdir}'param.par'

divaclean

##echo ${inputdir}
echo //////////////////////////////////////////////////
echo 'Running a simple test'
echo //////////////////////////////////////////////////
echo ' '

echo '1. creating data file'
echo ' '

echo '0.3 0.3 1' > ${datafile}
echo '0.55 0.9 -1' >> ${datafile}
echo '0.85 0.1 0.2' >> ${datafile}

echo '2. creating contour file'
echo ' '

echo 2 > ${contfile}
echo 4 >> ${contfile}
echo -0.001 -0.001 >> ${contfile}
echo 1.001 -0.001 >> ${contfile}
echo 1.001 1.001 >> ${contfile}
echo -0.001 1.001 >> ${contfile}
echo 4 >> ${contfile}
echo 0.401 0.201 >> ${contfile}
echo 0.401 0.801 >> ${contfile}
echo 0.601 0.801 >> ${contfile}
echo 0.601 0.201 >> ${contfile}


echo '3. creating parameter file'
echo ' '

echo '# Correlation Length lc' > ${paramfile}
echo '0.2' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '11' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '0' >> ${paramfile} 
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '51' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '51' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

divamesh

divacalc

echo ' '
echo 'Check the results in'
echo './ouput/ghertonetcdf/results.nc (netcdf)'


echo 'Now checking if you have gawk or nawk'
whichawk=$(echo 0 | awk '{if (PROCINFO["version"])  print "1"; else print "0"; }')
echo $whichawk
if [ "$whichawk" != "1" ]
then
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo !!! PLEASE INSTALL GAWK !!!!!!!!!!!!
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
else
echo gawk is present
fi

echo 
echo
echo

echo Finally testing pipes needed for exact error calculations
echo If the program hangs it means pipes are not supported
echo In this case you need to adapt parameter ipipe to ipepe=0 in divacalc
cd ../src/Fortran/Pipetest
pipetest

cd ../../../divastripped

