#!/bin/bash
##########################################
#
  Fileinf=./input/3Dinfo
{
read comment
read comment
read comment
read bottm
read comment
read surf
read comment
read cont
} < $Fileinf
#
#
if [ "$cont" -eq "1" ]; then
if [ -d ./input/divaparam ];then
echo '>>>WARNING: ./input/divaparam exists.'
else
mkdir -p ./input/divaparam
fi
if [ -f ./input/topo.grd ]; then
echo " topo.grd found, will proceed to generate coast.cont files"
else
 if [ -f ./input/topo.dat ]; then
  if [ -f ./input/param.par ]; then
   if [ -f ./input/contour.depth ];then
    echo "running divatopo ........."
    ./divatopo
    mv ./output/TopoInfo.dat ./input/.
    mv ./output/topo.grd ./input/.
    echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
    echo 'TopoInfo.dat and topo.grd were created and put in '
    echo ./input/.
    echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
   else
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    echo '!!!!!!!!!!  diva3Dcont:    !!!!!!!!!!!!!!!!!'
    echo 'Missing contour.depth file, could not perform !!'
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
   fi
  else
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    echo '!!!!!!!!!!  diva3Dcont:    !!!!!!!!!!!!!!!!!'
    echo 'Missing param.par file, could not perform !!'
    echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
  fi
 else
  if [ -f ./input/topo.gebco ]; then
    if [ -f ./input/param.par ]; then
     if [ -f ./input/contour.depth ];then
      echo "running gebco2diva ........."
      ./gebco2diva 10 10
      mv ./output/TopoInfo.dat ./input/.
      mv ./output/topo.grd ./input/.
      echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
      echo 'TopoInfo.dat and topo.grd were created and put in '
      echo ./input/.
      echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
     else
      echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
      echo '!!!!!!!!!!  diva3Dcont:    !!!!!!!!!!!!!!!!!'
      echo 'Missing contour.depth file, could not perform !!'
      echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
     fi
    else
      echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
      echo '!!!!!!!!!!  diva3Dcont:    !!!!!!!!!!!!!!!!!'
      echo 'Missing param.par file, could not perform !!'
      echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    fi
  fi
 fi
fi
#
if [ -f ./input/topo.grd ]; then
 ./divacont
mv ./output/coast.cont* ./input/divaparam/.
echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
echo 'coast.cont files were created and put in '
echo ./input/divaparam/.
echo ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
fi
#
fi
#
if [ "$cont" -ge "2" ]; then
if [ -f ./input/topo.dat ]; then
   if [ -f ./input/param.par ]; then
      echo "running divatopo ........."$cont
    ./divatopo
   else
     echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
     echo '!!!!!!!!!!  diva3Dcont:    !!!!!!!!!!!!!!!!!'
     echo 'Missing param.par file, could not perform !!'
     echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
   fi
else
  if [ -f ./input/topo.gebco ]; then
    if [ -f ./input/param.par ]; then
      echo "running gebco2diva ........."$cont
      ./gebco2diva 15 15
    else
      echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
      echo '!!!!!!!!!!  diva3Dcont:    !!!!!!!!!!!!!!!!!'
      echo 'Missing param.par file, could not perform !!'
      echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    fi
  fi
 mv ./output/TopoInfo.dat ./input/.
 mv ./output/topo.grd ./input/.
fi
if [ "$cont" -eq "3" ]; then
if [ -d ./input/divaparam ];then
echo '>>>WARNING: ./input/divaparam exists, files may be rewritten'
else
mkdir -p ./input/divaparam
fi
if [ -f ./input/topo.grd ]; then
 ./divacont
mv ./output/coast.cont* ./input/divaparam/.
fi
fi
if [ -d ./input/divaUVcons ];then
echo '>>>WARNING: ./input/divaUVcons exists, files may be rewritten'
else
mkdir -p ./input/divaUVcons
fi
if [ -f ./input/topo.grd ]; then
if [ -f ./input/param.par ]; then
./divaUVtopo
cp -v ./output/U* ./input/divaUVcons
cp -v ./output/V* ./input/divaUVcons
cp -v ./output/constraint.dat ./input/.
else
echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
echo '!!!!!!!!!!  diva3Dcont:    !!!!!!!!!!!!!!!!!'
echo 'Missing param.par file, could not perform !!'
echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
fi
fi
fi
