#!/bin/bash

source divalogging

infolog -- 
infolog "Cleaning up intermediate files"
infolog --

divaecho ' ' 
divaecho Making directories
divaecho ' ' 

mkdir -p ./divawork
mkdir -p ./meshgenwork
mkdir -p ./output
mkdir -p ./input
mkdir -p ./output/ghertonetcdf
mkdir -p ./output/meshvisu
mkdir -p ./gnuwork
divaecho Cleaning divawork and gnuwork directory
divaecho ' ' 
rm -f ./logs/*log
rm -f ./divawork/*.log              # Remove all log files?
rm -f ./divawork/fort.*
rm -f ./divawork/dvping
rm -f ./divawork/dvpong
rm -f ./divawork/divapipe
rm -f ./divawork/*.stackdump
rm -f ./gnuwork/*.stackdump
rm -f ./gnuwork/fort.*
rm -f ./gnuwork/plots/*
rm -f ./divawork/sub/*
rm -f ./divawork/coast.cont*        # Removing old contours

divaecho Cleaning meshgenwork directory
divaecho ' ' 
rm -f ./meshgenwork/fort.*
rm -f ./meshgenwork/diva.log
divaecho Cleaning output directory
divaecho ' ' 
rm -f ./output/meshvisu/fort.*
rm -f ./output/*.anl
rm -f ./output/ghertonetcdf/GridInfo.dat
rm -f ./output/ghertonetcdf/fort.*
rm -f ./output/ghertonetcdf/diva.log
rm -f ./output/*.dat
rm -f ./output/*.nc
rm -f ./output/*.ref
divaecho Looking for density file...
divaecho ' ' 

if [ -f ./input/coast.cont.dens ]; then
  warnline 
  warnlog "... there is a coast.cont.dens file"
  warnlog "Are you sure you provided it for this application?"
  echo ' '
  warnline
  warnlog "In any case, make sure the input files in ./input are OK"
  echo
  warline
  else 
  warnlog "... there is no density file"
fi

divaecho ' ' 
divaecho --------------------
divaecho Cleaning is finished
divaecho --------------------
