#!/bin/bash





echo Now testing divacalc with a lot of data and small mesh

inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
datafile=${inputdir}'data.dat'
paramfile=${inputdir}'param.par'

##echo ${inputdir}
echo //////////////////////////////////////////////////
echo 'Running a heavy test'
echo //////////////////////////////////////////////////
echo ' '

echo '1. creating huge data file, be patient'
echo ' '

echo 2000000 | awk '{NP=$1;{for (i = 1; i <= NP; i++) {x=-1+2*rand();y=-1+2*rand();z=sin(3.14*x)*cos(3.14*y)*exp(x+y);print x,y,z,1}}}' > ${datafile}

echo '2. creating contour file'
echo ' '

echo 2 > ${contfile}
echo 4 >> ${contfile}
echo -1 -1 >> ${contfile}
echo 1 -1 >> ${contfile}
echo 1  1 >> ${contfile}
echo -1 1 >> ${contfile}
echo 4 >> ${contfile}
echo 0.4 0.2 >> ${contfile}
echo 0.4 0.8 >> ${contfile}
echo 0.6 0.8 >> ${contfile}
echo 0.6 0.2 >> ${contfile}


echo '3. creating parameter file'
echo ' '

echo '# Correlation Length lc' > ${paramfile}
echo '0.07' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '11' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '-1' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '-1' >> ${paramfile} 
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '101' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '101' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

divamesh

echo 'Now into the calculation itself'

divacalc

echo ' '
echo 'Check the results in'
echo './ouput/ghertonetcdf/results.nc (netcdf)'



