#!/bin/bash
#
#first layer to be processed
bottm=$1
#last layer to be processed
surf=$2
temp=$3
psal=$4
actp=$5
acts=$6
##########################################
#
mkdir -p ./output/3Danalysis/Before_stab
#
let lev1=10000+$bottm
let lev2=10000+$surf
if [ "$actp" == "1" ]; then
mv ./output/3Danalysis/$temp'.'$lev1'.'$lev2'.anl.nc' ./output/3Danalysis/Before_stab/.
else
mv ./output/3Danalysis/$temp'.'$lev1'.'$lev2'.ref.nc' ./output/3Danalysis/Before_stab/.
dep=$bottm
while [ $dep -le $surf ]
do
let level=10000+$dep
cp -v './output/3Danalysis/Fields/'$temp'.'$level'.ref' './output/3Danalysis/Fields/'$temp'.'$level'.anl'
cp -v './output/3Danalysis/Fields/'$temp'.'$level'.ref.error'  './output/3Danalysis/Fields/'$temp'.'$level'.error'
dep=`expr $dep + 1`
done
fi
if [ "$acts" == "1" ]; then
mv ./output/3Danalysis/$psal'.'$lev1'.'$lev2'.anl.nc' ./output/3Danalysis/Before_stab/.
else
mv ./output/3Danalysis/$psal'.'$lev1'.'$lev2'.ref.nc' ./output/3Danalysis/Before_stab/.
dep=$bottm
while [ $dep -le $surf ]
do
let level=10000+$dep
cp -v './output/3Danalysis/Fields/'$psal'.'$level'.ref' './output/3Danalysis/Fields/'$psal'.'$level'.anl'
cp -v './output/3Danalysis/Fields/'$psal'.'$level'.ref.error'  './output/3Danalysis/Fields/'$psal'.'$level'.error'
dep=`expr $dep + 1`
done
fi
mv ./output/3Danalysis/TEMP_SAL_*.nc ./output/3Danalysis/Before_stab/.
mv ./output/3Danalysis/GnuPlots ./output/3Danalysis/Before_stab/.
