#!/bin/bash
#####################################################
#
# $1 = level number
# $2 = variable name.
#======================================
lev=$1
var=$2
if [ -f ./input/divatrans/$var.$lev.anl.mat ];then
  if [ -f ./output/3Danalysis/Fields/$var.$lev.anl ];then
    cp ./output/3Danalysis/Fields/$var.$lev.anl ./output/3Danalysis/Fields/$var.$lev.anl.trsf
    gherfile=$var.$lev.anl
#    matlab="matlab -nosplash -nodesktop"
#    $matlab <<EOF
#    invtrans('$gherfile')
#    EOF
    echo dv3D_invtrans: mission accomplie pour $var.$lev.anl
  else
    echo dv3D_invtrans did not find $var.$lev.anl
  fi
else
    echo dv3D_invtrans did not find $var.$lev.anl.mat
fi
