#!/bin/bash
#######################################
#
# $1 = level number
# $2 = variable name.
#======================================
lev=$1
var=$2
ntrans=$3
act=$4


diva3dlog='./output/3Danalysis/'$var'.diva3D.log'
#
echo 'dv3Dinvtrsh:' 
echo 'dv3Dinvtrsh:' 'Start field transform: '
echo 'dv3Dinvtrsh:' 'on '$var', level '$lev', trans-flag '$ntrans
echo 'dv3Dinvtrsh:'
#
echo 'dv3Dinvtrsh:'  >> $diva3dlog
echo 'dv3Dinvtrsh:' 'Start field transform' >> $diva3dlog
echo 'dv3Dinvtrsh:' 'on '$var', level '$lev', trans-flag '$ntrans >> $diva3dlog
echo 'dv3Dinvtrsh:' >> $diva3dlog
#



flag=1
nblines=0
if [ "$act" == "1" ];then

if [ -f ./output/3Danalysis/Fields/$var.$lev.anl.nc ];then

 cp ./output/3Danalysis/Fields/$var.$lev.anl.nc ./output/3Danalysis/Fields/$var.$lev.anl.tr.nc
 cp ./output/3Danalysis/Fields/$var.$lev.anl ./output/3Danalysis/Fields/$var.$lev.anl.tr

ncdfile=$var.$lev.anl.nc
binfile=$var.$lev.anl
ascfile=$var.$lev.ascii.anl

echo 'dv3Dinvtrsh '$gherfile' '$binfile >> $diva3dlog
echo 'dv3Dinvtrsh '$gherfile' '$binfile

flag=0

fi
fi

if [ "$act" == "2" ];then

if [ -f ./output/3Danalysis/Fields/$var.$lev.ref.nc ];then

 cp ./output/3Danalysis/Fields/$var.$lev.ref.nc ./output/3Danalysis/Fields/$var.$lev.ref.tr.nc
 if [ -f ./output/3Danalysis/Fields/$var.$lev.ref ];then
  cp ./output/3Danalysis/Fields/$var.$lev.ref ./output/3Danalysis/Fields/$var.$lev.ref.tr
  binfile=$var.$lev.ref

  echo 'dv3Dinvtrsh ncfile '$binfile >> $diva3dlog
  echo 'dv3Dinvtrsh ncfile '$binfile

 fi
 if [ -f ./output/3Danalysis/Fields/$var.$lev.datapoint.ref ];then
  cp ./output/3Danalysis/Fields/$var.$lev.datapoint.ref ./output/3Danalysis/Fields/$var.$lev.datapoint.ref.tr
  ascfile=$var.$lev.datapoint.ref
  nblines=`cat ./output/3Danalysis/Fields/$ascfile |wc -l` 

  echo 'dv3Dinvtrsh ascfile '$ascfile >> $diva3dlog
  echo 'dv3Dinvtrsh ascfile '$ascfile

 fi

ncdfile=$var.$lev.ref.nc
echo 'dv3Dinvtrsh ncfile '$binfile

flag=0

fi
fi

if [ "$flag" == "1" ];then

echo ' did not find '$var'.'$lev' 2D file (analysis of transformed data)' >> $diva3dlog
echo ' did not find '$var'.'$lev' 2D file (analysis of transformed data)'

exit

fi

mkdir -p ./3DWORK
echo 'starting transformation of '$var'.'$lev'.anl.nc' >> $diva3dlog
echo 'starting transformation of '$var'.'$lev'.anl.nc'
#
echo $ncdfile > ./3DWORK/ncname
echo $binfile >> ./3DWORK/ncname
echo $ascfile >> ./3DWORK/ncname
echo $var >> ./3DWORK/ncname
echo $lev >> ./3DWORK/ncname
echo $act >> ./3DWORK/ncname
echo $ntrans >> ./3DWORK/ncname
echo $nblines >> ./3DWORK/ncname
#
# Start analyses inverse transformation
#######################################
#
echo 'Start analyses inverse transformation '$ntrans
echo 'Start analyses inverse transformation '$ntrans >> $diva3dlog

cd ./3DWORK
#if [ -f ERR.$var.$lev ];then
#
#  echo 'No inverse transformation for '$var.$lev >> ../$diva3dlog
#  echo 'No inverse transformation for '$var.$lev
#else
  echo ' Inverse transformation for '$var.$lev >> ../$diva3dlog
  echo ' Inverse transformation for '$var.$lev

  echo dv3Dinvtrsh: ////////////////////////////////////////// >> ../output/diva.log
  echo dv3Dinvtrsh:       anatrans   >> ../output/diva.log
  echo dv3Dinvtrsh: ////////////////////////////////////////// >> ../output/diva.log
  echo ' '  >> ../output/diva.log

  ../../bin/anatrans.a >> ../$diva3dlog


  if [ $? -ne 0 ];then
  echo ' '
  echo --------------------------------------------
  echo A problem was encountered during execution !
  echo       dv3Dinvtrsh:  anatrans.a
  echo Check execution track
  echo --------------------------------------------
  echo ' ' >> ../$diva3dlog
  echo -------------------------------------------- >> ../$diva3dlog
  echo A problem was encountered during execution ! >> ../$diva3dlog
  echo       dv3Dinvtrsh:  anatrans.a >> ../$diva3dlog
  echo Check execution track >> ../$diva3dlog
  echo -------------------------------------------- >> ../$diva3dlog
  echo ' ' >> ../output/diva.log
  echo -------------------------------------------- >> ../output/diva.log
  echo A problem was encountered during execution ! >> ../output/diva.log
  echo       dv3Dinvtrsh:   anatrans.a  >> ../output/diva.log
  echo Check execution track >> ../output/diva.log
  echo -------------------------------------------- >> ../output/diva.log
  fi

#fi
cd ../
#
# End analyses inverse transformations
######################################
#
