#! /bin/bash
################
#
bottm=$1
surf=$2
var=$3
itrans=$4
#
if [ -d ./3DWORK ];then
echo 'starting divaqc files generation'
else
mkdir -p ./3DWORK
echo 'starting divaqc files generation'
fi
#
dep=$bottm
rm -f ./3DWORK/fort.44
while [ $dep -le $surf ]
do
let level=$((10000+$dep))
#
cd ./input/divadata

  file=$var.$level
  nbln=$(cat $file |wc -l)

  echo $var > ../../3DWORK/fort.44
  echo $nbln >> ../../3DWORK/fort.44
  echo $dep >> ../../3DWORK/fort.44
cd ../../3DWORK/
../../bin/dvqcfiles.a
cd ../
#
 dep=`expr $dep + 1`
done
echo 'finished with divaqcfiles'
#
# End transformations
#################################
#
