#!/bin/bash
export LC_ALL=C
echo Going to clean data points outside the mesh > ./output/dvdataclean.log
echo Going to clean data points outside the mesh > ./output/dvdataclean.log
valex=$(head -22 ./input/param.par | tail -1)
echo Using valex $valex > ./output/dvdataclean.log
awk -v valex=$valex 'NR==FNR {s[i++]=$0; next; j=0} { if ( ($3-valex)*($3-valex) > 0.0000000001*(valex*valex) ) {j=j+1;print s[j-1]} else {j=j+1}}' ./input/data.dat ./output/fieldatdatapoint.anl > ./input/data.dat.clean
echo Before cleaning > ./output/dvdataclean.log
wc -l ./input/data.dat > ./output/dvdataclean.log
echo After cleaning of points outside of the mesh > ./output/dvdataclean.log
echo Before cleaning
wc -l ./input/data.dat
echo After cleaning of points outside of the mesh
wc -l ./input/data.dat.clean
mv -v ./input/data.dat ./input/data.beforeclean.dat
mv -v ./input/data.dat.clean ./input/data.dat
