#!/bin/bash
export LC_ALL=C

source divalogging

divaecho "Going to clean data points outside the mesh" >> ${divadatalog}
valex=$(head -22 ./input/param.par | tail -1)
divaecho "Using valex $valex" >> ${divadatalog}
awk -v valex=$valex 'NR==FNR {s[i++]=$0; next; j=0} { if ( ($3-valex)*($3-valex) > 0.0000000001*(valex*valex) ) {j=j+1;print s[j-1]} else {j=j+1}}' ./input/data.dat ./output/fieldatdatapoint.anl > ./input/data.dat.clean
divaecho "Before cleaning" | tee -a ${divadatalog}
divaecho "$(wc -l ./input/data.dat)"     | tee -a ${divadatalog}
divaecho "After cleaning of points outside of the mesh" | tee -a ${divadatalog}
divaecho "$(wc -l ./input/data.dat.clean)"  | tee -a ${divadatalog}
mv -v ./input/data.dat ./input/data.beforeclean.dat
mv -v ./input/data.dat.clean ./input/data.dat
