#!/bin/bash
cd divawork
cp ../input/data.dat fort.88
cp ../output/fieldatdatapoint.anl fort.89
if [ -f ../output/diva.log ] ; then
 cp  -f ../output/diva.log .
fi
../../bin/detrend.a >> diva.log

if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo       divacalc:    detrend.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> diva.log
echo -------------------------------------------- >> diva.log
echo A problem was encountered during execution ! >> diva.log
echo       divacalc:    detrend.a  >> diva.log
echo Check execution track >> diva.log
echo -------------------------------------------- >> diva.log
fi

cp  -f diva.log  ../output/.
cp fort.90 ../input/data.detrend.dat
cp fort.97 ../output/trends.dat
cd ..
echo ' '
