#!/bin/bash
DIVAWORK=./divawork
export LC_ALL=C
echo //////////////////////////////////////////////////
echo           No data on grid: creating nil solution
echo //////////////////////////////////////////////////
Filepar=./input/param.par
{
read linecomment
read lc
read linecomment
read icoordchange
read linecomment
read ispec
read linecomment
read ireg
read linecomment
read xori
read linecomment
read yori
read linecomment
read dx
read linecomment
read dy
read linecomment
read nx
read linecomment
read ny
read linecomment
read valex
read linecomment
read snr
read linecomment
read varbak
} < $Filepar
if [ -f ./input/valatxy.coord  ]; then 
awk -v valex=$valex '{print $1,$2,valex}' ./input/valatxy.coord > $DIVAWORK/fort.82
fi
awk -v valex=$valex '{print $1,$2,valex}' ./input/data.dat > $DIVAWORK/fort.71
cp $DIVAWORK/fort.71 $DIVAWORK/fort.72
cp $DIVAWORK/fort.82 $DIVAWORK/fort.73
cd $DIVAWORK
echo $nx $ny $valex | ../../bin/dvnil.a
cd ..