#!/bin/bash
#####################################################
#
#
bottm=$1
surf=$2
var="$3"
itrans=$4
#
dvrefetransflog='./output/3Danalysis/'"$var"'_dvrefetransf.log'
#
##if [ -f "./input/dorefeinfo" ];then
##FILENAME="./input/dorefeinfo"
##{
##read revar
##read yrref
##read mnref
##} < $FILENAME
##var=$revar.$yrref.$mnref
##fi
#
if [ -d "./3DWORK" ];then
echo 'starting data transformation' > $dvrefetransflog
else
mkdir -p ./3DWORK
echo 'starting data transformation' > $dvrefetransflog
fi
echo 'making a backup of  ./input/divarefe' >> $dvrefetransflog
cp -r ./input/divarefe ./input/divarefe_BKP
#

if [ "$itrans" == "13" ];then 
echo Start anamorphose transformation of reference fields >> $dvrefetransflog
######################################################


dep=$bottm
rm -f ./3DWORK/fort.33
while [ $dep -le $surf ]
do
let level=$((10000+$dep))
#
if [ -f ./input/divarefe/"$var"'.'$level'.datapoint.ref' ];then

cd ./input/divarefe
  file="$var"'.'$level'.datapoint.ref'
  nbcl=$(head -n 1 $file | wc -w)
  nbln=$(cat $file |wc -l)
  echo "$var" > ../../3DWORK/fort.33
  echo $itrans >> ../../3DWORK/fort.33
  echo $bottm >> ../../3DWORK/fort.33
  echo $surf >> ../../3DWORK/fort.33
  echo $nbln >> ../../3DWORK/fort.33
  echo $nbcl >> ../../3DWORK/fort.33
  echo $dep >> ../../3DWORK/fort.33
cd ../../3DWORK/


echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
echo 'dvrefetransf:       refenoise: '"$var"   >> ./output/diva.log
echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
echo ' '  >> ./output/diva.log

../../bin/refenoise.a >> ../output/diva.log


if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo       dvrefetransf:  refenoise.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo A problem was encountered during execution ! >> ../$dvrefetransflog
echo       dvrefetransf:  refenoise.a >> ../$dvrefetransflog
echo Check execution track >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo       dvrefetransf:   refenoise.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi

cd ../

fi

dep=`expr $dep + 1`
done
#
cd input/divarefe

rm -f '../../3DWORK/lsdivarefe'
rm -f '../../3DWORK/refbruitls'

dep=$bottm
while [ $dep -le $surf ]
do
let level=$((10000+$dep))


if [ -f ./input/divarefe/"$var"'.'$level'.datapoint.ref' ];then


file="$var"'.'$level'.datapoint.ref'
nbcl=$(head -n 1 $file | wc -w)
nbln=$(cat $file |wc -l)
echo $file $nbln $nbcl >> ../../3DWORK/lsdivarefe
echo 'refbruit_'"$var"'.'$level'.datapoint.ref' >> ../../3DWORK/refbruitls

fi

dep=`expr $dep + 1`
done

if [ -f '../../3DWORK/refbruitls' ];then

cat 'refbruit_'"$var"'.1'*'.datapoint.ref' >../../3DWORK/"$var"'_noise.ref'

cd ../../3DWORK/
  file="$var"'_noise.ref'
  nbln=$(cat $file |wc -l)
  file='lsdivadata'
  nbfl=$(cat $file |wc -l)
  echo "$var" > fort.33
  echo $itrans >> fort.33
  echo $bottm >> fort.33
  echo $surf >> fort.33
  echo $nbln >> fort.33


echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
echo dvrefetransf:       refenoise   >> ./output/diva.log
echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
echo ' '  >> ./output/diva.log

../../bin/sortref.a >> ../output/diva.log

if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo       dvrefetransf:  sortref.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo A problem was encountered during execution ! >> ../$dvrefetransflog
echo       dvrefetransf:  sortref.a >> ../$dvrefetransflog
echo Check execution track >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo       dvrefetransf:   sortref.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi

#
  file='../input/divarefe/'"$var"'_inverf'
  nbln=$(cat $file |wc -l)
  file='lsdivarefe'
  nbfl=$(cat $file |wc -l)
  echo "$var" > fort.33
  echo $itrans >> fort.33
  echo $bottm >> fort.33
  echo $surf >> fort.33
  echo $nbln >> fort.33
  echo $nbfl >> fort.33

echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
echo 'dvrefetransf:       refenoise: '"$var"   >> ./output/diva.log
echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
echo ' '  >> ./output/diva.log

../../bin/refdispach.a >> ../output/diva.log

if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo       dvrefetransf:  refdispach.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo A problem was encountered during execution ! >> ../$dvrefetransflog
echo       dvrefetransf:  refdispach.a >> ../$dvrefetransflog
echo Check execution track >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo       dvrefetransf:   refdispach.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi

echo 'finished anamorphose refe transformation'
cd ..

fi

else

echo Start data transformation >> $dvrefetransflog
#################################
#
dep=$bottm
rm -f ./3DWORK/fort.44
while [ $dep -le $surf ]
do
let level=$((10000+$dep))

if [ -f ./input/divarefe/"$var"'.'$level'.datapoint.ref' ];then
#
cd ./input/divarefe
  file="$var".$level'.datapoint.ref'
  nbcl=$(head -n 1 $file | wc -w)
  nbln=$(cat $file |wc -l)

  echo "$var" > ../../3DWORK/fort.44
  echo $itrans >> ../../3DWORK/fort.44
  echo $bottm >> ../../3DWORK/fort.44
  echo $surf >> ../../3DWORK/fort.44
  echo $nbln >> ../../3DWORK/fort.44
  echo $nbcl >> ../../3DWORK/fort.44
  echo $dep >> ../../3DWORK/fort.44

  echo "$var" >> $dvrefetransflog
  echo $itrans >> $dvrefetransflog
  echo $bottm  >> $dvrefetransflog
  echo $surf  >> $dvrefetransflog
  echo $nbln >> $dvrefetransflog
  echo $nbcl >> $dvrefetransflog
  echo $dep  >> $dvrefetransflog

  cd ../../3DWORK/

echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
'echo dvrefetransf:       refetrans: '"$var"'.'$level   >> ./output/diva.log
echo dvrefetransf: ////////////////////////////////////////// >> ../output/diva.log
echo ' '  >> ./output/diva.log

  ../../bin/refetrans.a >> ../output/diva.log

if [ $? -ne 0 ];then
echo ' '
echo --------------------------------------------
echo A problem was encountered during execution !
echo       dvrefetransf:  refetrans.a
echo Check execution track
echo --------------------------------------------
echo ' ' >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo A problem was encountered during execution ! >> ../$dvrefetransflog
echo       dvrefetransf:  refetrans.a >> ../$dvrefetransflog
echo Check execution track >> ../$dvrefetransflog
echo -------------------------------------------- >> ../$dvrefetransflog
echo ' ' >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
echo A problem was encountered during execution ! >> ../output/diva.log
echo       dvrefetransf:   refetrans.a  >> ../output/diva.log
echo Check execution track >> ../output/diva.log
echo -------------------------------------------- >> ../output/diva.log
fi

  if [ -f fort.55 ];then
  mv fort.55 'ERR.'"$var"'.'$level'.datapoint.ref'
  fi
cd ../
#

else

 if [ -f ./input/divarefe/"$var"'.'$lev'.ref' ];then
#
cd ./input/divarefe
  file="$var"'.'$level'.ref'

  echo $file > ../../3DWORK/fort.44
  echo $itrans >> ../../3DWORK/fort.44

  cd ../../3DWORK/
  ../../bin/refebintrans.a
  if [ -f fort.55 ];then
  mv fort.55 'ERR.'"$var"'.'$level'.ref'
  fi

 fi
fi

cd ../
dep=`expr $dep + 1`
done

echo 'finished non-13 transform' >> $dvrefetransflog
#

fi

echo 'finished transforming data' >> $dvrefetransflog
