#!/bin/bash
export LC_ALL=C

if [ "$#" != "2" ]
then
echo '=========================================='
echo  Usage:
echo '    ' dvtimesx LC icoord
echo  Example: coorelation length ob obs noise 0.1
echo '        ' with coordinates transformed in km
echo '    ' dvtimesx 0.1 1
echo '=========================================='

exit
fi

cp ./input/data.dat.x ./divawork/fort.20
cd divawork
echo $1 $2 | ../../bin/Rtimesx.a
cd ..
cp ./divawork/fort.21 ./output/data.dat.Rx
