#!/bin/bash
export LC_ALL=C

source divalogging

inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
datafile=${inputdir}'data.dat'
paramfile=${inputdir}'param.par'

infoline --
infolog 'Testing divafit without data weight'
infoline --

Nseed=226342.444
awk -v Ndata=1000 -v Nseed=${Nseed} 'BEGIN {srand(Nseed); for (i = 1; i <= Ndata; i++)
        {x=rand();y=rand();print x,y,3*x*x-2*y-1} }' > ${datafile}

echo '# Correlation Length lc' > ${paramfile}
echo '0.2' >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '51' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '51' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

./divafit

divaecho " "
echo 'Estimated correlation length L: '$(awk 'FNR == 2 { print; exit }' ./output/paramfit.dat)
divaecho 'Expected value of L:             0.197846353'

divaecho --------------------------------------------------
divaecho 'Testing divafit with random data weight'
divaecho --------------------------------------------------
divaecho ' '

Nseed=226342.444
awk -v Ndata=1000 -v Nseed=${Nseed} 'BEGIN {srand(Nseed); for (i = 1; i <= Ndata; i++)
        {x=rand();y=rand();w=rand();print x,y,3*x*x-2*y-1,w} }' > ${datafile}

./divafit

divaecho " "
divaecho 'Estimated correlation length L: '$(awk 'FNR == 2 { print; exit }' ./output/paramfit.dat)
divaecho 'Expected value of L:             0.179912895'
