#!/bin/bash
source divalogging

infolog --
infolog 'Running divamesh with a decreasing correlation length (finer mesh)'
infolog

CLlist=( 10 5 2.5 1 0.5 0.25 0.1 0.05 0.025)
inputdir=$(pwd)'/input/'
contfile=${inputdir}'coast.cont'
paramfile=${inputdir}'param.par'
tmpfile=$(mktemp)

mkdir -pv logs

# Add divaclean to avoid working on old files!
divaclean

##echo ${inputdir}
divaecho '1. Creating a simple contour file'
divaecho ' '

echo 2 > ${contfile}
echo 4 >> ${contfile}
echo -1 -1 >> ${contfile}
echo 1 -1 >> ${contfile}
echo 1  1 >> ${contfile}
echo -1 1 >> ${contfile}
echo 4 >> ${contfile}
echo 0.4 0.2 >> ${contfile}
echo 0.4 0.8 >> ${contfile}
echo 0.6 0.8 >> ${contfile}
echo 0.6 0.2 >> ${contfile}


divaecho '2. Creating base parameter file'
divaecho ' '

echo '# Correlation Length lc' > ${paramfile}
echo ${correlationLength} >> ${paramfile}
echo '# icoordchange' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# ispec' >> ${paramfile}
echo '11' >> ${paramfile}
echo '# ireg' >> ${paramfile}
echo '0' >> ${paramfile}
echo '# xori' >> ${paramfile}
echo '-1' >> ${paramfile}
echo '# yori' >> ${paramfile}
echo '-1' >> ${paramfile}
echo '# dx' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# dy' >> ${paramfile}
echo '0.02' >> ${paramfile}
echo '# nx' >> ${paramfile}
echo '101' >> ${paramfile}
echo '#ny' >> ${paramfile}
echo '101' >> ${paramfile}
echo '# valex' >> ${paramfile}
echo '-99' >> ${paramfile}
echo '# snr' >> ${paramfile}
echo '1.0' >> ${paramfile}
echo '# varbak' >> ${paramfile}
echo '1.0' >> ${paramfile}

logfile='./logs/testmesh_'`date +%Y-%m-%d-%H-%M-%S`'.log'
divaecho "Writing results in ${logfile}"
echo 'Correlation length (degrees)      Time (seconds)	Nodes	Interfaces	Elements' > ${logfile}

# Loop on the listed values of correlation length
for correlationLength in "${CLlist[@]}"
do
  divaecho "Working with CL: ${correlationLength}"
  # Replace value in param.par
  awk -v CL=${correlationLength} 'NR==2 {$0=CL} { print }' ${paramfile} > ${tmpfile}
  mv ${tmpfile} ${paramfile}
  timeinit=$(date +%s.%N)

  ./divamesh

  timeend=$(date +%s.%N)
  timemesh=$(echo ${timeend} ${timeinit} | awk '{print ($1-$2)}')

  topomesh=./meshgenwork/fort.23
  {
  read nodes
  read interfaces
  read elements
   } < $topomesh

  echo ${correlationLength}       ${timemesh}	${nodes}	${interfaces}	${elements}   >> ${logfile}

done

infolog --
infolog "Check results of the test in ${logfile}"
infolog "End mesh speed test"
infolog --
