#!/bin/bash

# Name of the fortran compiler
#-----------------------------

compiler=ifort			#--charles
compiler=gfortran


# To use parall version, put value to 1
#-------------------------------------
DIVA_PARALLEL=0
#

# Compilation flags
#-----------------

flags='-O3   '			#--charles
#flags='-O0' 			# no optimization


flagscalc=' -cpp '
if [ "$DIVA_PARALLEL" = 1 ]
then
echo Going to use parallel version
flagscalc='-cpp -fopenmp -DDIVAPARALLEL '
echo $flagscalc

fi

# Netcdf library
#---------------

ncconfigok=$(type -P nc-config | wc -l)
echo $ncconfigok
if [ "$ncconfigok" != "0" ]
then
nclib=`nc-config --flibs`
compiler=`nc-config --fc`
else
nclib=/usr/lib/libnetcdff.dll.a	#--charles
fi
# Use of Plplot (creation of scientific plots)
#--------------

Plplot=Plplot
Plplot=NoPlplot

# gui = 1 for Graphical User Interface programs to be compiled
gui=1

# netcdf = 1 for NetCDF programs to be compiled
netcdf=1
